# Generated by Django 4.1.4 on 2023-01-03 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("siren", models.CharField(max_length=9, unique=True)),
                (
                    "effectif",
                    models.CharField(
                        choices=[
                            ("petit", "moins de 50"),
                            ("moyen", "entre 50 et 300"),
                            ("grand", "entre 301 et 499"),
                            ("sup500", "500 et plus"),
                        ],
                        help_text="Vérifiez et confirmez le nombre de salariés",
                        max_length=9,
                    ),
                ),
                ("bdese_accord", models.BooleanField(default=False)),
                ("raison_sociale", models.CharField(default="", max_length=250)),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
