# Generated by Django 4.1.2 on 2022-12-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise",
            name="effectif",
            field=models.CharField(
                choices=[
                    ("petit", "moins de 50"),
                    ("moyen", "entre 50 et 300"),
                    ("grand", "entre 301 et 499"),
                    ("sup500", "500 et plus"),
                ],
                help_text="Vérifiez et confirmez le nombre de salariés",
                max_length=9,
            ),
        ),
    ]
