# Generated by Django 4.1.2 on 2023-01-10 09:53
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0003_create_through_relations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entreprise",
            name="users",
        ),
        migrations.AlterField(
            model_name="Habilitation",
            name="fonctions",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
