# Generated by Django 4.1.2 on 2023-01-10 09:55
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entreprises", "0004_remove_entreprise_users_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="users",
            field=models.ManyToManyField(
                through="entreprises.Habilitation", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
