# Generated by Django 4.1.4 on 2023-01-10 13:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0005_entreprise_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habilitation",
            name="fonctions",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Fonction(s) dans la société",
            ),
        ),
    ]
