# Generated by Django 4.1.5 on 2023-01-27 15:10
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0006_alter_habilitation_fonctions"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="entreprise",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
