# Generated by Django 4.1.5 on 2023-02-24 09:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0007_entreprise_created_at_entreprise_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise",
            name="effectif",
            field=models.CharField(
                choices=[
                    ("petit", "moins de 50"),
                    ("moyen", "entre 50 et 300"),
                    ("grand", "entre 301 et 499"),
                    ("sup500", "plus de 500"),
                ],
                help_text="Vérifiez et confirmez le nombre de salariés",
                max_length=9,
            ),
        ),
    ]
