# Generated by Django 4.1.7 on 2023-03-03 15:36
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0008_alter_entreprise_effectif"),
    ]

    operations = [
        migrations.AddField(
            model_name="habilitation",
            name="confirmed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
