# Generated by Django 4.1.7 on 2023-03-07 14:59
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("habilitations", "0002_copy_habilitations_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entreprises", "0010_alter_habilitation_entreprise_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise",
            name="users",
            field=models.ManyToManyField(
                through="habilitations.Habilitation", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
