# Generated by Django 4.1.7 on 2023-03-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0013_alter_entreprise_bdese_accord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise",
            name="effectif",
            field=models.CharField(
                choices=[
                    ("petit", "moins de 50"),
                    ("moyen", "entre 50 et 300"),
                    ("grand", "entre 301 et 499"),
                    ("sup500", "plus de 500"),
                ],
                help_text="Vérifiez et confirmez le nombre de salariés",
                max_length=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="raison_sociale",
            field=models.CharField(max_length=250),
        ),
    ]
