# Generated by Django 4.1.7 on 2023-03-28 14:55
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0014_alter_entreprise_effectif_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entreprise",
            old_name="raison_sociale",
            new_name="denomination",
        ),
    ]
