# Generated by Django 4.2.1 on 2023-06-02 12:30
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0016_alter_entreprise_effectif"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.IntegerField()),
            ],
        ),
    ]
