# Generated by Django 4.2.1 on 2023-06-02 13:05
from datetime import date

import django.db.models.deletion
from django.db import migrations
from django.db import models


def migrate_entreprise_yearly_data_to_dedicated_class(apps, schema_editor):
    annee = date.today().year
    Entreprise = apps.get_model("entreprises", "Entreprise")
    Evolution = apps.get_model("entreprises", "Evolution")
    for entreprise in Entreprise.objects.all():
        if entreprise.effectif:
            evolution = Evolution.objects.create(
                annee=annee - 1,
                entreprise=entreprise,
                effectif=entreprise.effectif,
                bdese_accord=entreprise.bdese_accord,
            )
            evolution.save()


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0017_evolution"),
    ]

    operations = [
        migrations.AddField(
            model_name="evolution",
            name="bdese_accord",
            field=models.BooleanField(
                default=False,
                verbose_name="L'entreprise a un accord collectif d'entreprise concernant la Base de Données Économiques, Sociales et Environnementales (BDESE)",
            ),
        ),
        migrations.AddField(
            model_name="evolution",
            name="effectif",
            field=models.CharField(
                choices=[
                    ("0-49", "moins de 50 salariés"),
                    ("50-299", "entre 50 et 299 salariés"),
                    ("300-499", "entre 300 et 499 salariés"),
                    ("500+", "500 salariés ou plus"),
                ],
                help_text="Vérifiez et confirmez le nombre de salariés",
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="evolution",
            name="entreprise",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="entreprises.entreprise",
            ),
        ),
        migrations.RunPython(
            migrate_entreprise_yearly_data_to_dedicated_class,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="entreprise",
            name="bdese_accord",
        ),
        migrations.RemoveField(
            model_name="entreprise",
            name="effectif",
        ),
    ]
