# Generated by Django 4.2 on 2023-06-16 10:00
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0020_evolution_uniques_caracteristiques_annuelles"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Evolution",
            new_name="CaracteristiquesAnnuelles",
        ),
        migrations.AlterModelOptions(
            name="caracteristiquesannuelles",
            options={
                "verbose_name": "Caractéristiques annuelles",
                "verbose_name_plural": "Caractéristiques annuelles",
            },
        ),
    ]
