# Generated by Django 4.2 on 2023-06-16 10:33
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0021_rename_evolution_caracteristiquesannuelles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="entreprises.entreprise"
            ),
        ),
    ]
