# Generated by Django 4.2.2 on 2023-06-30 15:18
import time

from django.db import migrations
from django.db import models

from api.recherche_entreprises import recherche_par_siren
from entreprises.models import CaracteristiquesAnnuelles as Caracs


def supprime_la_tranche_50_299(apps, schema_editor):
    CaracteristiquesAnnuelles = apps.get_model(
        "entreprises", "CaracteristiquesAnnuelles"
    )
    for caracteristique in CaracteristiquesAnnuelles.objects.all():
        if caracteristique.effectif == "50-299":  # cette tranche n'existe plus
            caracteristique.effectif = devine_effectif(caracteristique.entreprise.siren)
            print(f"{caracteristique.entreprise.siren}, {caracteristique.effectif}")
            caracteristique.save()


def devine_effectif(siren):
    resultats = recherche_par_siren(siren)
    time.sleep(
        1 / 5
    )  # attendre après un appel à API entreprise pour éviter de dépasser le quota (7 appels / seconde)
    if resultats["effectif"] == Caracs.EFFECTIF_ENTRE_50_ET_249:
        return Caracs.EFFECTIF_ENTRE_50_ET_249
    else:
        return Caracs.EFFECTIF_ENTRE_250_ET_299


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0023_caracteristiquesannuelles_effectif_outre_mer"),
    ]

    operations = [
        migrations.AddField(
            model_name="caracteristiquesannuelles",
            name="tranche_bilan",
            field=models.CharField(
                choices=[
                    ("0-350k", "moins de 350k€"),
                    ("350k-6M", "entre 350k€ et 6M€"),
                    ("6M-20M", "entre 6M€ et 20M€"),
                    ("20M-43M", "entre 20M€ et 43M€"),
                    ("43M-100M", "entre 43M€ et 100M€"),
                    ("100M+", "100M€ ou plus"),
                ],
                max_length=9,
                null=True,
                verbose_name="Bilan",
            ),
        ),
        migrations.AddField(
            model_name="caracteristiquesannuelles",
            name="tranche_chiffre_affaires",
            field=models.CharField(
                choices=[
                    ("0-700k", "moins de 700k€"),
                    ("700k-12M", "entre 700k€ et 12M€"),
                    ("12M-40M", "entre 12M€ et 40M€"),
                    ("40M-50M", "entre 40M€ et 50M€"),
                    ("50M-100M", "entre 50M€ et 100M€"),
                    ("100M+", "100M€ ou plus"),
                ],
                max_length=9,
                null=True,
                verbose_name="Chiffre d'affaires",
            ),
        ),
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="effectif",
            field=models.CharField(
                choices=[
                    ("0-49", "moins de 50 salariés"),
                    ("50-249", "entre 50 et 249 salariés"),
                    ("250-299", "entre 250 et 299 salariés"),
                    ("300-499", "entre 300 et 499 salariés"),
                    ("500+", "500 salariés ou plus"),
                ],
                help_text="Vérifiez et confirmez le nombre de salariés",
                max_length=9,
                null=True,
                verbose_name="Effectif total",
            ),
        ),
        migrations.RunPython(
            supprime_la_tranche_50_299,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
