# Generated by Django 4.2.2 on 2023-07-11 12:41
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0026_entreprise_date_cloture_exercice"),
    ]

    operations = [
        migrations.AddField(
            model_name="caracteristiquesannuelles",
            name="date_cloture_exercice",
            field=models.DateField(
                null=True, verbose_name="Date de clôture de l'exercice comptable"
            ),
        ),
    ]
