# Generated by Django 4.2.2 on 2023-08-01 15:08
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0027_caracteristiquesannuelles_date_cloture_exercice"),
    ]

    operations = [
        migrations.AddField(
            model_name="caracteristiquesannuelles",
            name="tranche_bilan_consolide",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0-350k", "moins de 350k€"),
                    ("350k-6M", "entre 350k€ et 6M€"),
                    ("6M-20M", "entre 6M€ et 20M€"),
                    ("20M-43M", "entre 20M€ et 43M€"),
                    ("43M-100M", "entre 43M€ et 100M€"),
                    ("100M+", "100M€ ou plus"),
                ],
                max_length=9,
                null=True,
                verbose_name="Bilan consolidé du groupe",
            ),
        ),
        migrations.AddField(
            model_name="caracteristiquesannuelles",
            name="tranche_chiffre_affaires_consolide",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0-700k", "moins de 700k€"),
                    ("700k-12M", "entre 700k€ et 12M€"),
                    ("12M-40M", "entre 12M€ et 40M€"),
                    ("40M-50M", "entre 40M€ et 50M€"),
                    ("50M-100M", "entre 50M€ et 100M€"),
                    ("100M+", "100M€ ou plus"),
                ],
                max_length=9,
                null=True,
                verbose_name="Chiffre d'affaires consolidé du groupe",
            ),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="appartient_groupe",
            field=models.BooleanField(
                null=True, verbose_name="L'entreprise fait partie d'un groupe"
            ),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="comptes_consolides",
            field=models.BooleanField(
                null=True,
                verbose_name="Le groupe d'entreprises établit des comptes consolidés",
            ),
        ),
    ]
