# Generated by Django 4.2.2 on 2023-08-22 16:57
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "entreprises",
            "0028_caracteristiquesannuelles_tranche_bilan_consolide_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="bdese_accord",
            field=models.BooleanField(
                null=True,
                verbose_name="L'entreprise a un accord collectif d'entreprise concernant la Base de Données Économiques, Sociales et Environnementales (BDESE)",
            ),
        ),
    ]
