# Generated by Django 4.2 on 2023-08-30 12:46
import time

from django.db import migrations
from django.db import models

from api.recherche_entreprises import recherche

EFFECTIF_ENTRE_500_ET_4999 = "500-4999"
EFFECTIF_ENTRE_5000_ET_9999 = "5000-9999"
EFFECTIF_10000_ET_PLUS = "10000+"


def supprime_la_tranche_500_et_plus(apps, schema_editor):
    CaracteristiquesAnnuelles = apps.get_model(
        "entreprises", "CaracteristiquesAnnuelles"
    )
    for caracteristique in CaracteristiquesAnnuelles.objects.all():
        if caracteristique.effectif == "500+":  # cette tranche n'existe plus
            caracteristique.effectif = devine_effectif(caracteristique.entreprise.siren)
            print(f"{caracteristique.entreprise.siren}, {caracteristique.effectif}")
            caracteristique.save()


def devine_effectif(siren):
    resultats = recherche(siren)
    time.sleep(
        1 / 5
    )  # attendre après un appel à API entreprise pour éviter de dépasser le quota (7 appels / seconde)
    effectif = resultats["effectif"]
    if effectif in (
        EFFECTIF_ENTRE_500_ET_4999,
        EFFECTIF_ENTRE_5000_ET_9999,
        EFFECTIF_10000_ET_PLUS,
    ):
        return effectif
    else:
        print(
            f"WARNING L'entreprise {siren} a un effectif inférieur à 500 d'après l'API recherche entreprises ({effectif})"
        )
        return EFFECTIF_ENTRE_500_ET_4999


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0029_alter_caracteristiquesannuelles_bdese_accord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="effectif",
            field=models.CharField(
                choices=[
                    ("0-49", "moins de 50 salariés"),
                    ("50-249", "entre 50 et 249 salariés"),
                    ("250-299", "entre 250 et 299 salariés"),
                    ("300-499", "entre 300 et 499 salariés"),
                    ("500-4999", "entre 500 et 4 999 salariés"),
                    ("5000-9999", "entre 5 000 et 9 999 salariés"),
                    ("10000+", "10 000 salariés ou plus"),
                ],
                help_text="Vérifiez et confirmez le nombre de salariés",
                max_length=9,
                null=True,
                verbose_name="Effectif total",
            ),
        ),
        migrations.RunPython(
            supprime_la_tranche_500_et_plus,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
