# Generated by Django 4.2.3 on 2023-09-26 14:57
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0031_caracteristiquesannuelles_effectif_groupe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="effectif",
            field=models.CharField(
                choices=[
                    ("", "Sélectionnez une réponse"),
                    ("0-49", "moins de 50 salariés"),
                    ("50-249", "entre 50 et 249 salariés"),
                    ("250-299", "entre 250 et 299 salariés"),
                    ("300-499", "entre 300 et 499 salariés"),
                    ("500-4999", "entre 500 et 4 999 salariés"),
                    ("5000-9999", "entre 5 000 et 9 999 salariés"),
                    ("10000+", "10 000 salariés ou plus"),
                ],
                help_text="Nombre de salariés de l'entreprise",
                max_length=9,
                null=True,
                verbose_name="Effectif",
            ),
        ),
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="effectif_groupe",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sélectionnez une réponse"),
                    ("0-49", "moins de 50 salariés"),
                    ("50-249", "entre 50 et 249 salariés"),
                    ("250-499", "entre 250 et 499 salariés"),
                    ("500-4999", "entre 500 et 4 999 salariés"),
                    ("5000-9999", "entre 5 000 et 9 999 salariés"),
                    ("10000+", "10 000 salariés ou plus"),
                ],
                help_text="Nombre de salariés du groupe",
                max_length=9,
                null=True,
                verbose_name="Effectif du groupe",
            ),
        ),
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="effectif_outre_mer",
            field=models.CharField(
                choices=[
                    ("", "Sélectionnez une réponse"),
                    ("0-249", "moins de 250 salariés"),
                    ("250+", "250 salariés ou plus"),
                ],
                help_text="Nombre de salariés dans les régions et départements d'outre-mer",
                max_length=9,
                null=True,
                verbose_name="Effectif outre-mer",
            ),
        ),
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="tranche_bilan",
            field=models.CharField(
                choices=[
                    ("", "Sélectionnez une réponse"),
                    ("0-350k", "moins de 350k€"),
                    ("350k-6M", "entre 350k€ et 6M€"),
                    ("6M-20M", "entre 6M€ et 20M€"),
                    ("20M-43M", "entre 20M€ et 43M€"),
                    ("43M-100M", "entre 43M€ et 100M€"),
                    ("100M+", "100M€ ou plus"),
                ],
                max_length=9,
                null=True,
                verbose_name="Bilan",
            ),
        ),
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="tranche_bilan_consolide",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sélectionnez une réponse"),
                    ("0-350k", "moins de 350k€"),
                    ("350k-6M", "entre 350k€ et 6M€"),
                    ("6M-20M", "entre 6M€ et 20M€"),
                    ("20M-43M", "entre 20M€ et 43M€"),
                    ("43M-100M", "entre 43M€ et 100M€"),
                    ("100M+", "100M€ ou plus"),
                ],
                max_length=9,
                null=True,
                verbose_name="Bilan consolidé du groupe",
            ),
        ),
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="tranche_chiffre_affaires",
            field=models.CharField(
                choices=[
                    ("", "Sélectionnez une réponse"),
                    ("0-700k", "moins de 700k€"),
                    ("700k-12M", "entre 700k€ et 12M€"),
                    ("12M-40M", "entre 12M€ et 40M€"),
                    ("40M-50M", "entre 40M€ et 50M€"),
                    ("50M-100M", "entre 50M€ et 100M€"),
                    ("100M+", "100M€ ou plus"),
                ],
                max_length=9,
                null=True,
                verbose_name="Chiffre d'affaires",
            ),
        ),
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="tranche_chiffre_affaires_consolide",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sélectionnez une réponse"),
                    ("0-700k", "moins de 700k€"),
                    ("700k-12M", "entre 700k€ et 12M€"),
                    ("12M-40M", "entre 12M€ et 40M€"),
                    ("40M-50M", "entre 40M€ et 50M€"),
                    ("50M-100M", "entre 50M€ et 100M€"),
                    ("100M+", "100M€ ou plus"),
                ],
                max_length=9,
                null=True,
                verbose_name="Chiffre d'affaires consolidé du groupe",
            ),
        ),
    ]
