# Generated by Django 4.2.3 on 2023-09-26 14:57
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0031_caracteristiquesannuelles_effectif_groupe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="effectif",
            field=models.CharField(
                choices=[
                    ("0-49", "moins de 50 salariés"),
                    ("50-249", "entre 50 et 249 salariés"),
                    ("250-299", "entre 250 et 299 salariés"),
                    ("300-499", "entre 300 et 499 salariés"),
                    ("500-4999", "entre 500 et 4 999 salariés"),
                    ("5000-9999", "entre 5 000 et 9 999 salariés"),
                    ("10000+", "10 000 salariés ou plus"),
                ],
                help_text="Nombre de salariés de l'entreprise",
                max_length=9,
                null=True,
                verbose_name="Effectif",
            ),
        ),
    ]
