# Generated by Django 4.2.6 on 2023-10-25 13:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0032_alter_caracteristiquesannuelles_effectif"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="date_derniere_qualification",
            field=models.DateField(
                null=True, verbose_name="Date de la dernière qualification"
            ),
        ),
    ]
