# Generated by Django 4.2.7 on 2023-12-27 08:43
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0038_alter_caracteristiquesannuelles_effectif_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caracteristiquesannuelles",
            name="effectif_groupe_france",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sélectionnez une réponse"),
                    ("0-49", "moins de 50 salariés"),
                    ("50-249", "entre 50 et 249 salariés"),
                    ("250-499", "entre 250 et 499 salariés"),
                    ("500-4999", "entre 500 et 4 999 salariés"),
                    ("5000-9999", "entre 5 000 et 9 999 salariés"),
                    ("10000+", "10 000 salariés ou plus"),
                ],
                help_text="Nombre de salariés (notamment CDI, CDD et salariés à temps partiel) employés par les entreprises françaises du groupe au prorata de leur temps de présence au cours des douze mois précédents (cf. <a href='https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006072050/LEGISCTA000006177833/#LEGISCTA000006177833' target='_blank' rel='noopener'>articles L.1111-2 et L.1111-3 du Code du Travail</a>)",
                max_length=9,
                null=True,
                verbose_name="Effectif du groupe France",
            ),
        ),
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="effectif_groupe",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sélectionnez une réponse"),
                    ("0-49", "moins de 50 salariés"),
                    ("50-249", "entre 50 et 249 salariés"),
                    ("250-499", "entre 250 et 499 salariés"),
                    ("500-4999", "entre 500 et 4 999 salariés"),
                    ("5000-9999", "entre 5 000 et 9 999 salariés"),
                    ("10000+", "10 000 salariés ou plus"),
                ],
                help_text="Nombre de salariés employés par les entreprises du groupe en incluant les filiales directes ou indirectes étrangères",
                max_length=9,
                null=True,
                verbose_name="Effectif du groupe international",
            ),
        ),
    ]
