# Generated by Django 4.2.7 on 2023-12-27 10:50
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "entreprises",
            "0039_caracteristiquesannuelles_effectif_groupe_france_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="est_societe_mere",
            field=models.BooleanField(
                null=True, verbose_name="L'entreprise est la société mère du groupe"
            ),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="societe_mere_en_france",
            field=models.BooleanField(
                null=True,
                verbose_name="La société mère du groupe a son siège social en France",
            ),
        ),
    ]
