# Generated by Django 4.2.10 on 2024-03-07 14:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "entreprises",
            "0043_alter_caracteristiquesannuelles_tranche_bilan_consolide_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="est_interet_public",
            field=models.BooleanField(
                help_text="Entreprises cotées, établissements de crédit, entreprises d'assurance, mutuelles et unions, institutions de prévoyance et unions, organismes de liquidation (cf. <a href='https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2013:182:0019:0076:FR:PDF' target='_blank' rel='noopener'>article 2 directive comptable du 26 juin 2013</a>)",
                null=True,
                verbose_name="L'entreprise est d'intérêt public",
            ),
        ),
    ]
