# Generated by Django 4.2.10 on 2024-03-07 14:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "entreprises",
            "0043_alter_caracteristiquesannuelles_tranche_bilan_consolide_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="est_interet_public",
            field=models.BooleanField(
                null=True, verbose_name="L'entreprise est d'intérêt public"
            ),
        ),
    ]
