# Generated by Django 4.2.10 on 2024-03-08 11:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0044_entreprise_est_interet_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="code_pays_etranger_sirene",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
