# Generated by Django 4.2.3 on 2024-03-12 10:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("entreprises", "0045_entreprise_code_pays_etranger_sirene"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="tranche_bilan",
            field=models.CharField(
                choices=[
                    ("", "Sélectionnez une réponse"),
                    ("0-450k", "entre 0 et 450k€"),
                    ("450k-20M", "entre 450k€ et 20M€"),
                    ("20M-25M", "entre 20M€ et 25M€"),
                    ("25M-43M", "entre 25M€ et 43M€"),
                    ("43M-100M", "entre 43M€ et 100M€"),
                    ("100M+", "100M€ ou plus"),
                ],
                max_length=9,
                null=True,
                verbose_name="Bilan",
            ),
        ),
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="tranche_chiffre_affaires",
            field=models.CharField(
                choices=[
                    ("", "Sélectionnez une réponse"),
                    ("0-900k", "entre 0 et 900k€"),
                    ("900k-40M", "entre 900k€ et 40M€"),
                    ("40M-50M", "entre 40M€ et 50M€"),
                    ("50M-100M", "entre 50M€ et 100M€"),
                    ("100M+", "100M€ ou plus"),
                ],
                max_length=9,
                null=True,
                verbose_name="Chiffre d'affaires",
            ),
        ),
    ]
