# Generated by Django 4.2.10 on 2024-03-14 14:42
from django.db import migrations
from django.db import models


def maj_tranches_ca_et_bilan(apps, schema_editor):
    """Mise-à-jour des tranches de CA et bilan suite à l'obsolescence de la DPEF
    Tranches de CA :
    - les tranches 900k-40M et 40M-50M sont fusionnées dans 900k-50M
    - les tranches consolidées 0-40M et 40M-60M sont fusionnées dans 0-60M
    Tranches de bilan :
    - les tranches 450k-20M et 20M-25M sont fusionnées dans 450k-25M
    - les tranches consolidées 0-20M et 20M-30M sont fusionnées dans 0-30M
    """
    CaracteristiquesAnnuelles = apps.get_model(
        "entreprises", "CaracteristiquesAnnuelles"
    )
    for caracteristiques in CaracteristiquesAnnuelles.objects.all():
        sont_modifiees = False
        ancien_ca = caracteristiques.tranche_chiffre_affaires
        if ancien_ca in ("900k-40M", "40M-50M"):
            nouveau_ca = "900k-50M"
            sont_modifiees = True
        else:
            nouveau_ca = ancien_ca

        ancien_ca_consolide = caracteristiques.tranche_chiffre_affaires_consolide
        if ancien_ca_consolide in ("0-40M", "40M-60M"):
            nouveau_ca_consolide = "0-60M"
            sont_modifiees = True
        else:
            nouveau_ca_consolide = ancien_ca_consolide

        ancien_bilan = caracteristiques.tranche_bilan
        if ancien_bilan in ("450k-20M", "20M-25M"):
            nouveau_bilan = "450k-25M"
            sont_modifiees = True
        else:
            nouveau_bilan = ancien_bilan

        ancien_bilan_consolide = caracteristiques.tranche_bilan_consolide
        if ancien_bilan_consolide in ("0-20M", "20M-30M"):
            nouveau_bilan_consolide = "0-30M"
            sont_modifiees = True
        else:
            nouveau_bilan_consolide = ancien_bilan_consolide

        if sont_modifiees:
            print(
                (
                    "MODIFICATION",
                    caracteristiques.entreprise.siren,
                    caracteristiques.entreprise.denomination,
                    caracteristiques.id,
                    f"CA ancien: {ancien_ca} nouveau: {nouveau_ca}",
                    f"CA consolide ancien: {ancien_ca_consolide} nouveau: {nouveau_ca_consolide}",
                    f"Bilan ancien: {ancien_bilan} nouveau: {nouveau_bilan}",
                    f"Bilan consolide ancien: {ancien_bilan_consolide} nouveau: {nouveau_bilan_consolide}",
                )
            )
            caracteristiques.tranche_chiffre_affaires = nouveau_ca
            caracteristiques.tranche_chiffre_affaires_consolide = nouveau_ca_consolide
            caracteristiques.tranche_bilan = nouveau_bilan
            caracteristiques.tranche_bilan_consolide = nouveau_bilan_consolide
            caracteristiques.save()


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0046_alter_caracteristiquesannuelles_tranche_bilan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="tranche_bilan",
            field=models.CharField(
                choices=[
                    ("", "Sélectionnez une réponse"),
                    ("0-450k", "entre 0 et 450k€"),
                    ("450k-25M", "entre 450k€ et 25M€"),
                    ("25M-43M", "entre 25M€ et 43M€"),
                    ("43M-100M", "entre 43M€ et 100M€"),
                    ("100M+", "100M€ ou plus"),
                ],
                max_length=9,
                null=True,
                verbose_name="Bilan",
            ),
        ),
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="tranche_bilan_consolide",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sélectionnez une réponse"),
                    ("0-30M", "entre 0 et 30M€"),
                    ("30M-43M", "entre 30M€ et 43M€"),
                    ("43M-100M", "entre 43M€ et 100M€"),
                    ("100M+", "100M€ ou plus"),
                ],
                max_length=9,
                null=True,
                verbose_name="Bilan consolidé du groupe",
            ),
        ),
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="tranche_chiffre_affaires",
            field=models.CharField(
                choices=[
                    ("", "Sélectionnez une réponse"),
                    ("0-900k", "entre 0 et 900k€"),
                    ("900k-50M", "entre 900k€ et 50M€"),
                    ("50M-100M", "entre 50M€ et 100M€"),
                    ("100M+", "100M€ ou plus"),
                ],
                max_length=9,
                null=True,
                verbose_name="Chiffre d'affaires",
            ),
        ),
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="tranche_chiffre_affaires_consolide",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sélectionnez une réponse"),
                    ("0-60M", "entre 0 et 60M€"),
                    ("60M-100M", "entre 60M€ et 100M€"),
                    ("100M+", "100M€ ou plus"),
                ],
                max_length=9,
                null=True,
                verbose_name="Chiffre d'affaires consolidé du groupe",
            ),
        ),
        migrations.RunPython(
            maj_tranches_ca_et_bilan,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
