# Generated by Django 4.2.11 on 2024-05-23 15:22
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("entreprises", "0047_alter_caracteristiquesannuelles_tranche_bilan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="code_NAF",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
