# Generated by Django 5.1.7 on 2025-06-05 14:02
from django.db import migrations
from django.db import models


def remplissage_effectif_securite_sociale(apps, schema_editor):
    CaracteristiquesAnnuelles = apps.get_model(
        "entreprises", "CaracteristiquesAnnuelles"
    )
    for caracteristiques_annuelles in CaracteristiquesAnnuelles.objects.all():
        maj(caracteristiques_annuelles)


def maj(caracteristiques_annuelles):
    if not caracteristiques_annuelles.effectif:
        return

    if caracteristiques_annuelles.effectif == "0-9":
        caracteristiques_annuelles.effectif_securite_sociale = (
            "0-9"  # EFFECTIF_SECURITE_SOCIALE_MOINS_DE_10
        )
    elif caracteristiques_annuelles.effectif == "10-49":
        caracteristiques_annuelles.effectif_securite_sociale = (
            "10-49"  # EFFECTIF_SECURITE_SOCIALE_ENTRE_10_ET_49
        )
    elif caracteristiques_annuelles.effectif == "50-249":
        caracteristiques_annuelles.effectif_securite_sociale = (
            "50-249"  # EFFECTIF_SECURITE_SOCIALE_ENTRE_50_ET_249
        )
    elif caracteristiques_annuelles.effectif in (
        "250-299",
        "300-499",
    ):
        caracteristiques_annuelles.effectif_securite_sociale = (
            "250-499"  # EFFECTIF_SECURITE_SOCIALE_ENTRE_250_ET_499
        )
    else:
        caracteristiques_annuelles.effectif_securite_sociale = (
            "500+"  # EFFECTIF_SECURITE_SOCIALE_500_ET_PLUS
        )
    caracteristiques_annuelles.save()


class Migration(migrations.Migration):
    dependencies = [
        ("entreprises", "0048_entreprise_code_naf"),
    ]

    operations = [
        migrations.AddField(
            model_name="caracteristiquesannuelles",
            name="effectif_securite_sociale",
            field=models.CharField(
                choices=[
                    ("", "Sélectionnez une réponse"),
                    ("0-9", "entre 0 et 9 salariés"),
                    ("10-49", "entre 10 et 49 salariés"),
                    ("50-249", "entre 50 et 249 salariés"),
                    ("250-499", "entre 250 et 499 salariés"),
                    ("500+", "500 ou plus"),
                ],
                help_text="Nombre de salariés (notamment CDI, CDD et salariés à temps partiel) au prorata de leur temps de présence au cours des douze mois précédents (cf. articles <a href='https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000051287151' target='_blank' rel='noopener'>L130-1</a> et <a href='https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000041455619' target='_blank' rel='noopener'>R130-1</a> du code de la sécurité sociale",
                max_length=9,
                null=True,
                verbose_name="Effectif sécurité sociale",
            ),
        ),
        migrations.AlterField(
            model_name="caracteristiquesannuelles",
            name="effectif",
            field=models.CharField(
                choices=[
                    ("", "Sélectionnez une réponse"),
                    ("0-9", "entre 0 et 9 salariés"),
                    ("10-49", "entre 10 et 49 salariés"),
                    ("50-249", "entre 50 et 249 salariés"),
                    ("250-299", "entre 250 et 299 salariés"),
                    ("300-499", "entre 300 et 499 salariés"),
                    ("500-4999", "entre 500 et 4 999 salariés"),
                    ("5000-9999", "entre 5 000 et 9 999 salariés"),
                    ("10000+", "10 000 salariés ou plus"),
                ],
                help_text="Nombre moyen de salariés, y compris les salariés mis à la disposition de l'entreprise par une entreprise extérieure présents depuis au moins un an (cf. <a href='https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006072050/LEGISCTA000006177833/#LEGISCTA000006177833' target='_blank' rel='noopener'>articles L.1111-2 et L.1111-3 du Code du Travail</a>)",
                max_length=9,
                null=True,
                verbose_name="Effectif code du travail",
            ),
        ),
        migrations.RunPython(
            remplissage_effectif_securite_sociale,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
