# Generated by Django 5.1.7 on 2025-06-06 12:44
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "entreprises",
            "0049_caracteristiquesannuelles_effectif_securite_sociale_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caracteristiquesannuelles",
            name="effectif_permanent",
        ),
    ]
