# Generated by Django 5.1.7 on 2025-06-10 13:45
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entreprises", "0050_remove_caracteristiquesannuelles_effectif_permanent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caracteristiquesannuelles",
            name="effectif_groupe_permanent",
        ),
    ]
