# Generated by Django 5.1.13 on 2025-10-23 05:15
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("analyseia", "0002_auto_20251014_1459"),
        (
            "entreprises",
            "0051_remove_caracteristiquesannuelles_effectif_groupe_permanent",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="analyses_ia",
            field=models.ManyToManyField(
                related_name="entreprises", to="analyseia.analyseia"
            ),
        ),
    ]
