# Generated by Django 5.1.12 on 2025-11-12 09:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("analyseia", "0002_auto_20251014_1459"),
        ("entreprises", "0052_entreprise_analyses_ia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise",
            name="analyses_ia",
            field=models.ManyToManyField(
                blank=True, related_name="entreprises", to="analyseia.analyseia"
            ),
        ),
    ]
