# Generated by Django 5.1.15 on 2026-04-02 10:32
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0053_alter_entreprise_analyses_ia"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="code_postal",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
