# Generated by Django 5.1.15 on 2026-04-14 14:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0054_entreprise_code_postal"),
    ]

    operations = [
        migrations.AddField(
            model_name="caracteristiquesannuelles",
            name="tranche_consommation_energie_finale",
            field=models.CharField(
                choices=[
                    ("", "Sélectionnez une réponse"),
                    ("0-2.75GWh", "inférieure à 2,75 GWh"),
                    ("2.75GWh-23.6GWh", "entre 2,75 GWh et 23,6 GWh"),
                    ("23.6GWh+", "supérieure ou égale à 23,6 GWh"),
                ],
                max_length=20,
                null=True,
                verbose_name="Consommation annuelle moyenne d'énergie finale",
            ),
        ),
    ]
