services:
  db:
    # note: les versions 13.x ne se déploient pas correctement
    # image: docker.io/scalingo/postgresql:14.13.0-1
    image: docker.io/scalingo/postgresql
    command: /postgresql
    environment:
       - DB_USER=rse
       - DB_PASSWORD=rse
       - DB_ADMIN_PASSWORD=admin
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "25432:5432"
  
  redis:
    image: redis:alpine
    ports:
      - "26379:6379"
    volumes:
      - redisdata:/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "29000:9000"
      - "29001:9001"
    volumes:
      - miniodata:/data

volumes:
  pgdata:
  redisdata:
  miniodata:
