# Generated by Django 4.1.2 on 2022-10-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0001_initial"),
        ("reglementations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BDESE_50_300",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.IntegerField(default=2022)),
                (
                    "capitaux_propres",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Capitaux propres de l'entreprise",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entreprises.entreprise",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
