# Generated by Django 4.1.4 on 2023-01-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bdese_300",
            name="annee",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="bdese_50_300",
            name="annee",
            field=models.IntegerField(),
        ),
    ]
