# Generated by Django 4.1.1 on 2022-10-27 14:33

from django.db import migrations, models
import django.forms.fields
import reglementations.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reglementations",
            "0002_bdese_50_300_actions_emploi_personnes_handicapees_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese_300",
            name="nombre_unites_absence_par_categorie_pro",
            field=reglementations.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Répartition des absences pour maladie selon leur catégorie",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="nombre_unites_absence_par_duree",
            field=reglementations.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=["< 3 jours", "de 3 à 90 jours", "> 90 jours"],
                null=True,
                verbose_name="Répartition des absences pour maladie selon leur durée",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_jours_feries_payes",
            field=reglementations.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de jours fériés payés",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="remunerations",
            field=models.TextField(
                blank=True,
                help_text="Faire une grille des rémunérations en distinguant au moins six tranches.",
                null=True,
                verbose_name="Grille des rémunérations",
            ),
        ),
    ]
