# Generated by Django 4.1.5 on 2023-01-20 17:49
import django.db.models.fields
from django.db import migrations

import reglementations.models.bdese


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0003_alter_bdese_300_nombre_unites_absence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese_50_300",
            name="completion_steps",
            field=reglementations.models.bdese.CategoryField(
                base_field=django.db.models.fields.BooleanField,
                categories=["Catégories professionnelles", "Données"],
                default=reglementations.models.bdese.bdese_50_300_completion_steps_default,
            ),
        ),
    ]
