# Generated by Django 4.1.2 on 2022-12-01 09:17

from django.db import migrations, models
import django.db.models.fields
import django.forms.fields
import reglementations.models


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0006_bdese_300_categories_professionnelles_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bdese_300",
            name="complement_salaire_conge",
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="complement_salaire_conge_adoption",
            field=models.BooleanField(
                default=False,
                help_text="Existence d'un complément de salaire versé par l'employeur pour le congé d'adoption",
                verbose_name="Complément de salaire pour le congé d'adoption",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="complement_salaire_conge_maternite",
            field=models.BooleanField(
                default=False,
                help_text="Existence d'un complément de salaire versé par l'employeur pour le congé de maternité",
                verbose_name="Complément de salaire pour le congé de maternité",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="complement_salaire_conge_paternite",
            field=models.BooleanField(
                default=False,
                help_text="Existence d'un complément de salaire versé par l'employeur pour le congé de paternité",
                verbose_name="Complément de salaire pour le congé de paternité",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="action_adaptation_au_poste_femme",
            field=reglementations.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de femmes ayant suivi une formation d'adaptation au poste",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="action_adaptation_au_poste_homme",
            field=reglementations.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre d'hommes ayant suivi une formation d'adaptation au poste",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="action_developpement_competences_femme",
            field=reglementations.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de femmes ayant suivi une formation pour le développement des compétences",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="action_developpement_competences_homme",
            field=reglementations.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre d'hommes ayant suivi une formation pour le développement des compétences",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="action_maintien_emploi_femme",
            field=reglementations.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de femmes ayant suivi une formation pour le maintien dans l'emploi",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="action_maintien_emploi_homme",
            field=reglementations.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre d'hommes ayant suivi une formation pour le maintien dans l'emploi",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="completion_steps",
            field=reglementations.models.CategoryField(
                base_field=django.db.models.fields.BooleanField,
                categories=(
                    "Investissement social",
                    "Investissement matériel et immatériel",
                    "Egalité professionnelle homme/femme",
                    "Fonds propres, endettement et impôts",
                    "Rémunérations",
                    "Représentation du personnel et Activités sociales et culturelles",
                    "Rémunération des financeurs",
                    "Flux financiers",
                    "Partenariats",
                    "Transferts commerciaux et financiers",
                    "Environnement",
                ),
                default=reglementations.models.bdese_300_completion_steps_default,
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="departs_retraite_femme",
            field=reglementations.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de femmes parties en retraite",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_accidents_par_elements_materiels_femme",
            field=models.TextField(
                blank=True,
                help_text="Faire référence aux codes de classification des éléments matériels des accidents (arrêté du 10 octobre 1974).",
                null=True,
                verbose_name="Répartition des accidents par éléments matériels chez les hommes",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_accidents_par_elements_materiels_homme",
            field=models.TextField(
                blank=True,
                help_text="Faire référence aux codes de classification des éléments matériels des accidents (arrêté du 10 octobre 1974).",
                null=True,
                verbose_name="Répartition des accidents par éléments matériels chez les hommes",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_50_300",
            name="nombre_journees_salaries_temporaires",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre de journées de travail réalisées au cours des douze derniers mois par les salariés temporaires",
            ),
        ),
    ]
