# Generated by Django 4.1.5 on 2023-01-27 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0006_rename_mecenat_bdese_50_300_mecenat_recu_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese_300",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="bdese_50_300",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bdese_50_300",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
