# Generated by Django 4.1.4 on 2023-01-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0008_remove_bdese_50_300_nombre_stagiaires_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese_300",
            name="indicateurs_externes",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="bdese_50_300",
            name="indicateurs_externes",
            field=models.JSONField(default=list),
        ),
    ]
