# Generated by Django 4.1.2 on 2022-12-01 11:35

from django.db import migrations
import django.forms.fields
import reglementations.models


def erase_nombre_departs_volontaires_retraite_preretraite(apps, schema_editor):
    BDESE_300 = apps.get_model("reglementations", "BDESE_300")
    for bdese in BDESE_300.objects.all():
        bdese.nombre_departs_volontaires_retraite_preretraite = None
        bdese.save()


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0009_alter_bdese_300_completion_steps"),
    ]

    operations = [
        migrations.RunPython(erase_nombre_departs_volontaires_retraite_preretraite),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_departs_volontaires_retraite_preretraite",
            field=reglementations.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="Distinguer les différents systèmes légaux et conventionnels de toute nature",
                null=True,
                verbose_name="Nombre de départs volontaires en retraite et préretraite",
            ),
        ),
    ]
