# Generated by Django 4.1.5 on 2023-01-24 17:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0009_bdese_300_indicateurs_externes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bdese_50_300",
            name="mecenat_recu",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Mécénat reçu"
            ),
        ),
        migrations.AlterField(
            model_name="bdese_50_300",
            name="mecenat_verse",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Mécénat versé"
            ),
        ),
    ]
