# Generated by Django 4.1.2 on 2022-12-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reglementations",
            "0010_alter_bdese_300_nombre_departs_volontaires_retraite_preretraite",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="bdese_300",
            old_name="nombre_unites_absence_par_duree",
            new_name="nombre_unites_absence_maladie_par_duree",
        ),
        migrations.RemoveField(
            model_name="bdese_300",
            name="nombre_unites_absence_par_categorie_pro",
        ),
    ]
