# Generated by Django 4.1.6 on 2023-02-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0010_alter_bdese_50_300_mecenat_recu_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bdese_300",
            old_name="indicateurs_externes",
            new_name="external_fields",
        ),
        migrations.RenameField(
            model_name="bdese_50_300",
            old_name="indicateurs_externes",
            new_name="external_fields",
        ),
    ]
