# Generated by Django 4.1.6 on 2023-02-15 14:05
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reglementations",
            "0011_rename_indicateurs_externes_bdese_300_external_fields_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese_300",
            name="niveaux_hierarchiques",
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name="Niveaux ou coefficients hiérachiques",
            ),
        ),
    ]
