# Generated by Django 4.1.2 on 2022-12-01 13:01

from django.db import migrations
import django.forms.fields
import reglementations.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reglementations",
            "0011_rename_nombre_unites_absence_par_duree_bdese_300_nombre_unites_absence_maladie_par_duree_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese_300",
            name="nombre_examens_medicaux_complementaires",
            field=reglementations.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=["soumis à surveillance", "autres"],
                null=True,
                verbose_name="Nombre d'examens médicaux complémentaires des travailleurs",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_examens_medicaux",
            field=reglementations.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=["suivi de droit commun", "suivi individuel renforcé"],
                null=True,
                verbose_name="Nombre d'examens médicaux des travailleurs",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_visites_medicales",
            field=reglementations.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=["suivi de droit commun", "suivi individuel renforcé"],
                help_text="Selon le type de suivi",
                null=True,
                verbose_name="Nombre de visites d'information et de prévention des travailleurs",
            ),
        ),
    ]
