# Generated by Django 4.1.6 on 2023-02-15 15:48
from django.db import migrations

import reglementations.models


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0012_bdese_300_niveaux_hierarchiques"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese_300",
            name="age_moyen_par_niveau_hierarchique_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["HIERARCHIQUE"],
                null=True,
                verbose_name="Age moyen des femmes par niveau ou coefficient hiérarchique",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="age_moyen_par_niveau_hierarchique_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["HIERARCHIQUE"],
                null=True,
                verbose_name="Age moyen des hommes par niveau ou coefficient hiérarchique",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="anciennete_moyenne_dans_niveau_hierarchique_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["HIERARCHIQUE"],
                null=True,
                verbose_name="Ancienneté moyenne des femmes dans chaque niveau ou coefficient hiérarchique",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="anciennete_moyenne_dans_niveau_hierarchique_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["HIERARCHIQUE"],
                null=True,
                verbose_name="Ancienneté moyenne des hommes dans chaque niveau ou coefficient hiérarchique",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="anciennete_moyenne_par_niveau_hierarchique_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["HIERARCHIQUE"],
                null=True,
                verbose_name="Ancienneté moyenne des femmes par niveau ou coefficient hiérarchique",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="anciennete_moyenne_par_niveau_hierarchique_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["HIERARCHIQUE"],
                null=True,
                verbose_name="Ancienneté moyenne des hommes par niveau ou coefficient hiérarchique",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="effectif_par_niveau_hierarchique_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["HIERARCHIQUE"],
                null=True,
                verbose_name="Répartition des effectifs femmes par niveau ou coefficient hiérarchique",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="effectif_par_niveau_hierarchique_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["HIERARCHIQUE"],
                null=True,
                verbose_name="Répartition des effectifs hommes par niveau ou coefficient hiérarchique",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="remuneration_par_niveau_hierarchique_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["HIERARCHIQUE"],
                help_text="Cet indicateur n'a pas à être renseigné lorsque sa mention est de nature à porter atteinte à la confidentialité des données correspondantes, compte tenu notamment du nombre réduit d'individus dans un niveau ou coefficient hiérarchique",
                null=True,
                verbose_name="Rémunération moyenne/médiane mensuelle des femmes par niveau ou coefficient hiérarchique",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="remuneration_par_niveau_hierarchique_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["HIERARCHIQUE"],
                help_text="Cet indicateur n'a pas à être renseigné lorsque sa mention est de nature à porter atteinte à la confidentialité des données correspondantes, compte tenu notamment du nombre réduit d'individus dans un niveau ou coefficient hiérarchique",
                null=True,
                verbose_name="Rémunération moyenne/médiane mensuelle des hommes par niveau ou coefficient hiérarchique",
            ),
        ),
    ]
