# Generated by Django 4.1.2 on 2022-12-01 14:57

from django.db import migrations
import django.forms.fields
import reglementations.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reglementations",
            "0013_remove_bdese_300_remuneration_moyenne_femme_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bdese_300",
            name="part_primes_non_mensuelle",
            field=reglementations.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Part des primes à périodicité non mensuelle dans la déclaration de salaire",
            ),
        ),
    ]
