# Generated by Django 4.1.7 on 2023-02-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0014_alter_bdese_300_completion_steps_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bdese_300",
            name="complement_salaire_conge_adoption",
            field=models.BooleanField(
                help_text="Existence d'un complément de salaire versé par l'employeur pour le congé d'adoption",
                null=True,
                verbose_name="Complément de salaire pour le congé d'adoption",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="complement_salaire_conge_maternite",
            field=models.BooleanField(
                help_text="Existence d'un complément de salaire versé par l'employeur pour le congé de maternité",
                null=True,
                verbose_name="Complément de salaire pour le congé de maternité",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="complement_salaire_conge_paternite",
            field=models.BooleanField(
                help_text="Existence d'un complément de salaire versé par l'employeur pour le congé de paternité",
                null=True,
                verbose_name="Complément de salaire pour le congé de paternité",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="participation_accueil_petite_enfance",
            field=models.BooleanField(
                null=True,
                verbose_name="Participation de l'entreprise et du comité social et économique aux modes d'accueil de la petite enfance",
            ),
        ),
    ]
