# Generated by Django 4.1.2 on 2022-12-06 14:18

from django.db import migrations
import reglementations.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reglementations",
            "0015_bdese_300_categories_professionnelles_detaillees_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese_300",
            name="effectif_qualification_detaillee_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType[
                    "PROFESSIONNELLE_DETAILLEE"
                ],
                help_text="Répartition de l'effectif total féminin au 31/12 selon une structure de qualification détaillée",
                null=True,
                verbose_name="Répartition des femmes",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="effectif_qualification_detaillee_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType[
                    "PROFESSIONNELLE_DETAILLEE"
                ],
                help_text="Répartition de l'effectif total masculin au 31/12 selon une structure de qualification détaillée",
                null=True,
                verbose_name="Répartition des hommes",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="action_adaptation_au_poste_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de femmes ayant suivi une formation d'adaptation au poste",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="action_adaptation_au_poste_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre d'hommes ayant suivi une formation d'adaptation au poste",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="action_developpement_competences_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de femmes ayant suivi une formation pour le développement des compétences",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="action_developpement_competences_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre d'hommes ayant suivi une formation pour le développement des compétences",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="action_maintien_emploi_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de femmes ayant suivi une formation pour le maintien dans l'emploi",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="action_maintien_emploi_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre d'hommes ayant suivi une formation pour le maintien dans l'emploi",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="age_moyen_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Age moyen des femmes par catégorie professionnelle",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="age_moyen_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Age moyen des hommes par catégorie professionnelle",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="anciennete_moyenne_dans_categorie_profesionnelle_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Ancienneté moyenne des femmes dans chaque catégorie professionnelle",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="anciennete_moyenne_dans_categorie_profesionnelle_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Ancienneté moyenne des hommes dans chaque catégorie professionnelle",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="anciennete_moyenne_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Ancienneté moyenne des femmes par catégorie professionnelle",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="anciennete_moyenne_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Ancienneté moyenne des hommes par catégorie professionnelle",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="conges_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Répartition des congés des femmes",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="conges_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Répartition des congés des hommes",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="departs_demission_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de femmes ayant démissionné",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="departs_demission_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre d'hommes ayant démissionné",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="departs_fin_CDD_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de femmes en fin de CDD",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="departs_fin_CDD_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre d'hommes en fin de CDD",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="departs_licenciement_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de femmes licenciées",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="departs_licenciement_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre d'hommes licenciés",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="departs_retraite_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de femmes parties en retraite",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="departs_retraite_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre d'hommes partis en retraite",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="effectif_cdd",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="Nombre de salariés titulaires d’un contrat de travail à durée déterminée au 31/12",
                null=True,
                verbose_name="Effectif CDD",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="effectif_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="effectif_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="effectif_mensuel_moyen",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="Somme des effectifs totaux mensuels divisée par 12 (on entend par effectif total tout salarié inscrit à l’effectif au dernier jour du mois considéré)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="effectif_nationalite_etrangere",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Effectif de nationalité étrangère",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="effectif_nationalite_francaise",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Effectif de nationalité française",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="effectif_permanent",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="Les salariés à temps plein, inscrits à l’effectif pendant toute l’année considérée et titulaires d’un contrat de travail à durée indéterminée.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="effectif_total",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="Tout salarié inscrit à l’effectif au 31/12 quelle que soit la nature de son contrat de travail",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="embauches_CDD_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Répartition des embauches femmes en CDD par catégorie professionnelle",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="embauches_CDD_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Répartition des embauches hommes en CDD par catégorie professionnelle",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="embauches_CDI_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Répartition des embauches femmes en CDI par catégorie professionnelle",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="embauches_CDI_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Répartition des embauches hommes en CDI par catégorie professionnelle",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="evolution_salariale_par_categorie",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="horaire_hebdomadaire_moyen",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="Il est possible de remplacer cet indicateur par la somme des heures travaillées durant l'année.",
                null=True,
                verbose_name="Horaire hebdomadaire moyen affiché des ouvriers et employés ou catégories assimilées",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="montant_moyen_participation",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="La participation est envisagée ici au sens du titre II du livre III de la partie III.",
                null=True,
                verbose_name="Montant moyen de la participation et/ ou de l'intéressement par salarié bénéficiaire",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_CDD_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de femmes en CDD",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_CDD_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre d'hommes en CDD",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_CDI_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de femmes en CDI",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_CDI_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre d'hommes en CDI",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_deces",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de décès",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_demissions",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de démissions",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_departs_volontaires_retraite_preretraite",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="Distinguer les différents systèmes légaux et conventionnels de toute nature",
                null=True,
                verbose_name="Nombre de départs volontaires en retraite et préretraite",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_embauches_cdd",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="dont nombre de contrats de travailleurs saisonniers",
                null=True,
                verbose_name="Nombre d'embauches par contrats de travail à durée déterminée",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_fin_cdd",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de fins de contrats de travail à durée déterminée",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_fin_periode_essai",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="à ne remplir que si ces départs sont comptabilisés dans le total des départs",
                null=True,
                verbose_name="Nombre de départs au cours de la période d’essai",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_heures_chomage_intemperies_indemnisees",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre total d'heures de chômage intempéries indemnisées",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_heures_chomage_intemperies_non_indemnisees",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre total d'heures de chômage intempéries non indemnisées",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_heures_chomage_partiel_indemnisees",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="Y compris les heures indemnisées au titre du chômage total en cas d’arrêt de plus de quatre semaines consécutives",
                null=True,
                verbose_name="Nombre total d'heures de chômage partiel indemnisées",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_heures_chomage_partiel_non_indemnisees",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre total d'heures de chômage partiel non indemnisées",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_jours_conges_paternite_pris",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="Nombre de jours de congés de paternité pris par le salarié par rapport au nombre de jours de congés théoriques",
                null=True,
                verbose_name="Jours de congés parternité",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_jours_feries_payes",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de jours fériés payés",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_licenciements_autres",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de licenciements pour d’autres causes",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_licenciements_economiques",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="dont départs en retraite et préretraite",
                null=True,
                verbose_name="Nombre de licenciements pour motif économique",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_moyen_heures_formation_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="femmes",
                null=True,
                verbose_name="Nombre moyen d'heures d'actions de formation par salariée et par an",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_moyen_heures_formation_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="hommes",
                null=True,
                verbose_name="Nombre moyen d'heures d'actions de formation par salarié et par an",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_moyen_jours_conges_annuels",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="Repos compensateur non compris. Cet indicateur peut être calculé sur la dernière période de référence.",
                null=True,
                verbose_name="Nombre moyen de jours de congés annuels (non compris le repos compensateur)",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_mutations",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de mutations d’un établissement à un autre",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_promotions_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de promotions femme",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_promotions_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de promotions homme",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_salaries_2_jours_repos_hebdomadaire_consecutifs",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de salariés ayant bénéficié tout au long de l'année considérée de deux jours de repos hebdomadaire consécutifs",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_salaries_chomage_intemperies",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de salariés mis en chômage intempéries",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_salaries_chomage_partiel",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de salariés mis en chômage partiel pendant l’année considérée",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_salaries_horaires_individualises",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="Au sens de l'article L. 3121-48.",
                null=True,
                verbose_name="Nombre de salariés bénéficiant d'un système d'horaires individualisés",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_salaries_repos_compensateur_code_travail",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="Au sens des dispositions du code du travail et du code rural et de la pêche maritime instituant un repos compensateur en matière d'heures supplémentaires.",
                null=True,
                verbose_name="Nombre de salariés ayant bénéficié d'un repos compensateur au titre du code du travail",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_salaries_repos_compensateur_regime_conventionne",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de salariés ayant bénéficié d'un repos compensateur au titre d'un régime conventionne",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_salaries_temps_partiel_20_30_heures",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="Au sens de l'article L. 3123-1.",
                null=True,
                verbose_name="Nombre de salariés employés à temps partiel entre 20 et 30 heures (33)",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_salaries_temps_partiel_autres",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de salariés employés sous d'autres formes de temps partiel",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_salaries_temps_partiel_choisi_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de salariées femme ayant accédé au temps partiel choisi",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_salaries_temps_partiel_choisi_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de salariés homme ayant accédé au temps partiel choisi",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_salaries_temps_partiel_choisi_vers_temps_plein_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de salariées femme à temps partiel choisi ayant repris un travail à temps plein",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_salaries_temps_partiel_choisi_vers_temps_plein_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de salariés homme à temps partiel choisi ayant repris un travail à temps plein",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_unites_absence",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="Ne sont pas comptés parmi les absences : les diverses sortes de congés, les conflits et le service national.",
                null=True,
                verbose_name="Nombre de journées d'absence",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_unites_absence_accidents",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de journées d'absence pour accidents du travail et de trajet ou maladies professionnelles",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_unites_absence_autres",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de journées d'absence imputables à d'autres causes",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_unites_absence_conges_autorises",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="(événements familiaux, congés spéciaux pour les femmes …)",
                null=True,
                verbose_name="Nombre de journées d'absence pour congés autorisés",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_unites_absence_maladie",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de journées d'absence pour maladie",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="nombre_unites_absence_maternite",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Nombre de journées d'absence pour maternité",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="part_primes_non_mensuelle",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Part des primes à périodicité non mensuelle dans la déclaration de salaire",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="rapport_masse_salariale_effectif_mensuel",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="Masse salariale annuelle totale, au sens de la déclaration annuelle de salaire",
                null=True,
                verbose_name="Rapport entre la masse salariale annuelle et l'effectif mensuel moyen",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="remuneration_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Rémunération moyenne/médiane mensuelle des femmes par catégorie professionnelle",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="remuneration_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Rémunération moyenne/médiane mensuelle des hommes par catégorie professionnelle",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="remuneration_mensuelle_moyenne",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Rémunération mensuelle moyenne",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="remuneration_moyenne_decembre",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                help_text="base 35 heures",
                null=True,
                verbose_name="Rémunération moyenne du mois de décembre (effectif permanent) hors primes à périodicité non mensuelle",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="salaire_base_minimum_par_categorie",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Salaire de base minimum par catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="salaire_median_par_categorie",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Salaire médian par catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="salaire_moyen_par_categorie",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Salaire moyen par catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="total_departs",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Total des départs",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_50_300",
            name="effectif_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bdese_50_300",
            name="effectif_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bdese_50_300",
            name="evolution_salariale_par_categorie",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bdese_50_300",
            name="nombre_salaries_temps_partiel_par_qualification",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Qualification des salariés travaillant à temps partiel",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_50_300",
            name="salaire_base_minimum_par_categorie",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Salaire de base minimum par catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_50_300",
            name="salaire_median_par_categorie",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Salaire médian par catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_50_300",
            name="salaire_moyen_par_categorie",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType["PROFESSIONNELLE"],
                null=True,
                verbose_name="Salaire moyen par catégorie",
            ),
        ),
    ]
