# Generated by Django 4.1.2 on 2022-12-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reglementations",
            "0016_bdese_300_effectif_qualification_detaillee_femme_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bdese_300",
            name="categories_professionnelles",
            field=models.JSONField(
                blank=True,
                help_text="Une structure de qualification détaillée en trois postes minimum",
                null=True,
                verbose_name="Catégories professionnelles",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="categories_professionnelles_detaillees",
            field=models.JSONField(
                blank=True,
                help_text="Une structure de qualification détaillée en cinq postes minimum",
                null=True,
                verbose_name="Catégories professionnelles détaillées",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_50_300",
            name="categories_professionnelles",
            field=models.JSONField(
                blank=True,
                help_text="Une structure de qualification détaillée en trois postes minimum",
                null=True,
                verbose_name="Catégories professionnelles",
            ),
        ),
    ]
