# Generated by Django 4.1.5 on 2023-03-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0017_transform_official_bdese_into_personal_bdese"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficialBDESE_300",
            fields=[],
            options={
                "verbose_name": "BDESE officielle plus de 300 salariés",
                "verbose_name_plural": "BDESE officielles plus de 300 salariés",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reglementations.bdese_300",),
        ),
        migrations.CreateModel(
            name="OfficialBDESE_50_300",
            fields=[],
            options={
                "verbose_name": "BDESE officielle 50 à 300 salariés",
                "verbose_name_plural": "BDESE officielles 50 à 300 salariés",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reglementations.bdese_50_300",),
        ),
        migrations.CreateModel(
            name="PersonalBDESE_300",
            fields=[],
            options={
                "verbose_name": "BDESE personnelle plus de 300 salariés",
                "verbose_name_plural": "BDESE personnelles plus de 300 salariés",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reglementations.bdese_300",),
        ),
        migrations.CreateModel(
            name="PersonalBDESE_50_300",
            fields=[],
            options={
                "verbose_name": "BDESE personnelle 50 à 300 salariés",
                "verbose_name_plural": "BDESE personnelles 50 à 300 salariés",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reglementations.bdese_50_300",),
        ),
    ]
