# Generated by Django 4.1.2 on 2022-12-07 14:37

from django.db import migrations
import reglementations.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reglementations",
            "0018_alter_bdese_300_nombre_heures_stage_non_remunerees_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese_300",
            name="nombre_stagiaires_formation_continue",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType[
                    "PROFESSIONNELLE_DETAILLEE"
                ],
                null=True,
                verbose_name="Nombre de stagiaires",
            ),
        ),
    ]
