# Generated by Django 4.1.7 on 2023-03-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0018_officialbdese_300_officialbdese_50_300_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bdese_300",
            old_name="bilan_gaz_effet_de_serre",
            new_name="bilan_gaz_effet_de_serre_non_soumis_DPEF",
        ),
        migrations.RenameField(
            model_name="bdese_300",
            old_name="prevention_et_gestion_dechets",
            new_name="quantite_de_dechets_dangereux_soumis_DPEF",
        ),
        migrations.RemoveField(
            model_name="bdese_300",
            name="quantite_de_dechets_dangereux",
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="bilan_gaz_effet_de_serre_soumis_DPEF",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Bilan des émissions de gaz à effet de serre prévu par l'article L. 229-25 du code de l'environnement ou bilan simplifié prévu par l'article 244 de la loi n° 2020-1721 du 29 décembre 2020 de finances pour 2021 pour les entreprises tenues d'établir ces différents bilans",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="quantite_de_dechets_dangereux_non_soumis_DPEF",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Évaluation de la quantité de déchets dangereux définis à l'article R. 541-8 du code de l'environnement et faisant l'objet d'une émission du bordereau mentionné à l'article R. 541-45 du même code",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="postes_emissions_directes_gaz_effet_de_serre",
            field=models.TextField(
                blank=True,
                help_text="produites par les sources fixes et mobiles nécessaires aux activités de l'entreprise (communément appelées \"émissions du scope 1\") et, lorsque l'entreprise dispose de cette information, évaluation du volume de ces émissions de gaz à effet de serre ",
                null=True,
                verbose_name="Identification des postes d'émissions directes de gaz à effet de serre",
            ),
        ),
    ]
