# Generated by Django 4.1.2 on 2022-12-07 15:06

from django.db import migrations
import reglementations.models


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0019_bdese_300_nombre_stagiaires_formation_continue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bdese_300",
            name="nombre_heures_stage_non_remunerees",
        ),
        migrations.RemoveField(
            model_name="bdese_300",
            name="nombre_heures_stage_remunerees",
        ),
        migrations.RemoveField(
            model_name="bdese_300",
            name="nombre_stagiaires_formation_continue",
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="nombre_heures_stage_non_remunerees_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType[
                    "PROFESSIONNELLE_DETAILLEE"
                ],
                null=True,
                verbose_name="Nombre d'heures de stage non rémunérées pour les femmes",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="nombre_heures_stage_non_remunerees_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType[
                    "PROFESSIONNELLE_DETAILLEE"
                ],
                null=True,
                verbose_name="Nombre d'heures de stage non rémunérées pour les hommes",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="nombre_heures_stage_remunerees_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType[
                    "PROFESSIONNELLE_DETAILLEE"
                ],
                null=True,
                verbose_name="Nombre d'heures de stage rémunérées pour les femmes",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="nombre_heures_stage_remunerees_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType[
                    "PROFESSIONNELLE_DETAILLEE"
                ],
                null=True,
                verbose_name="Nombre d'heures de stage rémunérées pour les hommes",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="nombre_stagiaires_formation_continue_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType[
                    "PROFESSIONNELLE_DETAILLEE"
                ],
                null=True,
                verbose_name="Nombre de stagiaires femmes",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="nombre_stagiaires_formation_continue_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType[
                    "PROFESSIONNELLE_DETAILLEE"
                ],
                null=True,
                verbose_name="Nombre de stagiaires hommes",
            ),
        ),
    ]
