# Generated by Django 4.1.7 on 2023-04-04 15:30
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entreprises", "0014_alter_entreprise_effectif_and_more"),
        (
            "reglementations",
            "0019_rename_bilan_gaz_effet_de_serre_bdese_300_bilan_gaz_effet_de_serre_non_soumis_dpef_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BDESEAvecAccord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("annee", models.IntegerField()),
                (
                    "categories_professionnelles",
                    models.JSONField(
                        blank=True,
                        help_text="Une structure de qualification détaillée en trois postes minimum",
                        null=True,
                        verbose_name="Catégories professionnelles",
                    ),
                ),
                ("external_fields", models.JSONField(default=list)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entreprises.entreprise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "BDESE avec accord d'entreprise",
                "verbose_name_plural": "BDESE avec accord d'entreprise",
            },
        ),
    ]
