# Generated by Django 4.1.7 on 2023-04-04 15:01
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0020_bdeseavecaccord"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdeseavecaccord",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
