# Generated by Django 4.1.2 on 2022-12-07 15:47

from django.db import migrations
import reglementations.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reglementations",
            "0020_remove_bdese_300_nombre_heures_stage_non_remunerees_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bdese_300",
            name="part_primes_non_mensuelle",
        ),
        migrations.RemoveField(
            model_name="bdese_300",
            name="rapport_masse_salariale_effectif_mensuel",
        ),
        migrations.RemoveField(
            model_name="bdese_300",
            name="remuneration_mensuelle_moyenne",
        ),
        migrations.RemoveField(
            model_name="bdese_300",
            name="remuneration_moyenne_decembre",
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="part_primes_non_mensuelle_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType[
                    "PROFESSIONNELLE_DETAILLEE"
                ],
                null=True,
                verbose_name="Part des primes à périodicité non mensuelle dans la déclaration de salaire (femmes)",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="part_primes_non_mensuelle_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType[
                    "PROFESSIONNELLE_DETAILLEE"
                ],
                null=True,
                verbose_name="Part des primes à périodicité non mensuelle dans la déclaration de salaire (hommes)",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="rapport_masse_salariale_effectif_mensuel_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType[
                    "PROFESSIONNELLE_DETAILLEE"
                ],
                help_text="Masse salariale annuelle totale, au sens de la déclaration annuelle de salaire",
                null=True,
                verbose_name="Rapport entre la masse salariale annuelle et l'effectif mensuel moyen (femmes)",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="rapport_masse_salariale_effectif_mensuel_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType[
                    "PROFESSIONNELLE_DETAILLEE"
                ],
                help_text="Masse salariale annuelle totale, au sens de la déclaration annuelle de salaire",
                null=True,
                verbose_name="Rapport entre la masse salariale annuelle et l'effectif mensuel moyen (hommes)",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="remuneration_mensuelle_moyenne_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType[
                    "PROFESSIONNELLE_DETAILLEE"
                ],
                null=True,
                verbose_name="Rémunération mensuelle moyenne (femmes)",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="remuneration_mensuelle_moyenne_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType[
                    "PROFESSIONNELLE_DETAILLEE"
                ],
                null=True,
                verbose_name="Rémunération mensuelle moyenne (hommes)",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="remuneration_moyenne_decembre_femme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType[
                    "PROFESSIONNELLE_DETAILLEE"
                ],
                help_text="base 35 heures",
                null=True,
                verbose_name="Rémunération moyenne du mois de décembre (effectif permanent) hors primes à périodicité non mensuelle (femmes)",
            ),
        ),
        migrations.AddField(
            model_name="bdese_300",
            name="remuneration_moyenne_decembre_homme",
            field=reglementations.models.CategoryField(
                blank=True,
                category_type=reglementations.models.CategoryType[
                    "PROFESSIONNELLE_DETAILLEE"
                ],
                help_text="base 35 heures",
                null=True,
                verbose_name="Rémunération moyenne du mois de décembre (effectif permanent) hors primes à périodicité non mensuelle (hommes)",
            ),
        ),
    ]
