# Generated by Django 4.1.7 on 2023-04-04 15:07
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0021_bdeseavecaccord_is_complete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bdeseavecaccord",
            name="completion_steps",
        ),
    ]
