# Generated by Django 4.1.4 on 2022-12-12 17:20

from django.db import migrations
import django.db.models.fields
import reglementations.models


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0021_remove_bdese_300_part_primes_non_mensuelle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bdese_300",
            name="completion_steps",
            field=reglementations.models.CategoryField(
                base_field=django.db.models.fields.BooleanField,
                categories=[
                    "Catégories professionnelles",
                    "Investissement social",
                    "Investissement matériel et immatériel",
                    "Egalité professionnelle homme/femme",
                    "Fonds propres, endettement et impôts",
                    "Rémunérations",
                    "Représentation du personnel et Activités sociales et culturelles",
                    "Rémunération des financeurs",
                    "Flux financiers",
                    "Partenariats",
                    "Transferts commerciaux et financiers",
                    "Environnement",
                ],
                default=reglementations.models.bdese_300_completion_steps_default,
            ),
        ),
    ]
