# Generated by Django 4.2.16 on 2024-09-27 15:33
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entreprises", "0048_entreprise_code_naf"),
        ("reglementations", "0022_bdese_300_uniques_personalbdese_300_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RapportCSRD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annee",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(2024)],
                        verbose_name="année du rapport CSRD",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="description du rapport CSRD"
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports_csrd",
                        to="entreprises.entreprise",
                    ),
                ),
                (
                    "proprietaire",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propriétaire rapport CSRD personnel",
                    ),
                ),
            ],
            options={
                "verbose_name": "rapport CSRD",
            },
        ),
        migrations.CreateModel(
            name="Enjeu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "esrs",
                    models.TextField(
                        choices=[
                            ("ESRS_1", "Esrs 1"),
                            ("ESRS_2", "Esrs 2"),
                            ("ESRS_E1", "Esrs E1"),
                            ("ESRS_E2", "Esrs E2"),
                            ("ESRS_E3", "Esrs E3"),
                            ("ESRS_E4", "Esrs E4"),
                            ("ESRS_E5", "Esrs E5"),
                            ("ESRS_S1", "Esrs S1"),
                            ("ESRS_S2", "Esrs S2"),
                            ("ESRS_S3", "Esrs S3"),
                            ("ESRS_S4", "Esrs S4"),
                            ("ESRS_G1", "Esrs G1"),
                        ],
                        verbose_name="ESRS rattaché",
                    ),
                ),
                ("nom", models.TextField(verbose_name="nom de l'enjeu")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description de l'enjeu"),
                ),
                (
                    "modifiable",
                    models.BooleanField(
                        default=True, verbose_name="enjeu modifiable par l'utilisateur"
                    ),
                ),
                (
                    "selection",
                    models.BooleanField(default=False, verbose_name="selectionné"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enfants",
                        to="reglementations.enjeu",
                        verbose_name="enjeu parent",
                    ),
                ),
                (
                    "rapport_csrd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enjeux",
                        to="reglementations.rapportcsrd",
                    ),
                ),
            ],
            options={
                "verbose_name": "enjeu ESRS",
                "ordering": ["rapport_csrd", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="rapportcsrd",
            index=models.Index(fields=["annee"], name="reglementat_annee_e04785_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="rapportcsrd",
            unique_together={("annee", "entreprise", "proprietaire")},
        ),
        migrations.AddIndex(
            model_name="enjeu",
            index=models.Index(fields=["esrs"], name="reglementat_esrs_859daf_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="enjeu",
            unique_together={("rapport_csrd", "nom", "esrs")},
        ),
    ]
