# Generated by Django 4.2.16 on 2024-11-08 13:25
from django.db import migrations
from django.db import models


def maj_etapes(apps, schema_editor):
    RapportCSRD = apps.get_model("reglementations", "RapportCSRD")
    for rapport in RapportCSRD.objects.all():
        if rapport.etape_validee == "1":
            rapport.etape_validee = "introduction"
        elif rapport.etape_validee == "2":
            rapport.etape_validee = "selection-enjeux"
        rapport.save()


class Migration(migrations.Migration):
    dependencies = [
        ("reglementations", "0024_rapportcsrd_etape_validee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rapportcsrd",
            name="etape_validee",
            field=models.TextField(
                null=True, verbose_name="étape validée du rapport CSRD"
            ),
        ),
        migrations.RunPython(
            maj_etapes,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
