# Generated by Django 4.2.16 on 2024-11-20 09:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0025_alter_rapportcsrd_etape_validee"),
    ]

    operations = [
        migrations.AddField(
            model_name="enjeu",
            name="materiel",
            field=models.BooleanField(
                null=True, verbose_name="sélectionné comme enjeu matériel"
            ),
        ),
    ]
