# Generated by Django 5.1.4 on 2025-01-08 09:33
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0026_enjeu_materiel"),
    ]

    operations = [
        migrations.AddField(
            model_name="rapportcsrd",
            name="lien_rapport",
            field=models.URLField(
                blank=True, verbose_name="lien du rapport CSRD publié"
            ),
        ),
    ]
