# Generated by Django 5.1.6 on 2025-02-27 15:59
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0028_rapportcsrd_bloque"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAnalyseIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resultat_csv", models.TextField()),
                ("erreur", models.CharField(max_length=144)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
