# Generated by Django 5.1.5 on 2025-03-04 17:44
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reglementations", "0029_documentanalyseia"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documentanalyseia",
            old_name="erreur",
            new_name="etat",
        ),
    ]
