# Generated by Django 5.1.6 on 2025-02-28 15:13
import django.db.models.deletion
from django.db import migrations
from django.db import models

import reglementations.models.csrd


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0029_rename_csrd_step_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAnalyseIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fichier",
                    models.FileField(
                        storage=reglementations.models.csrd.select_storage,
                        upload_to=reglementations.models.csrd.entreprise_directory_path,
                    ),
                ),
                (
                    "rapport_csrd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="reglementations.rapportcsrd",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
