# Generated by Django 5.1.7 on 2025-03-21 09:26
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0029_rename_csrd_step_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAnalyseIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fichier",
                    models.FileField(
                        storage=None,  # les fonctions ont été déplacées dans analyseia.models et DocumentAnalyseIA est supprimé dans la migration 0036
                        upload_to=None,  # les fonctions ont été déplacées dans analyseia.models et DocumentAnalyseIA est supprimé dans la migration 0036
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="nom d'origine")),
                (
                    "resultat_json",
                    models.JSONField(
                        null=True,
                        verbose_name="résultat de l'analyse IA au format JSON",
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        max_length=144,
                        null=True,
                        verbose_name="dernier état connu du traitement d'analyse IA envoyé par le serveur IA",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        max_length=144,
                        null=True,
                        verbose_name="éventuel message précisant l'état envoyé par le serveur IA",
                    ),
                ),
                (
                    "rapport_csrd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="reglementations.rapportcsrd",
                    ),
                ),
            ],
            options={
                "verbose_name": "document analyse IA",
                "verbose_name_plural": "documents analyse IA",
            },
        ),
    ]
