# Generated by Django 5.1.9 on 2025-05-21 09:29
from django.db import migrations

"""
Permet la fusion des rapports CSRD (personnels vers principaux) :
 - traitement par année (2024 et 2025),
 - pour les entreprises sans rapport principal : avec un lien de publication et/ou par date de modification,
 - les anciens rapports personnels ne sont pas supprimés pour le moment (support éventuel).
"""


class Migration(migrations.Migration):
    dependencies = [
        ("reglementations", "0030_documentanalyseia"),
    ]

    def fusion_personnels_en_principaux(apps, schema_editor):
        RapportCSRD = apps.get_model("reglementations", "RapportCSRD")

        # pour l'instant les rapports CSRD personnels restent en base
        # mais ne seront plus directement accessibles.
        # Une deuxième migration pourra permettre leur suppression
        for annee in ("2024", "2025"):
            # pour chaque année, on récupère les entreprises n'ayant pas de rapport officiel
            entreprises = (
                RapportCSRD.objects.filter(annee=annee)
                .exclude(proprietaire=None)
                .select_related("entreprise")
                .values_list("entreprise", flat=True)
                .distinct()
            )
            for entreprise in entreprises:
                rapports_personnels = RapportCSRD.objects.filter(
                    entreprise=entreprise, annee=annee
                ).order_by("-lien_rapport", "-updated_at")
                # on prends le premier de chaque bloc :
                # le plus récent et / ou ayant un lien de publication
                # et il devient le rapport principal pour l'année donnée
                if premier_rapport := rapports_personnels.first():
                    premier_rapport.proprietaire = None
                    premier_rapport.save()
                    continue

    operations = [migrations.RunPython(fusion_personnels_en_principaux)]
