# Generated by Django 5.1.6 on 2025-03-12 13:51
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0030_documentanalyseia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentanalyseia",
            name="resultat_csv",
        ),
        migrations.AddField(
            model_name="documentanalyseia",
            name="resultat_json",
            field=models.JSONField(null=True),
        ),
    ]
