# Generated by Django 5.1.6 on 2025-03-13 10:36
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("reglementations", "0031_remove_documentanalyseia_resultat_csv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentanalyseia",
            name="message",
            field=models.CharField(max_length=144, null=True),
        ),
    ]
