# Generated by Django 5.1.7 on 2025-06-11 14:29
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0032_fusion_bdese"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OfficialBDESE_300",
        ),
        migrations.DeleteModel(
            name="OfficialBDESE_50_300",
        ),
        migrations.DeleteModel(
            name="OfficialBDESEAvecAccord",
        ),
        migrations.DeleteModel(
            name="PersonalBDESE_300",
        ),
        migrations.DeleteModel(
            name="PersonalBDESE_50_300",
        ),
        migrations.DeleteModel(
            name="PersonalBDESEAvecAccord",
        ),
    ]
