# Generated by Django 5.1.6 on 2025-03-18 16:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0032_documentanalyseia_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentanalyseia",
            options={
                "verbose_name": "document analyse IA",
                "verbose_name_plural": "documents analyse IA",
            },
        ),
        migrations.AddField(
            model_name="documentanalyseia",
            name="nom",
            field=models.CharField(
                default="", max_length=255, verbose_name="nom d'origine"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="documentanalyseia",
            name="etat",
            field=models.CharField(
                max_length=144,
                null=True,
                verbose_name="dernier état connu du traitement d'analyse IA envoyé par le serveur IA",
            ),
        ),
        migrations.AlterField(
            model_name="documentanalyseia",
            name="message",
            field=models.CharField(
                max_length=144,
                null=True,
                verbose_name="éventuel message précisant l'état envoyé par le serveur IA",
            ),
        ),
        migrations.AlterField(
            model_name="documentanalyseia",
            name="resultat_json",
            field=models.JSONField(
                null=True, verbose_name="résultat de l'analyse IA au format JSON"
            ),
        ),
    ]
