# Generated by Django 5.1.7 on 2025-07-11 12:17
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reglementations",
            "0033_delete_officialbdese_300_delete_officialbdese_50_300_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bdese_300",
            name="external_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="bdese_300",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="uniquement pour les documents personnels (déprécié)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="propriétaire de la BDESE personnelle",
            ),
        ),
        migrations.AlterField(
            model_name="bdese_50_300",
            name="external_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="bdese_50_300",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="uniquement pour les documents personnels (déprécié)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="propriétaire de la BDESE personnelle",
            ),
        ),
        migrations.AlterField(
            model_name="bdeseavecaccord",
            name="external_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="bdeseavecaccord",
            name="is_complete",
            field=models.BooleanField(
                default=False, verbose_name="est marquée comme terminée"
            ),
        ),
        migrations.AlterField(
            model_name="bdeseavecaccord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="uniquement pour les documents personnels (déprécié)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="propriétaire de la BDESE personnelle",
            ),
        ),
        migrations.AlterField(
            model_name="documentanalyseia",
            name="etat",
            field=models.CharField(
                blank=True,
                max_length=144,
                null=True,
                verbose_name="dernier état connu du traitement d'analyse IA envoyé par le serveur IA",
            ),
        ),
        migrations.AlterField(
            model_name="documentanalyseia",
            name="message",
            field=models.CharField(
                blank=True,
                max_length=144,
                null=True,
                verbose_name="éventuel message précisant l'état envoyé par le serveur IA",
            ),
        ),
        migrations.AlterField(
            model_name="documentanalyseia",
            name="resultat_json",
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name="résultat de l'analyse IA au format JSON",
            ),
        ),
        migrations.AlterField(
            model_name="rapportcsrd",
            name="etape_validee",
            field=models.TextField(
                blank=True, null=True, verbose_name="étape validée du rapport CSRD"
            ),
        ),
        migrations.AlterField(
            model_name="rapportcsrd",
            name="proprietaire",
            field=models.ForeignKey(
                blank=True,
                help_text="uniquement pour les documents personnels (déprécié)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="propriétaire du rapport CSRD personnel",
            ),
        ),
    ]
