# Generated by Django 5.1.13 on 2025-10-14 14:35
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("analyseia", "0001_initial"),
        (
            "reglementations",
            "0034_alter_bdese_300_external_fields_alter_bdese_300_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rapportcsrd",
            name="analyses_ia",
            field=models.ManyToManyField(
                related_name="rapports_csrd", to="analyseia.analyseia"
            ),
        ),
    ]
