# Generated by Django 5.1.12 on 2025-11-04 15:24
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reglementations", "0035_rapportcsrd_analyses_ia"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DocumentAnalyseIA",
        ),
    ]
