# Generated by Django 5.1.7 on 2025-05-09 09:54
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entreprises", "0048_entreprise_code_naf"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(max_length=255, verbose_name="Adresse e-mail"),
                ),
                (
                    "code",
                    models.CharField(max_length=10, verbose_name="Code de validation"),
                ),
                ("role", models.CharField(max_length=20, verbose_name="Role (droits)")),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entreprises.entreprise",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
