# Generated by Django 5.1.7 on 2025-06-03 12:07
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invitations", "0002_invitation_inviteur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="code",
        ),
    ]
