# Generated by Django 5.1.7 on 2025-06-20 16:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("invitations", "0003_remove_invitation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="date_acceptation",
            field=models.DateTimeField(null=True),
        ),
    ]
