# Generated by Django 5.1.14 on 2026-01-13 17:43
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0006_alter_invitation_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="est_invitation_proprietaire_tiers",
            field=models.BooleanField(
                default=False,
                help_text="Invitation créée par un conseiller RSE pour un futur propriétaire",
                verbose_name="Invitation propriétaire pour un tiers",
            ),
        ),
    ]
