# Generated by Django 5.1.15 on 2026-02-17 17:52
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0007_invitation_est_invitation_proprietaire_tiers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="est_invitation_proprietaire_tiers",
        ),
    ]
