# Generated by Django 5.2.16 on 2026-07-22 14:41
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0008_remove_invitation_est_invitation_proprietaire_tiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("administrateur", "Administrateur"),
                    ("contributeur", "Contributeur"),
                    ("lecteur", "Lecteur"),
                ],
                max_length=20,
                verbose_name="Role (droits)",
            ),
        ),
    ]
