# Generated by Django 5.1.13 on 2025-10-14 13:27
from django.db import migrations
from django.db import models

import analyseia.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyseIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fichier",
                    models.FileField(
                        storage=analyseia.models.select_storage,
                        upload_to=analyseia.models.upload_path,
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="nom d'origine")),
                (
                    "resultat_json",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="résultat de l'analyse IA au format JSON",
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        blank=True,
                        max_length=144,
                        null=True,
                        verbose_name="dernier état connu du traitement d'analyse IA envoyé par le serveur IA",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        max_length=144,
                        null=True,
                        verbose_name="éventuel message précisant l'état envoyé par le serveur IA",
                    ),
                ),
            ],
            options={
                "verbose_name": "document analyse IA",
                "verbose_name_plural": "documents analyse IA",
            },
        ),
    ]
