# Generated by Django 5.1.13 on 2025-10-14 14:59
from django.db import migrations
from django.forms.models import model_to_dict


def copier_documents_analyseia(apps, _):
    DocumentAnalyseIA = apps.get_model("reglementations", "DocumentAnalyseIA")
    AnalyseIA = apps.get_model("analyseia", "AnalyseIA")

    for analyse_ia in DocumentAnalyseIA.objects.select_related("rapport_csrd").all():
        rapport_csrd = analyse_ia.rapport_csrd
        doc_fields = model_to_dict(analyse_ia)

        doc_fields.pop("rapport_csrd")
        doc_fields.pop("id")

        analyse_ia = AnalyseIA.objects.create(**doc_fields)
        analyse_ia.rapports_csrd.add(rapport_csrd)


class Migration(migrations.Migration):
    dependencies = [
        ("reglementations", "0035_rapportcsrd_analyses_ia"),
        ("analyseia", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(copier_documents_analyseia, migrations.RunPython.noop),
    ]
