# Generated by Django 5.2.16 on 2026-08-27 08:45
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("analyseia", "0002_auto_20251014_1459"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyseia",
            name="etat_v2",
            field=models.CharField(
                blank=True,
                max_length=144,
                null=True,
                verbose_name="dernier état connu du traitement d'analyse IA v2 envoyé par le serveur IA",
            ),
        ),
        migrations.AddField(
            model_name="analyseia",
            name="message_v2",
            field=models.CharField(
                blank=True,
                max_length=144,
                null=True,
                verbose_name="éventuel message précisant l'état envoyé par le serveur IA v2",
            ),
        ),
        migrations.AddField(
            model_name="analyseia",
            name="resultat_json_v2",
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name="résultat de l'analyse IA v2 au format JSON",
            ),
        ),
        migrations.AlterField(
            model_name="analyseia",
            name="etat",
            field=models.CharField(
                blank=True,
                max_length=144,
                null=True,
                verbose_name="dernier état connu du traitement d'analyse IA v1 envoyé par le serveur IA",
            ),
        ),
        migrations.AlterField(
            model_name="analyseia",
            name="message",
            field=models.CharField(
                blank=True,
                max_length=144,
                null=True,
                verbose_name="éventuel message précisant l'état envoyé par le serveur IA v1",
            ),
        ),
        migrations.AlterField(
            model_name="analyseia",
            name="resultat_json",
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name="résultat de l'analyse IA v1 au format JSON",
            ),
        ),
    ]
