# Generated by Django 5.2.16 on 2026-08-27 14:26
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyseia", "0003_analyseia_etat_v2_analyseia_message_v2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analyseia",
            old_name="etat",
            new_name="etat_v1",
        ),
        migrations.RenameField(
            model_name="analyseia",
            old_name="message",
            new_name="message_v1",
        ),
        migrations.RenameField(
            model_name="analyseia",
            old_name="resultat_json",
            new_name="resultat_json_v1",
        ),
    ]
