# Generated by Django 5.1.11 on 2025-09-25 10:02
import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "entreprises",
            "0051_remove_caracteristiquesannuelles_effectif_groupe_permanent",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RapportVSME",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annee",
                    models.PositiveIntegerField(verbose_name="année du rapport VSME"),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports_vsme",
                        to="entreprises.entreprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "rapport VSME",
                "verbose_name_plural": "rapports VSME",
            },
        ),
        migrations.CreateModel(
            name="Indicateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schema_id",
                    models.CharField(
                        max_length=42,
                        verbose_name="id du schéma descriptif de l'indicateur",
                    ),
                ),
                (
                    "schema_version",
                    models.PositiveIntegerField(
                        default=1,
                        verbose_name="numéro de version du schéma descriptif de l'indicateur",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        verbose_name="donnée brute saisie par l'utilisateur",
                    ),
                ),
                (
                    "rapport_vsme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicateurs",
                        to="vsme.rapportvsme",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="rapportvsme",
            index=models.Index(fields=["annee"], name="vsme_rappor_annee_a7515d_idx"),
        ),
        migrations.AddConstraint(
            model_name="rapportvsme",
            constraint=models.UniqueConstraint(
                fields=("entreprise", "annee"), name="unique_rapport_annuel"
            ),
        ),
        migrations.AddIndex(
            model_name="indicateur",
            index=models.Index(
                fields=["schema_id"], name="vsme_indica_schema__0f7ed8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="indicateur",
            constraint=models.UniqueConstraint(
                fields=("rapport_vsme", "schema_id"),
                name="unique_indicateur_par_rapport",
            ),
        ),
    ]
