# Generated by Django 5.1.14 on 2025-11-25 08:59
from django.db import migrations
from django.db import models

import vsme.models


class Migration(migrations.Migration):

    dependencies = [
        ("vsme", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rapportvsme",
            name="annee",
            field=models.PositiveIntegerField(
                validators=[vsme.models.validate_annee_rapport],
                verbose_name="année du rapport VSME",
            ),
        ),
    ]
