# Generated by Django 5.1.11 on 2025-08-12 14:19
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("vsme", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VSME",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "indicateur_nombre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vsme.indicateurnombre",
                    ),
                ),
                (
                    "indicateur_tableau",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vsme.indicateurtableau",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
