# Generated by Django 5.1.12 on 2026-01-07 09:35
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vsme", "0002_alter_rapportvsme_annee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="indicateur",
            old_name="data",
            new_name="_data",
        ),
    ]
