# Generated by Django 4.1.4 on 2023-01-04 15:15
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="acceptation_cgu",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="reception_actualites",
            field=models.BooleanField(default=False),
        ),
    ]
