# Generated by Django 4.1.4 on 2023-01-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_acceptation_cgu_user_reception_actualites"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nom",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="prenom",
            field=models.CharField(default="", max_length=50),
        ),
    ]
