# Generated by Django 4.2 on 2023-04-20 14:52
from django.db import migrations
from django.db import models


def initialize_is_email_confirmed_field(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        user.is_email_confirmed = True
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            initialize_is_email_confirmed_field,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
