# Generated by Django 4.2 on 2023-04-26 08:39
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_is_email_confirmed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Utilisateur"},
        ),
        migrations.AlterField(
            model_name="user",
            name="acceptation_cgu",
            field=models.BooleanField(default=False, verbose_name="CGU acceptées"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="Adresse e-mail"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_email_confirmed",
            field=models.BooleanField(
                default=False, verbose_name="Adresse e-mail confirmée"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Accès admin"),
        ),
        migrations.AlterField(
            model_name="user",
            name="prenom",
            field=models.CharField(default="", max_length=50, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="user",
            name="reception_actualites",
            field=models.BooleanField(
                default=False, verbose_name="Réception des actualités acceptée"
            ),
        ),
    ]
