# Generated by Django 4.2.1 on 2023-07-19 14:01
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_options_alter_user_acceptation_cgu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False, verbose_name="Accès à /admin (back-office)"
            ),
        ),
    ]
