# Generated by Django 5.1.12 on 2025-09-09 16:43
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sub",
            field=models.UUIDField(
                null=True, verbose_name="identifiant interne ProConnect"
            ),
        ),
    ]
