# Generated by Django 5.1.14 on 2025-12-12 17:10
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_sub_pc"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_conseiller_rse",
            field=models.BooleanField(
                blank=True,
                help_text="Indique si l'utilisateur est un conseiller RSE externe",
                null=True,
                verbose_name="est conseiller RSE",
            ),
        ),
    ]
