# Generated by Django 5.1.15 on 2026-04-08 15:49
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_fonction_rse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fonction_rse",
            field=models.CharField(
                blank=True,
                choices=[
                    ("consultant", "Consultant"),
                    ("auditeur", "Auditeur / expert comptable"),
                    ("finance", "Finance durable & investissement"),
                    ("fédération", "Fédération / structure d’accompagnement"),
                    ("public", "Conseiller CCI / acteur public RSE"),
                    ("autre", "Autre"),
                ],
                max_length=50,
                null=True,
                verbose_name="Fonction dans l'accompagnement",
            ),
        ),
    ]
