# NACE Rev. 2.1
# https://showvoc.op.europa.eu/#/datasets/ESTAT_Statistical_Classification_of_Economic_Activities_in_the_European_Community_Rev._2.1._%28NACE_2.1%29/downloads

CODES_NACE = {
    "01.11": "Culture de céréales, à l’exception du riz, de légumineuses et de graines oléagineuses",
    "01.12": "Culture du riz",
    "01.13": "Culture de légumes, de melons, de racines et de tubercules",
    "01.14": "Culture de la canne à sucre",
    "01.15": "Culture du tabac",
    "01.16": "Culture de plantes à fibres",
    "01.19": "Autres cultures non permanentes",
    "01.21": "Culture de la vigne",
    "01.22": "Culture de fruits tropicaux et subtropicaux",
    "01.23": "Culture d’agrumes",
    "01.24": "Culture de fruits à pépins et à noyau",
    "01.25": "Culture d’autres fruits d’arbres ou d’arbustes et de fruits à coque",
    "01.26": "Culture de fruits oléagineux",
    "01.27": "Culture de plantes à boissons",
    "01.28": "Culture de plantes à épices, aromatiques, médicinales et pharmaceutiques",
    "01.29": "Autres cultures permanentes",
    "01.30": "Reproduction de plantes",
    "01.41": "Élevage de vaches laitières",
    "01.42": "Élevage d’autres bovins et de buffles",
    "01.43": "Élevage de chevaux et d’autres équidés",
    "01.44": "Élevage de chameaux et d’autres camélidés",
    "01.45": "Élevage d’ovins et de caprins",
    "01.46": "Élevage de porcins",
    "01.47": "Élevage de volailles",
    "01.48": "Élevage d’autres animaux",
    "01.50": "Culture et élevage associés",
    "01.61": "Activités de soutien aux cultures",
    "01.62": "Activités de soutien à la production animale",
    "01.63": "Traitement primaire des récoltes et traitement des semences",
    "01.70": "Chasse, piégeage et activités de service connexes",
    "02.10": "Sylviculture et autres activités forestières",
    "02.20": "Exploitation forestière",
    "02.30": "Récolte de produits forestiers non ligneux poussant à l’état sauvage",
    "02.40": "Activités de soutien à l’exploitation forestière",
    "03.11": "Pêche en mer",
    "03.12": "Pêche en eau douce",
    "03.21": "Aquaculture en mer",
    "03.22": "Aquaculture en eau douce",
    "03.30": "Activités de soutien à la pêche et l’aquaculture",
    "05.10": "Extraction de houille",
    "05.20": "Extraction de lignite",
    "06.10": "Extraction de pétrole brut",
    "06.20": "Extraction de gaz naturel",
    "07.10": "Extraction de minerais de fer",
    "07.21": "Extraction de minerais d’uranium et de thorium",
    "07.29": "Extraction d’autres minerais de métaux non ferreux",
    "08.11": "Extraction de pierres ornementales, de calcaire industriel, de gypse, d’ardoise et d’autres pierres",
    "08.12": "Exploitation de gravières et sablières, extraction d’argiles et de kaolin",
    "08.91": "Extraction de minéraux chimiques et d’engrais minéraux",
    "08.92": "Extraction de tourbe",
    "08.93": "Production de sel",
    "08.99": "Autres activités extractives n.c.a.",
    "09.10": "Activités de soutien à l’extraction d’hydrocarbures",
    "09.90": "Activités de soutien aux autres industries extractives",
    "10.11": "Transformation et conservation de la viande, à l’exception de la viande de volaille",
    "10.12": "Transformation et conservation de la viande de volaille",
    "10.13": "Préparation de produits à base de viande et viande de volaille",
    "10.20": "Transformation et conservation de poisson, de crustacés et de mollusques",
    "10.31": "Transformation et conservation de pommes de terre",
    "10.32": "Préparation de jus de fruits et légumes",
    "10.39": "Autre transformation et conservation de fruits et légumes",
    "10.41": "Fabrication d’huiles et graisses",
    "10.42": "Fabrication de margarine et graisses comestibles similaires",
    "10.51": "Fabrication de produits laitiers",
    "10.52": "Fabrication de crèmes glacées et autres glaces alimentaires",
    "10.61": "Travail des grains",
    "10.62": "Fabrication de produits amylacés",
    "10.71": "Fabrication de pain; fabrication de pâtisserie fraîche",
    "10.72": "Fabrication de biscuits, biscottes et pâtisseries de conservation",
    "10.73": "Fabrication de pâtes alimentaires",
    "10.81": "Fabrication de sucre",
    "10.82": "Fabrication de cacao, de chocolat et de produits de confiserie",
    "10.83": "Transformation du thé et du café",
    "10.84": "Fabrication de condiments et assaisonnements",
    "10.85": "Fabrication de plats préparés",
    "10.86": "Fabrication d’aliments homogénéisés et diététiques",
    "10.89": "Fabrication d’autres produits alimentaires n.c.a.",
    "10.91": "Fabrication d’aliments pour animaux de ferme",
    "10.92": "Fabrication d’aliments pour animaux de compagnie",
    "11.01": "Production de boissons alcoolisées distillées",
    "11.02": "Production de vin (de raisin)",
    "11.03": "Fabrication de cidre et autres boissons fermentées à base de fruits",
    "11.04": "Production d’autres boissons fermentées non distillées",
    "11.05": "Fabrication de bière",
    "11.06": "Fabrication de malt",
    "11.07": "Fabrication de boissons non alcoolisées et d’eaux embouteillées",
    "12.00": "Fabrication de produits à base de tabac",
    "13.10": "Préparation de fibres textiles et filature",
    "13.20": "Tissage",
    "13.30": "Ennoblissement textile",
    "13.91": "Fabrication d’étoffes à mailles",
    "13.92": "Fabrication de textiles ménagers et d’articles d’ameublement confectionnés",
    "13.93": "Fabrication de tapis et moquettes",
    "13.94": "Fabrication de ficelles, cordes et filets",
    "13.95": "Fabrication de textiles non-tissés et articles non-tissés",
    "13.96": "Fabrication d’autres textiles techniques et industriels",
    "13.99": "Fabrication d’autres textiles n.c.a.",
    "14.10": "Fabrication d’articles à mailles",
    "14.21": "Fabrication de vêtements de dessus",
    "14.22": "Fabrication de vêtements de dessous",
    "14.23": "Fabrication de vêtements de travail",
    "14.24": "Fabrication de vêtements en cuir et en fourrure",
    "14.29": "Fabrication d’autres articles d’habillement et accessoires n.c.a.",
    "15.11": "Tannage, apprêt et teinture des cuirs et des fourrures",
    "15.12": "Fabrication de bagages, de maroquinerie, sellerie et bourrellerie, en toutes matières",
    "15.20": "Fabrication de chaussures",
    "16.11": "Sciage et rabotage du bois",
    "16.12": "Façonnage et finition du bois",
    "16.21": "Fabrication de placage et de panneaux de bois",
    "16.22": "Fabrication de parquets assemblés",
    "16.23": "Fabrication de charpentes et d’autres menuiseries",
    "16.24": "Fabrication d’emballages en bois",
    "16.25": "Fabrication de portes et fenêtres en bois",
    "16.26": "Fabrication de combustibles solides à partir de biomasse végétale",
    "16.27": "Finition de produits en bois",
    "16.28": "Fabrication d’objets divers en bois, d’objets en liège, vannerie et sparterie",
    "17.11": "Fabrication de pâte à papier",
    "17.12": "Fabrication de papier et de carton",
    "17.21": "Fabrication de papier et carton ondulés et d’emballages en papier ou en carton",
    "17.22": "Fabrication d’articles en papier à usage sanitaire ou domestique",
    "17.23": "Fabrication d’articles de papeterie",
    "17.24": "Fabrication de papiers peints",
    "17.25": "Fabrication d’autres articles en papier ou en carton",
    "18.11": "Imprimerie de journaux",
    "18.12": "Autres activités d’imprimerie",
    "18.13": "Activités de pré-presse",
    "18.14": "Reliure et activités connexes",
    "18.20": "Reproduction d’enregistrements",
    "19.10": "Cokéfaction",
    "19.20": "Raffinage du pétrole et fabrication de produits à base de combustibles fossiles",
    "20.11": "Fabrication de gaz industriels",
    "20.12": "Fabrication de colorants et de pigments",
    "20.13": "Fabrication d’autres produits chimiques inorganiques de base",
    "20.14": "Fabrication d’autres produits chimiques organiques de base",
    "20.15": "Fabrication de produits azotés et d’engrais",
    "20.16": "Fabrication de matières plastiques de base",
    "20.17": "Fabrication de caoutchouc synthétique",
    "20.20": "Fabrication de pesticides, de désinfectants et d’autres produits agrochimiques",
    "20.30": "Fabrication de peintures, vernis, encres et mastics",
    "20.41": "Fabrication de savons, détergents et produits d’entretien",
    "20.42": "Fabrication de parfums et de produits pour la toilette",
    "20.51": "Fabrication de biocarburants liquides",
    "20.59": "Fabrication d’autres produits chimiques n.c.a.",
    "20.60": "Fabrication de fibres artificielles ou synthétiques",
    "21.10": "Fabrication de produits pharmaceutiques de base",
    "21.20": "Fabrication de préparations pharmaceutiques",
    "22.11": "Fabrication et rechapage de pneus en caoutchouc et fabrication de chambres à air",
    "22.12": "Fabrication d’autres articles en caoutchouc",
    "22.21": "Fabrication de plaques, feuilles, tubes et profilés en matières plastiques",
    "22.22": "Fabrication d’emballages en matières plastiques",
    "22.23": "Fabrication de portes et fenêtres en matières plastiques",
    "22.24": "Fabrication d’éléments en matières plastiques pour la construction",
    "22.25": "Façonnage et finition de produits en matières plastiques",
    "22.26": "Fabrication d’autres articles en matières plastiques",
    "23.11": "Fabrication de verre plat",
    "23.12": "Façonnage et transformation du verre plat",
    "23.13": "Fabrication de verre creux",
    "23.14": "Fabrication de fibres de verre",
    "23.15": "Fabrication et façonnage d’autres articles en verre, y compris verre technique",
    "23.20": "Fabrication de produits réfractaires",
    "23.31": "Fabrication de carreaux en céramique",
    "23.32": "Fabrication de briques, tuiles et produits de construction, en terre cuite",
    "23.41": "Fabrication d’articles céramiques à usage domestique ou ornemental",
    "23.42": "Fabrication d’appareils sanitaires en céramique",
    "23.43": "Fabrication d’isolateurs et pièces isolantes en céramique",
    "23.44": "Fabrication d’autres produits céramiques à usage technique",
    "23.45": "Fabrication d’autres produits céramiques",
    "23.51": "Fabrication de ciment",
    "23.52": "Fabrication de chaux et plâtre",
    "23.61": "Fabrication d’éléments en béton pour la construction",
    "23.62": "Fabrication d’éléments en plâtre pour la construction",
    "23.63": "Fabrication de béton prêt à l’emploi",
    "23.64": "Fabrication de mortiers et de bétons secs",
    "23.65": "Fabrication d’ouvrages en fibre-ciment",
    "23.66": "Fabrication d’autres ouvrages en béton, en ciment ou en plâtre",
    "23.70": "Taille, façonnage et finissage de pierres",
    "23.91": "Fabrication de produits abrasifs",
    "23.99": "Fabrication d’autres produits minéraux non métalliques n.c.a.",
    "24.10": "Sidérurgie",
    "24.20": "Fabrication de tubes, tuyaux, profilés creux et accessoires correspondants en acier",
    "24.31": "Étirage à froid de barres",
    "24.32": "Laminage à froid de feuillards",
    "24.33": "Profilage à froid par formage ou pliage",
    "24.34": "Tréfilage à froid",
    "24.41": "Production de métaux précieux",
    "24.42": "Métallurgie de l’aluminium",
    "24.43": "Métallurgie du plomb, du zinc ou de l’étain",
    "24.44": "Métallurgie du cuivre",
    "24.45": "Métallurgie des autres métaux non ferreux",
    "24.46": "Élaboration et transformation de matières nucléaires",
    "24.51": "Fonderie de fonte",
    "24.52": "Fonderie d’acier",
    "24.53": "Fonderie de métaux légers",
    "24.54": "Fonderie d’autres métaux non ferreux",
    "25.11": "Fabrication de structures métalliques et de parties de structures",
    "25.12": "Fabrication de portes et fenêtres en métal",
    "25.21": "Fabrication de radiateurs et de chaudières pour le chauffage central",
    "25.22": "Fabrication d’autres réservoirs, citernes et conteneurs métalliques",
    "25.30": "Fabrication d’armes et de munitions",
    "25.40": "Forgeage et façonnage de métal; métallurgie des poudres",
    "25.51": "Revêtement des métaux",
    "25.52": "Traitement thermique des métaux",
    "25.53": "Usinage des métaux",
    "25.61": "Fabrication de coutellerie",
    "25.62": "Fabrication de serrures et de ferrures",
    "25.63": "Fabrication d’outillage",
    "25.91": "Fabrication de fûts et emballages métalliques similaires",
    "25.92": "Fabrication d’emballages métalliques légers",
    "25.93": "Fabrication d’articles en fils métalliques, de chaînes et de ressorts",
    "25.94": "Fabrication de vis et de boulons",
    "25.99": "Fabrication d’autres produits métalliques n.c.a.",
    "26.11": "Fabrication de composants électroniques",
    "26.12": "Fabrication de cartes électroniques assemblées",
    "26.20": "Fabrication d’ordinateurs et d’équipements périphériques",
    "26.30": "Fabrication d’équipements de communication",
    "26.40": "Fabrication de produits électroniques grand public",
    "26.51": "Fabrication d’instruments et d’appareils de mesure, d’essai et de navigation",
    "26.52": "Horlogerie",
    "26.60": "Fabrication d’équipements d’irradiation médicale, d’équipements électromédicaux et électrothérapeutiques",
    "26.70": "Fabrication de matériels optique et photographique et de supports magnétiques et optiques",
    "27.11": "Fabrication de moteurs, génératrices et transformateurs électriques",
    "27.12": "Fabrication de matériel de distribution et de commande électrique",
    "27.20": "Fabrication de piles et d’accumulateurs électriques",
    "27.31": "Fabrication de câbles de fibres optiques",
    "27.32": "Fabrication d’autres fils et câbles électroniques ou électriques",
    "27.33": "Fabrication de matériel d’installation électrique",
    "27.40": "Fabrication d’appareils d’éclairage",
    "27.51": "Fabrication d’appareils électroménagers",
    "27.52": "Fabrication d’appareils ménagers non électriques",
    "27.90": "Fabrication d’autres matériels électriques",
    "28.11": "Fabrication de moteurs et turbines, à l’exception des moteurs d’avions et de véhicules",
    "28.12": "Fabrication d’équipements de transmission de puissance hydrauliques et pneumatiques",
    "28.13": "Fabrication d’autres pompes et compresseurs",
    "28.14": "Fabrication d’autres articles de robinetterie",
    "28.15": "Fabrication de roulements et de transmissions mécaniques",
    "28.21": "Fabrication de fours et brûleurs et d’équipements fixes de chauffage domestique",
    "28.22": "Fabrication de matériel de levage et de manutention",
    "28.23": "Fabrication de machines et d’équipements de bureau (à l’exception des ordinateurs et équipements périphériques)",
    "28.24": "Fabrication d’outillage portatif à moteur incorporé",
    "28.25": "Fabrication d’équipements aérauliques et frigorifiques industriels",
    "28.29": "Fabrication de machines diverses d’usage général",
    "28.30": "Fabrication de machines agricoles et forestières",
    "28.41": "Fabrication de machines-outils pour le formage et le travail des métaux",
    "28.42": "Fabrication d’autres machines-outils",
    "28.91": "Fabrication de machines pour la métallurgie",
    "28.92": "Fabrication de machines pour l’extraction ou la construction",
    "28.93": "Fabrication de machines pour l’industrie agroalimentaire",
    "28.94": "Fabrication de machines pour les industries textiles et du cuir",
    "28.95": "Fabrication de machines pour les industries du papier et du carton",
    "28.96": "Fabrication de machines pour le travail du caoutchouc ou des plastiques",
    "28.97": "Fabrication de machines de fabrication additive",
    "28.99": "Fabrication d’autres machines d’usage spécifique n.c.a.",
    "29.10": "Construction de véhicules automobiles",
    "29.20": "Fabrication de carrosseries de véhicules automobiles; fabrication de remorques et de semi-remorques",
    "29.31": "Fabrication d’équipements électriques et électroniques automobiles",
    "29.32": "Fabrication d’autres équipements automobiles",
    "30.11": "Construction de navires et de structures flottantes civiles",
    "30.12": "Construction de bateaux de plaisance",
    "30.13": "Construction de bateaux et navires militaires",
    "30.20": "Construction de locomotives et d’autre matériel ferroviaire roulant",
    "30.31": "Construction aéronautique et spatiale civile",
    "30.32": "Construction aéronautique et spatiale militaire",
    "30.40": "Construction de véhicules militaires de combat",
    "30.91": "Fabrication de motocycles",
    "30.92": "Fabrication de bicyclettes et de véhicules pour invalides",
    "30.99": "Fabrication d’autres équipements de transport n.c.a.",
    "31.00": "Fabrication de meubles",
    "32.11": "Frappe de monnaie",
    "32.12": "Fabrication d’articles de joaillerie et bijouterie",
    "32.13": "Fabrication d’articles de bijouterie fantaisie et articles similaires",
    "32.20": "Fabrication d’instruments de musique",
    "32.30": "Fabrication d’articles de sport",
    "32.40": "Fabrication de jeux et jouets",
    "32.50": "Fabrication d’instruments et de fournitures à usage médical et dentaire",
    "32.91": "Fabrication d’articles de brosserie",
    "32.99": "Autres activités manufacturières n.c.a.",
    "33.11": "Réparation et entretien d’ouvrages en métaux",
    "33.12": "Réparation et entretien de machines",
    "33.13": "Réparation et entretien de matériels électroniques et optiques",
    "33.14": "Réparation et entretien d’équipements électriques",
    "33.15": "Réparation et entretien de bateaux et navires civils",
    "33.16": "Réparation et entretien d’aéronefs et d’engins spatiaux civils",
    "33.17": "Réparation et entretien d’autres équipements de transport civils",
    "33.18": "Réparation et entretien de véhicules de combat, de navires, de bateaux, d’aéronefs et d’engins spatiaux militaires",
    "33.19": "Réparation et entretien d’autres équipements",
    "33.20": "Installation de machines et d’équipements industriels",
    "35.11": "Production d’électricité à partir de sources non renouvelables",
    "35.12": "Production d’électricité à partir de sources renouvelables",
    "35.13": "Transport d’électricité",
    "35.14": "Distribution d’électricité",
    "35.15": "Commerce d’électricité",
    "35.16": "Stockage de l’électricité",
    "35.21": "Production de gaz",
    "35.22": "Distribution de combustibles gazeux par conduites",
    "35.23": "Commerce de combustibles gazeux par conduites",
    "35.24": "Stockage de gaz dans le cadre de services d’approvisionnement en réseau",
    "35.30": "Production et distribution de vapeur et d’air conditionné",
    "35.40": "Activités des courtiers et agents pour l’électricité et le gaz naturel",
    "36.00": "Captage, traitement et distribution d’eau",
    "37.00": "Collecte et traitement des eaux usées",
    "38.11": "Collecte des déchets non dangereux",
    "38.12": "Collecte des déchets dangereux",
    "38.21": "Récupération de matériaux",
    "38.22": "Valorisation énergétique",
    "38.23": "Autre valorisation des déchets",
    "38.31": "Incinération sans récupération d’énergie",
    "38.32": "Mise en décharge ou stockage permanent",
    "38.33": "Autre élimination des déchets",
    "39.00": "Activités de dépollution et autres activités de service de gestion des déchets",
    "41.00": "Construction de bâtiments résidentiels et non résidentiels",
    "42.11": "Construction de routes et autoroutes",
    "42.12": "Construction de voies ferrées de surface et souterraines",
    "42.13": "Construction de ponts et tunnels",
    "42.21": "Construction de réseaux pour fluides",
    "42.22": "Construction de réseaux électriques et de télécommunications",
    "42.91": "Construction d’ouvrages maritimes et fluviaux",
    "42.99": "Construction d’autres ouvrages de génie civil n.c.a.",
    "43.11": "Démolition",
    "43.12": "Travaux de préparation des sites",
    "43.13": "Forages et sondages",
    "43.21": "Installation électrique",
    "43.22": "Travaux de plomberie et installation de chauffage et de conditionnement d’air",
    "43.23": "Mise en place de l’isolation",
    "43.24": "Autres travaux d’installation",
    "43.31": "Travaux de plâtrerie",
    "43.32": "Travaux de menuiserie",
    "43.33": "Travaux de revêtement des sols et des murs",
    "43.34": "Travaux de peinture et vitrerie",
    "43.35": "Autres travaux de finition",
    "43.41": "Travaux de couverture",
    "43.42": "Autres travaux de construction spécialisés dans la construction de bâtiments",
    "43.50": "Travaux de construction spécialisés en génie civil",
    "43.60": "Activités de service d’intermédiation pour des travaux de construction spécialisés",
    "43.91": "Travaux de maçonnerie et de pose de briques",
    "43.99": "Autres travaux de construction spécialisés n.c.a.",
    "46.11": "Activités d’intermédiaire du commerce de gros en matières premières agricoles, animaux vivants, matières premières textiles et produits semi-finis",
    "46.12": "Activités d’intermédiaire du commerce de gros en combustibles, minerais, métaux et produits chimiques",
    "46.13": "Activités d’intermédiaire du commerce de gros en bois et matériaux de construction",
    "46.14": "Activités d’intermédiaire du commerce de gros en machines, équipements industriels, navires et avions",
    "46.15": "Activités d’intermédiaire du commerce de gros en meubles, biens domestiques et quincaillerie",
    "46.16": "Activités d’intermédiaire du commerce de gros en textiles, habillement, fourrures, chaussures et articles en cuir",
    "46.17": "Activités d’intermédiaire du commerce de gros en denrées, boissons et tabac",
    "46.18": "Activités d’intermédiaire spécialisé dans le commerce de gros d’autres produits spécifiques",
    "46.19": "Activités d’intermédiaire non spécialisé du commerce de gros",
    "46.21": "Commerce de gros de céréales, de tabac non manufacturé, de semences et d’aliments pour animaux",
    "46.22": "Commerce de gros de fleurs et de plantes",
    "46.23": "Commerce de gros d’animaux vivants",
    "46.24": "Commerce de gros de cuirs et de peaux",
    "46.31": "Commerce de gros de fruits et légumes",
    "46.32": "Commerce de gros de viande, de produits à base de viande, de poisson et de produits à base de poisson",
    "46.33": "Commerce de gros de produits laitiers, œufs, huiles et matières grasses comestibles",
    "46.34": "Commerce de gros de boissons",
    "46.35": "Commerce de gros de produits à base de tabac",
    "46.36": "Commerce de gros de sucre, chocolat et confiserie",
    "46.37": "Commerce de gros de café, thé, cacao et épices",
    "46.38": "Commerce de gros d’autres denrées alimentaires",
    "46.39": "Commerce de gros non spécialisé de denrées, boissons et tabac",
    "46.41": "Commerce de gros de textiles",
    "46.42": "Commerce de gros d’habillement et de chaussures",
    "46.43": "Commerce de gros d’appareils électroménagers",
    "46.44": "Commerce de gros de vaisselle, verrerie et produits d’entretien",
    "46.45": "Commerce de gros de parfumerie et de produits de beauté",
    "46.46": "Commerce de gros de produits pharmaceutiques et médicaux",
    "46.47": "Commerce de gros de meubles à usage domestique, de bureau et de magasin, de tapis et d’appareils d’éclairage",
    "46.48": "Commerce de gros d’articles d’horlogerie et de bijouterie",
    "46.49": "Commerce de gros d’autres biens domestiques",
    "46.50": "Commerce de gros d’équipements de l’information et de la communication",
    "46.61": "Commerce de gros de matériel agricole",
    "46.62": "Commerce de gros de machines-outils",
    "46.63": "Commerce de gros de machines pour l’extraction, la construction et le génie civil",
    "46.64": "Commerce de gros d’autres machines et équipements",
    "46.71": "Commerce de gros de véhicules automobiles",
    "46.72": "Commerce de gros de pièces et accessoires de véhicules automobiles",
    "46.73": "Commerce de gros de motocycles et de pièces et accessoires pour motocycles",
    "46.81": "Commerce de gros de combustibles solides, liquides et gazeux et de produits annexes",
    "46.82": "Commerce de gros de minerais et de métaux",
    "46.83": "Commerce de gros de bois, de matériaux de construction et d’appareils sanitaires",
    "46.84": "Commerce de gros de quincaillerie et fournitures pour plomberie et chauffage",
    "46.85": "Commerce de gros de produits chimiques",
    "46.86": "Commerce de gros d’autres produits intermédiaires",
    "46.87": "Commerce de gros de déchets et débris",
    "46.89": "Autre commerce de gros spécialisé n.c.a.",
    "46.90": "Commerce de gros non spécialisé",
    "47.11": "Commerce de détail non spécialisé à prédominance alimentaire",
    "47.12": "Autre commerce de détail non spécialisé",
    "47.21": "Commerce de détail de fruits et légumes",
    "47.22": "Commerce de détail de viande et de produits à base de viande",
    "47.23": "Commerce de détail de poisson, de crustacés et de mollusques",
    "47.24": "Commerce de détail de pain, de pâtisserie et de confiserie",
    "47.25": "Commerce de détail de boissons",
    "47.26": "Commerce de détail de produits à base de tabac",
    "47.27": "Commerce de détail d’autres produits alimentaires",
    "47.30": "Commerce de détail de carburants",
    "47.40": "Commerce de détail d’équipements de l’information et de la communication",
    "47.51": "Commerce de détail de textiles",
    "47.52": "Commerce de détail de quincaillerie, de matériaux de construction et de bricolage, de peinture et de verre",
    "47.53": "Commerce de détail de tapis, moquettes et revêtements de murs et de sols",
    "47.54": "Commerce de détail d’appareils électroménagers",
    "47.55": "Commerce de détail de meubles, d’appareils d’éclairage, de vaisselle et d’autres biens domestiques",
    "47.61": "Commerce de détail de livres",
    "47.62": "Commerce de détail de journaux et autres publications périodiques et de papeterie",
    "47.63": "Commerce de détail d’articles de sport",
    "47.64": "Commerce de détail de jeux et jouets",
    "47.69": "Commerce de détail de biens culturels et de loisirs n.c.a.",
    "47.71": "Commerce de détail d’habillement",
    "47.72": "Commerce de détail de chaussures et d’articles en cuir",
    "47.73": "Commerce de produits pharmaceutiques",
    "47.74": "Commerce de détail d’articles médicaux et orthopédiques",
    "47.75": "Commerce de détail de parfumerie et de produits de beauté",
    "47.76": "Commerce de détail de fleurs, plantes, engrais, animaux de compagnie et aliments pour ces animaux",
    "47.77": "Commerce de détail d’articles d’horlogerie et de bijouterie",
    "47.78": "Commerce de détail d’autres biens neufs",
    "47.79": "Commerce de détail de biens d’occasion",
    "47.81": "Commerce de détail de véhicules automobiles",
    "47.82": "Commerce de détail de pièces et accessoires de véhicules automobiles",
    "47.83": "Commerce de détail de motocycles et de pièces et accessoires de motocycles",
    "47.91": "Activités de service d’intermédiation pour le commerce de détail non spécialisé",
    "47.92": "Activités de service d’intermédiation pour le commerce de détail spécialisé",
    "49.11": "Transport ferroviaire lourd de voyageurs",
    "49.12": "Autre transport ferroviaire de voyageurs",
    "49.20": "Transport ferroviaire de fret",
    "49.31": "Transport régulier de voyageurs par route",
    "49.32": "Transport non régulier de voyageurs par route",
    "49.33": "Transport de voyageurs sur demande par véhicule avec chauffeur",
    "49.34": "Transport de voyageurs par téléphériques et remontées mécaniques",
    "49.39": "Autre transport terrestre de voyageurs n.c.a.",
    "49.41": "Transport routier de fret",
    "49.42": "Services de déménagement",
    "49.50": "Transport par conduites",
    "50.10": "Transports maritimes et côtiers de passagers",
    "50.20": "Transports maritimes et côtiers de fret",
    "50.30": "Transports fluviaux de passagers",
    "50.40": "Transports fluviaux de fret",
    "51.10": "Transports aériens de passagers",
    "51.21": "Transports aériens de fret",
    "51.22": "Transports spatiaux",
    "52.10": "Entreposage et stockage",
    "52.21": "Services auxiliaires des transports terrestres",
    "52.22": "Services auxiliaires des transports par eau",
    "52.23": "Services auxiliaires des transports aériens",
    "52.24": "Manutention du fret",
    "52.25": "Activités de service logistique",
    "52.26": "Autres activités de soutien pour les transports",
    "52.31": "Activités de service d’intermédiation pour le transport de fret",
    "52.32": "Activités de service d’intermédiation pour le transport de passagers",
    "53.10": "Activités de poste dans le cadre d’une obligation de service universel",
    "53.20": "Autres activités de poste et de courrier",
    "53.30": "Activités de service d’intermédiation pour des activités de poste et de courrier",
    "55.10": "Hôtels et hébergement similaire",
    "55.20": "Hébergement touristique et autre hébergement de courte durée",
    "55.30": "Terrains de camping et parcs pour caravanes ou véhicules de loisirs",
    "55.40": "Activités de service d’intermédiation pour l’hébergement",
    "55.90": "Autres hébergements",
    "56.11": "Activités de restaurant",
    "56.12": "Activités de service de restauration mobile",
    "56.21": "Activités de traiteur événementiel",
    "56.22": "Activités de service contractuel de restauration et autres activités de service de restauration",
    "56.30": "Activités de débit de boissons",
    "56.40": "Activités de service d’intermédiation pour des activités de service de restauration",
    "58.11": "Édition de livres",
    "58.12": "Édition de journaux",
    "58.13": "Édition de revues et de périodiques",
    "58.19": "Autres activités d’édition, à l’exception de l’édition de logiciels",
    "58.21": "Édition de jeux vidéo",
    "58.29": "Édition d’autres logiciels",
    "59.11": "Production de films cinématographiques, de vidéos et de programmes de télévision",
    "59.12": "Post-production de films cinématographiques, de vidéos et de programmes de télévision",
    "59.13": "Distribution de films cinématographiques et de vidéos",
    "59.14": "Projection de films cinématographiques",
    "59.20": "Enregistrement sonore et édition musicale",
    "60.10": "Radiodiffusion et activités de distribution de contenu audio",
    "60.20": "Programmation et diffusion télévisuelle et activités de distribution de contenu vidéo",
    "60.31": "Activités d’agence de presse",
    "60.39": "Autres activités de distribution de contenu",
    "61.10": "Activités de télécommunications filaires, sans fil et satellitaires",
    "61.20": "Activités de revente de télécommunications et activités de service d’intermédiation pour les télécommunications",
    "61.90": "Autres activités de télécommunications",
    "62.10": "Activités de programmation informatique",
    "62.20": "Activités de conseil en informatique et de gestion d’installations informatiques",
    "62.90": "Autres activités de service informatique",
    "63.10": "Infrastructure informatique, traitement de données, hébergement et activités connexes",
    "63.91": "Activités de portail de recherche sur le web",
    "63.92": "Autres activités de service d’information",
    "64.11": "Activités de banque centrale",
    "64.19": "Autre intermédiation monétaire",
    "64.21": "Activités de société holding",
    "64.22": "Activités de conduit de financement",
    "64.31": "Activités de fonds d’investissement sur le marché monétaire ou non monétaire",
    "64.32": "Activités de fiducie, comptes de patrimoine et d’agence",
    "64.91": "Crédit-bail",
    "64.92": "Autre distribution de crédit",
    "64.99": "Autres activités des services financiers, hors assurance et fonds de pension, n.c.a.",
    "65.11": "Assurance vie",
    "65.12": "Assurances non-vie",
    "65.20": "Réassurance",
    "65.30": "Fonds de pension",
    "66.11": "Administration de marchés financiers",
    "66.12": "Courtage de valeurs mobilières et de matières premières",
    "66.19": "Autres activités auxiliaires de services financiers, hors assurance et fonds de pension",
    "66.21": "Évaluation des risques et dommages",
    "66.22": "Activités des agents et courtiers d’assurances",
    "66.29": "Activités auxiliaires d’assurance et de fonds de pension n.c.a.",
    "66.30": "Activités de gestion de fonds",
    "68.11": "Achat et vente de biens propres",
    "68.12": "Promotion immobilière",
    "68.20": "Location et exploitation de biens immobiliers propres ou loués",
    "68.31": "Activités de service d’intermédiation pour les activités immobilières",
    "68.32": "Autres activités immobilières pour compte de tiers",
    "69.10": "Activités juridiques",
    "69.20": "Activités de comptabilité, de tenue de comptes et d’audit; conseil fiscal",
    "70.10": "Activités des sièges sociaux",
    "70.20": "Activités de conseil pour les affaires et autre conseil de gestion",
    "71.11": "Activités d’architecture",
    "71.12": "Activités d’ingénierie et de conseil technique connexe",
    "71.20": "Activités de contrôle et analyses techniques",
    "72.10": "Recherche et développement en sciences physiques et naturelles",
    "72.20": "Recherche et développement en sciences humaines et sociales",
    "73.11": "Activités d’agence de publicité",
    "73.12": "Régie publicitaire de médias",
    "73.20": "Études de marché et sondages",
    "73.30": "Activités de relations publiques et de communication",
    "74.11": "Activités de design pour la création de mode ou les produits industriels",
    "74.12": "Activités de design graphique et de communication visuelle",
    "74.13": "Activités de design d’intérieur",
    "74.14": "Autres activités spécialisées de design",
    "74.20": "Activités photographiques",
    "74.30": "Activités de traduction et d’interprétation",
    "74.91": "Activités de courtage et de marketing de brevets",
    "74.99": "Toutes les autres activités spécialisées, scientifiques et techniques n.c.a.",
    "75.00": "Activités vétérinaires",
    "77.11": "Location et location-bail de voitures et véhicules automobiles légers",
    "77.12": "Location et location-bail de camions",
    "77.21": "Location et location-bail d’articles de loisirs et de sport",
    "77.22": "Location et location-bail d’autres biens personnels et domestiques",
    "77.31": "Location et location-bail de matériel agricole",
    "77.32": "Location et location-bail de machines et équipements pour la construction et le génie civil",
    "77.33": "Location et location-bail de machines et équipements de bureau et d’ordinateurs",
    "77.34": "Location et location-bail de matériels de transport par eau",
    "77.35": "Location et location-bail de matériels de transport aérien",
    "77.39": "Location et location-bail d’autres machines, équipements et biens n.c.a.",
    "77.40": "Location-bail de propriété intellectuelle et de produits similaires, à l’exception des œuvres soumises à copyright",
    "77.51": "Activités de service d’intermédiation pour la location et la location-bail de voitures, camping-cars et caravanes",
    "77.52": "Activités de service d’intermédiation pour la location et la location-bail d’autres biens corporels et d’immobilisations incorporelles non financières",
    "78.10": "Activités des agences de placement de main-d’œuvre",
    "78.20": "Activités d’agence de travail temporaire et autre mise à disposition de ressources humaines",
    "79.11": "Activités d’agence de voyage",
    "79.12": "Activités de voyagiste",
    "79.90": "Autres activités de service de réservation et activités connexes",
    "80.01": "Activités d’investigation et de sécurité privée",
    "80.09": "Activités de sécurité n.c.a.",
    "81.10": "Activités de soutien combinées pour les installations",
    "81.21": "Nettoyage courant des bâtiments",
    "81.22": "Autres activités de nettoyage des bâtiments et nettoyage industriel",
    "81.23": "Autres activités de nettoyage",
    "81.30": "Activités de service d’aménagement paysager",
    "82.10": "Activités de service de bureau et de soutien administratif",
    "82.20": "Activités de centre d’appels",
    "82.30": "Organisation de salons professionnels et congrès",
    "82.40": "Activités de service d’intermédiation pour des services de soutien aux entreprises n.c.a.",
    "82.91": "Activités d’agence de recouvrement et de bureau de crédit",
    "82.92": "Activités de conditionnement",
    "82.99": "Autres activités de service de soutien aux entreprises n.c.a.",
    "84.11": "Activités d’administration publique générale",
    "84.12": "Réglementation des soins de santé, de l’enseignement, des services culturels et des autres services sociaux",
    "84.13": "Réglementation et contribution à l’amélioration de l’efficacité des activités économiques",
    "84.21": "Affaires étrangères",
    "84.22": "Défense",
    "84.23": "Justice",
    "84.24": "Activités d’ordre public et de sécurité civile",
    "84.25": "Activités de service d’incendie et de secours",
    "84.30": "Sécurité sociale obligatoire",
    "85.10": "Enseignement pré-primaire",
    "85.20": "Enseignement primaire",
    "85.31": "Enseignement secondaire general",
    "85.32": "Enseignement secondaire professionnel",
    "85.33": "Enseignement post-secondaire non supérieur",
    "85.40": "Enseignement supérieur",
    "85.51": "Enseignement de disciplines sportives et d’activités de loisirs",
    "85.52": "Enseignement culturel",
    "85.53": "Enseignement de la conduit",
    "85.59": "Autre enseignement n.c.a.",
    "85.61": "Activités de service d’intermédiation dans le domaine de l’appui scolaire et du tutorat",
    "85.69": "Activités de soutien à l’enseignement n.c.a.",
    "86.10": "Activités hospitalières",
    "86.21": "Activités de médecine générale",
    "86.22": "Activités de médecine spécialisée",
    "86.23": "Activités de soins dentaires",
    "86.91": "Activités d’imagerie médicale et de laboratoire d’analyse médicale",
    "86.92": "Transport de patients par ambulance",
    "86.93": "Activités des psychologues et psychothérapeutes, à l’exception des médecins",
    "86.94": "Activités de soins infirmiers et de maïeutique",
    "86.95": "Activités de physiothérapie",
    "86.96": "Activités de médecine traditionnelle, complémentaire et alternative",
    "86.97": "Activités de service d’intermédiation pour les services médicaux, dentaires et autres services pour la santé humaine",
    "86.99": "Autres activités pour la santé humaine n.c.a.",
    "87.10": "Activités d’hébergement médicalisé",
    "87.20": "Activités d’hébergement social pour personnes souffrant de maladie mentale ou de toxicomanie",
    "87.30": "Activités d’hébergement social pour personnes âgées ou en situation de handicap physique",
    "87.91": "Activités de service d’intermédiation pour des activités de soins en établissement résidentiel",
    "87.99": "Autres activités d’hébergement social n.c.a.",
    "88.10": "Activités d’action sociale sans hébergement pour personnes âgées ou en situation de handicap",
    "88.91": "Activités de garde d’enfants",
    "88.99": "Autres activités d’action sociale sans hébergement n.c.a.",
    "90.11": "Activités de création littéraire et de composition musicale",
    "90.12": "Activités de création en arts visuels",
    "90.13": "Autres activités de création artistique",
    "90.20": "Activités de spectacle",
    "90.31": "Gestion de lieux d’exposition artistique et de salles de spectacles",
    "90.39": "Autres activités de soutien à la création artistique et aux spectacles",
    "91.11": "Activités des bibliothèques",
    "91.12": "Activités des centres d’archives",
    "91.21": "Activités des musées et collections",
    "91.22": "Activité des monuments et sites historiques",
    "91.30": "Conservation, restauration et autres activités de soutien pour la préservation du patrimoine culturel",
    "91.41": "Activités de gestion de jardins botaniques et zoologiques",
    "91.42": "Activités de gestion de réserves naturelles",
    "92.00": "Activités de jeux d’argent et de paris",
    "93.11": "Gestion d’installations sportives",
    "93.12": "Activités des clubs de sports",
    "93.13": "Activités des centres de fitness",
    "93.19": "Autres activités sportives n.c.a.",
    "93.21": "Activités des parcs d’attractions et parcs à thème",
    "93.29": "Activités récréatives et de loisirs n.c.a.",
    "94.11": "Activités des organisations patronales et des chambres représentatives",
    "94.12": "Activités des organisations professionnelles",
    "94.20": "Activités des syndicats de salariés",
    "94.91": "Activités des organisations religieuses",
    "94.92": "Activités des organisations politiques",
    "94.99": "Activités des organisations associatives n.c.a.",
    "95.10": "Réparation et entretien d’ordinateurs et d’équipements de communication",
    "95.21": "Réparation et entretien de produits électroniques grand public",
    "95.22": "Réparation et entretien d’appareils électroménagers et d’équipements pour la maison et le jardin",
    "95.23": "Réparation et entretien de chaussures et d’articles en cuir",
    "95.24": "Réparation et entretien de meubles et d’équipements du foyer",
    "95.25": "Réparation et entretien d’articles d’horlogerie et de bijouterie",
    "95.29": "Réparation et entretien d’autres biens personnels ou domestiques n.c.a.",
    "95.31": "Réparation et entretien d’automobiles",
    "95.32": "Réparation et entretien de motocycles",
    "95.40": "Activités de service d’intermédiation pour la réparation et l’entretien d’ordinateurs, de biens personnels et domestiques et d’automobiles et motocycles",
    "96.10": "Blanchisserie-teinturerie",
    "96.21": "Coiffure et activités de barbier",
    "96.22": "Soins de beauté et autres activités de traitement esthétique",
    "96.23": "Activités de spa, de sauna et de bain de vapeur",
    "96.30": "Services funéraires et activités connexes",
    "96.40": "Activités de service d’intermédiation pour des services aux personnes",
    "96.91": "Activités d’offre de services domestiques aux personnes",
    "96.99": "Autres activités de service aux personnes n.c.a.",
    "97.00": "Activités des ménages en tant qu’employeurs de personnel domestique",
    "98.10": "Activités indifférenciées des ménages en tant que producteurs de biens pour usage propre",
    "98.20": "Activités indifférenciées des ménages en tant que producteurs de services pour usage propre",
    "99.00": "Activités des organisations et organismes extraterritoriaux",
}
