# Récupéré du tableur excel VSME de l'EFRAG
# NCV est en TJ/Gg
# densité est en kg/L (pour les liquides) ou kg/m³ (pour les gaz)
from decimal import Decimal

COMBUSTIBLES = {
    "Anthracite": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": Decimal("26.70"),
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Aviation gasoline": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("44.30"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.71"),
    },
    "Biodiesel": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("27.00"),
        "etat_renouvelabilite": "renouvelable",
        "densite": Decimal("0.85"),
    },
    "Biogasoline": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("27.00"),
        "etat_renouvelabilite": "renouvelable",
        "densite": Decimal("0.75"),
    },
    "Bitumen": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("40.20"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("1.04"),
    },
    "Blast furnace gas": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": Decimal("2.47"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("1.25"),
    },
    "Brown coal briquettes": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": Decimal("20.70"),
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Butane and isomers": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": Decimal("45.57"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("2.50"),
    },
    "Coke oven gas": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": Decimal("38.70"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.48"),
    },
    "Coking coal": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": Decimal("28.20"),
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Crude oil and distillates": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("42.30"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.80"),
    },
    "Ethane": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": Decimal("46.40"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("1.30"),
    },
    "Gas coke": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": Decimal("28.20"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.54"),
    },
    "Gas/Diesel oil": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("43.00"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.84"),
    },
    "Jet gasoline": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("44.30"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.81"),
    },
    "Jet kerosene": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("44.10"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.79"),
    },
    "Kerosene": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("43.80"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.80"),
    },
    "Landfill gas": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": Decimal("50.40"),
        "etat_renouvelabilite": "renouvelable",
        "densite": Decimal("0.90"),
    },
    "Lignite": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": Decimal("11.90"),
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Liquefied Petroleum Gases (LPG)": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("47.30"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.54"),
    },
    "Lubricants": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("40.20"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("1.00"),
    },
    "Methane": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": Decimal("50.00"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.67"),
    },
    "Motor gasoline/Petrol": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("44.30"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.74"),
    },
    "Municipal wastes (biomass fraction)": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": Decimal("11.60"),
        "etat_renouvelabilite": "renouvelable",
    },
    "Municipal wastes (non-biomass fraction)": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": Decimal("10.00"),
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Naphtha": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("44.50"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.77"),
    },
    "Natural gas": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": Decimal("48.00"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.70"),
    },
    "Natural gas liquids (NGL)": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("44.20"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.47"),
    },
    "Oil shale and tar sands": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("8.90"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.95"),
    },
    "Orimulsion": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("27.50"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("1.13"),
    },
    "Oxygen steel furnace gas": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": Decimal("7.06"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("1.33"),
    },
    "Paraffin waxes": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": Decimal("40.20"),
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Patent fuel": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": Decimal("20.70"),
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Peat": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": Decimal("9.76"),
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Petroleum coke": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": Decimal("32.50"),
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Propane": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": Decimal("46.32"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("1.90"),
    },
    "Refinery feedstocks": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("43.00"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.83"),
    },
    "Refinery Gas": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": Decimal("49.50"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.88"),
    },
    "Residual fuel oil": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("40.40"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.94"),
    },
    "Shale oil (liquid)": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("38.10"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("1.00"),
    },
    "Sludge gas": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": Decimal("50.40"),
        "etat_renouvelabilite": "renouvelable",
        "densite": Decimal("0.67"),
    },
    "Sub-bituminous coal": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": Decimal("18.90"),
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Sulphite lyes (black liquor)": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("11.80"),
        "etat_renouvelabilite": "renouvelable",
        "densite": Decimal("1.20"),
    },
    "Turpentine": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("44.40"),
        "etat_renouvelabilite": "renouvelable",
        "densite": Decimal("0.87"),
    },
    "Vegetable oils": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("37.80"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.90"),
    },
    "Waste oils": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("40.20"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.80"),
    },
    "Waste water treatment biogas": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": Decimal("35.00"),
        "etat_renouvelabilite": "renouvelable",
        "densite": Decimal("0.90"),
    },
    "White Spirit & SBP": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": Decimal("40.20"),
        "etat_renouvelabilite": "non_renouvelable",
        "densite": Decimal("0.75"),
    },
    "Wood/Wood waste": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": Decimal("15.60"),
        "etat_renouvelabilite": "renouvelable",
    },
}
