COMBUSTIBLES = {
    "Anthracite": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": 26.70,
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Aviation gasoline": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 44.30,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.71,
    },
    "Biodiesel": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 27.00,
        "etat_renouvelabilite": "renouvelable",
        "densite": 0.85,
    },
    "Biogasoline": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 27.00,
        "etat_renouvelabilite": "renouvelable",
        "densite": 0.75,
    },
    "Bitumen": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 40.20,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 1.04,
    },
    "Blast furnace gas": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": 2.47,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 1.25,
    },
    "Brown coal briquettes": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": 20.70,
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Butane and isomers": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": 45.57,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 2.50,
    },
    "Coke oven coke & lignite coke": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": 28.20,
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Coke oven gas": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": 38.70,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.48,
    },
    "Coking coal": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": 28.20,
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Crude oil and distillates": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 42.30,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.80,
    },
    "Ethane": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": 46.40,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 1.30,
    },
    "Gas coke": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": 28.20,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.54,
    },
    "Gas/Diesel oil": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 43.00,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.84,
    },
    "Jet gasoline": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 44.30,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.81,
    },
    "Jet kerosene": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 44.10,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.79,
    },
    "Kerosene": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 43.80,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.80,
    },
    "Landfill gas": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": 50.40,
        "etat_renouvelabilite": "renouvelable",
        "densite": 0.90,
    },
    "Lignite": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": 11.90,
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Liquefied Petroleum Gases (LPG)": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 47.30,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.54,
    },
    "Lubricants": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 40.20,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 1.00,
    },
    "Methane": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": 50.00,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.67,
    },
    "Motor gasoline/Petrol": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 44.30,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.74,
    },
    "Municipal wastes (biomass fraction)": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": 11.60,
        "etat_renouvelabilite": "renouvelable",
    },
    "Municipal wastes (non-biomass fraction)": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": 10.00,
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Naphtha": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 44.50,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.77,
    },
    "Natural gas": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": 48.00,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.70,
    },
    "Natural gas liquids (NGL)": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 44.20,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.47,
    },
    "Oil shale and tar sands": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 8.90,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.95,
    },
    "Orimulsion": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 27.50,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 1.13,
    },
    "Oxygen steel furnace gas": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": 7.06,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 1.33,
    },
    "Paraffin waxes": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": 40.20,
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Patent fuel": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": 20.70,
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Peat": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": 9.76,
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Petroleum coke": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": 32.50,
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Propane": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": 46.32,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 1.90,
    },
    "Refinery feedstocks": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 43.00,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.83,
    },
    "Refinery Gas": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": 49.50,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.88,
    },
    "Residual fuel oil": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 40.40,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.94,
    },
    "Shale oil (liquid)": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 38.10,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 1.00,
    },
    "Sludge gas": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": 50.40,
        "etat_renouvelabilite": "renouvelable",
        "densite": 0.67,
    },
    "Sub-bituminous coal": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": 18.90,
        "etat_renouvelabilite": "non_renouvelable",
    },
    "Sulphite lyes (black liquor)": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 11.80,
        "etat_renouvelabilite": "renouvelable",
        "densite": 1.20,
    },
    "Turpentine": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 44.40,
        "etat_renouvelabilite": "renouvelable",
        "densite": 0.87,
    },
    "Vegetable oils": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 37.80,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.90,
    },
    "Waste oils": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 40.20,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.80,
    },
    "Waste water treatment biogas": {
        "etat_chimique": "gaz",
        "unite": "m3",
        "NCV": 35.00,
        "etat_renouvelabilite": "renouvelable",
        "densite": 0.90,
    },
    "White Spirit & SBP": {
        "etat_chimique": "liquide",
        "unite": "L",
        "NCV": 40.20,
        "etat_renouvelabilite": "non_renouvelable",
        "densite": 0.75,
    },
    "Wood/Wood waste": {
        "etat_chimique": "solide",
        "unite": "t",
        "NCV": 15.60,
        "etat_renouvelabilite": "renouvelable",
    },
}
