# Generated by Django 4.1.1 on 2022-09-29 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.forms.fields
import public.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("siren", models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name="BDESE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.IntegerField(default=2022)),
                (
                    "effectif_total",
                    public.models.CategoryField(
                        base_field=django.forms.fields.IntegerField,
                        blank=True,
                        help_text="Tout salarié inscrit à l’effectif au 31/12 quelle que soit la nature de son contrat de travail",
                        null=True,
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="public.entreprise",
                    ),
                ),
            ],
        ),
    ]
