# Generated by Django 4.1.1 on 2022-09-30 15:00

from django.db import migrations, models
import django.forms.fields
import public.models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese",
            name="duree_moyenne_contrat_de_travail_temporaire",
            field=models.IntegerField(
                blank=True,
                help_text="En jours",
                null=True,
                verbose_name="Durée moyenne des contrats de travail temporaire",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="effectif_cdd",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="Nombre de salariés titulaires d’un contrat de travail à durée déterminée au 31/12",
                null=True,
                verbose_name="Effectif CDD",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="effectif_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField, blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="effectif_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField, blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="effectif_mensuel_moyen",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="Somme des effectifs totaux mensuels divisée par 12 (on entend par effectif total tout salarié inscrit à l’effectif au dernier jour du mois considéré)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="effectif_nationalite_etrangere",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Effectif de nationalité étrangère",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="effectif_nationalite_francaise",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Effectif de nationalité française",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="effectif_permanent",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="Les salariés à temps plein, inscrits à l’effectif pendant toute l’année considérée et titulaires d’un contrat de travail à durée indéterminée.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_moyen_mensuel_salaries_temporaires",
            field=models.IntegerField(
                blank=True,
                help_text="Est considérée comme salarié temporaire toute personne mise à la disposition de l’entreprise, par une entreprise de travail temporaire.",
                null=True,
                verbose_name="Nombre moyen mensuel de salariés temporaires",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_de_l_entreprise_detaches",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre de salariés de l'entreprise détachés",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_detaches_accueillis",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre de salariés détachés accueillis",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_stagiaires",
            field=models.IntegerField(
                blank=True,
                help_text="Stages supérieurs à une semaine.",
                null=True,
                verbose_name="Nombre de stagiaires",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_travailleurs_exterieurs",
            field=models.IntegerField(
                blank=True,
                help_text="Nombre de salariés appartenant à une entreprise extérieure (prestataire de services) dont l’entreprise connaît le nombre, soit parce qu’il figure dans le contrat signé avec l’entreprise extérieure, soit parce que ces travailleurs sont inscrits aux effectifs.",
                null=True,
                verbose_name="Nombre de travailleurs extérieurs",
            ),
        ),
    ]
