# Generated by Django 4.1.2 on 2022-10-14 16:52

from django.db import migrations, models
import django.forms.fields
import public.models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese",
            name="accords_conclus",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Dates et signatures et objet des accords conclus dans l'entreprise pendant l'année considérée",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="affectation_benefices",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="L'affectation des bénéfices réalisés",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="aides_financieres",
            field=models.TextField(
                blank=True,
                help_text="Pour chacune de ces aides, l'employeur indique la nature de l'aide, son objet, son montant, les conditions de versement et d'emploi fixées, le cas échéant, par la personne publique qui l'attribue et son utilisation",
                null=True,
                verbose_name="Les aides ou avantages financiers consentis à l'entreprise par l'Union européenne, l'Etat, une collectivité territoriale, un de leurs établissements publics ou un organisme privé chargé d'une mission de service public, et leur utilisation",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="avantages_sociaux",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Avantages sociaux dans l'entreprise : pour chaque avantage préciser le niveau de garantie pour les catégories retenues pour les effectifs",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="benefices_ou_pertes",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Les bénéfices ou pertes constatés"
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="bilan_gaz_effet_de_serre",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Bilan des émissions de gaz à effet de serre prévu par l'article L. 229-25 du code de l'environnement ou bilan simplifié prévu par l'article 244 de la loi n° 2020-1721 du 29 décembre 2020 de finances pour 2021 pour les entreprises tenues d'établir ces différents bilans",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="cessions_fusions_acquisitions",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Cessions, fusions, et acquisitions réalisées",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="charge_salariale_globale",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bdese",
            name="chiffre_affaires",
            field=models.IntegerField(
                blank=True, null=True, verbose_name=" Le chiffre d'affaires"
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="composition_CSE_etablissement",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Composition des comités sociaux et économiques et/ ou d'établissement avec indication, s'il y a lieu, de l'appartenance syndicale",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="consommation_eau",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="consommation d'eau"
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="consommation_energie",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="consommation d'énergie"
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="contributions_autres_depenses",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "logement",
                    "transport",
                    "restauration",
                    "loisirs",
                    "vacances",
                    "divers",
                ],
                help_text="Dépenses consolidées de l'entreprise.",
                null=True,
                verbose_name="Autres dépenses directement supportées par l'entreprise",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="contributions_financement_CSE_CSEE",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Contributions au financement, le cas échéant, du comité social et économique et des comités sociaux économiques d'établissement",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="cout_prestations_maladie_deces",
            field=models.IntegerField(
                blank=True,
                help_text="Versements directs ou par l'intermédiaire d'assurances",
                null=True,
                verbose_name="Coût pour l'entreprise des prestations complémentaires (maladie, décès)",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="cout_prestations_vieillesse",
            field=models.IntegerField(
                blank=True,
                help_text="Versements directs ou par l'intermédiaire d'assurances",
                null=True,
                verbose_name="Coût pour l'entreprise des prestations complémentaires (vieillesse)",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="credits_impots",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Crédits d'impôts"
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="differends_application_droit_du_travail",
            field=models.TextField(
                blank=True,
                help_text="Avec indication de la nature du différend et, le cas échéant, de la solution qui y a mis fin.",
                null=True,
                verbose_name="Différends concernant l'application du droit du travail",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="elements_systeme_accueil",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Eléments caractéristiques du système d'accueil",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="elements_systeme_entretiens_individuels",
            field=models.TextField(
                blank=True,
                help_text="Préciser leur périodicité.",
                null=True,
                verbose_name="Eléments caractéristiques du système d'entretiens individuels",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="elements_systeme_information",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Eléments caractéristiques du système d'information ascendante ou descendante et niveau d'application",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="equipements_pour_conditions_de_vie",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Equipements réalisés par l'entreprise et touchant aux conditions de vie des salariés à l'occasion de l'exécution du travail",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="exonerations_cotisations_sociales",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Exonérations et réductions de cotisations sociales",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="informations_environnementales",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Informations environnementales présentées en application du 2° du A du II de l'article R. 225-105 du code de commerce",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="mecenat",
            field=models.IntegerField(blank=True, null=True, verbose_name="Mécénat"),
        ),
        migrations.AddField(
            model_name="bdese",
            name="montant_10_remunerations_les_plus_eleves",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Montant global des dix rémunérations les plus élevées.",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="montant_global_hautes_remunerations",
            field=models.IntegerField(
                blank=True,
                help_text="Montant global, certifié exact par les commissaires aux comptes, s'il en existe, des rémunérations versées aux personnes les mieux rémunérées, le nombre de ces personnes étant de dix ou de cinq selon que l'effectif du personnel excède ou non deux cents salariés ; uniquement pour les entreprises soumises aux dispositions de l'article L. 225-115 du code de commerce",
                null=True,
                verbose_name="Montant global des hautes rémunérations",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="montant_global_reserve_de_participation",
            field=models.IntegerField(
                blank=True,
                help_text="Le montant global de la réserve de participation est le montant de la réserve dégagée-ou de la provision constituée-au titre de la participation sur les résultats de l'exercice considéré.",
                null=True,
                verbose_name="Montant global de la réserve de participation",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="montant_moyen_participation",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="La participation est envisagée ici au sens du titre II du livre III de la partie III.",
                null=True,
                verbose_name="Montant moyen de la participation et/ ou de l'intéressement par salarié bénéficiaire",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_heures_reunion_personnel",
            field=models.IntegerField(
                blank=True,
                help_text="On entend par réunion du personnel, les réunions régulières de concertation, concernant les relations et conditions de travail organisées par l'entreprise.",
                null=True,
                verbose_name="Nombre d'heures consacrées aux différentes formes de réunion du personnel",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_personnes_conge_education_ouvriere",
            field=models.IntegerField(
                blank=True,
                help_text="Au sens des articles L. 2145-5 et suivants.",
                null=True,
                verbose_name="Nombre de personnes bénéficiaires d'un congé d'éducation ouvrière",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_reunion_representants_personnel",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre de réunions avec les représentants du personnel et les délégués syndicaux pendant l'année considérée",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="part_capital_detenu_par_salaries",
            field=models.IntegerField(
                blank=True,
                help_text="système de participation\xa0: participation aux résultats, intéressement, actionnariat …",
                null=True,
                verbose_name="Part du capital détenu par les salariés (dirigeants exclus) grâce à un système de participation",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="part_primes_non_mensuelle",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="part des primes à périodicité non mensuelle dans la déclaration de salaire",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="partenariats_pour_beneficier",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Partenariats conclus pour bénéficier des services ou des produits d'une autre entreprise",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="partenariats_pour_produire",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Partenariats conclus pour produire des services ou des produits pour une autre entreprise",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="participation_elections",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Participation aux élections (par collège) par catégories de représentants du personnel",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="postes_emissions_directes_gaz_effet_de_serre",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Bilan des émissions de gaz à effet de serre prévu par l'article L. 229-25 du code de l'environnement ou bilan simplifié prévu par l'article 244 de la loi n° 2020-1721 du 29 décembre 2020 de finances pour 2021 pour les entreprises tenues d'établir ces différents bilans",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="pourcentage_ouvriers_employes_payes_au_mois",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Pourcentage des ouvriers et employés payés au mois sur la base de l'horaire affiché",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="pourcentage_salaries_primes_de_rendement",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=["primes individuelles", "primes collectives"],
                null=True,
                verbose_name="Pourcentage des salariés dont le salaire dépend, en tout ou partie, du rendement",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="prevention_et_gestion_dechets",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Prévention et gestion de la production de déchets : évaluation de la quantité de déchets dangereux définis à l'article R. 541-8 du code de l'environnement et faisant l'objet d'une émission du bordereau mentionné à l'article R. 541-45 du même code",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="prise_en_compte_questions_environnementales",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Organisation de l'entreprise pour prendre en compte les questions environnementales et, le cas échéant, les démarches d'évaluation ou de certification en matière d'environnement",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="quantite_de_dechets_dangereux",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="évaluation de la quantité de déchets dangereux définis à l'article R. 541-8 du code de l'environnement et faisant l'objet d'une émission du bordereau mentionné à l'article R. 541-45 du même code",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="rapport_masse_salariale_effectif_mensuel",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="Masse salariale annuelle totale, au sens de la déclaration annuelle de salaire",
                null=True,
                verbose_name="Rapport entre la masse salariale annuelle et l'effectif mensuel moyen",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="rapport_moyenne_cadres_ouvriers",
            field=models.IntegerField(
                blank=True,
                help_text="Pour être prises en compte, les catégories concernées doivent comporter au minimum dix salariés.",
                null=True,
                verbose_name="Rapport entre la moyenne des rémunérations des cadres ou assimilés (y compris cadres supérieurs et dirigeants) et la moyenne des rémunérations des ouvriers non qualifiés ou assimilés.",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="rapport_moyenne_deciles",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="rapport entre la moyenne des rémunérations des 10 % des salariés touchant les rémunérations les plus élevées et celle correspondant au 10 % des salariés touchant les rémunérations les moins élevées",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="reductions_impots",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Réductions d'impôts"
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="remuneration_actionnaires",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Rémunération des actionnaires (revenus distribués)",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="remuneration_actionnariat_salarie",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Rémunération de l'actionnariat salarié (montant des actions détenues dans le cadre de l'épargne salariale, part dans le capital, dividendes reçus)",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="remuneration_dirigeants_mandataires_sociaux",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Rémunération des dirigeants mandataires sociaux",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="remuneration_mensuelle_moyenne",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Rémunération mensuelle moyenne",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="remuneration_moyenne_decembre",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="base 35 heures",
                null=True,
                verbose_name="Rémunération moyenne du mois de décembre (effectif permanent) hors primes à périodicité non mensuelle",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="remunerations",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "- de 1.000",
                    "1.000-2.000",
                    "2.000-3.000",
                    "3.000-4.000",
                    "4.000-5.000",
                    "5.000 et plus",
                ],
                null=True,
                verbose_name="Grille des rémunérations",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="resultats_globaux",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=["valeur", "volume"],
                null=True,
                verbose_name="Les résultats globaux de la production",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="transferts_de_capitaux",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Transferts de capitaux tels qu'ils figurent dans les comptes individuels des sociétés du groupe lorsqu'ils présentent une importance significative",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="volume_credit_heures",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Volume global des crédits d'heures utilisés pendant l'année considérée",
            ),
        ),
    ]
