# Generated by Django 4.1.1 on 2022-10-04 08:25

from django.db import migrations
import django.forms.fields
import public.models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0002_bdese_duree_moyenne_contrat_de_travail_temporaire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese",
            name="effectif_age",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "moins de 25 ans",
                    "entre 25 et 35 ans",
                    "entre 35 et 45 ans",
                    "entre 45 et 55 ans",
                    "plus de 55 ans",
                ],
                null=True,
            ),
        ),
    ]
