# Generated by Django 4.1.2 on 2022-10-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0002_bdese_accords_conclus_bdese_affectation_benefices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="accord",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="effectif",
            field=models.CharField(default="grand", max_length=9),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="raison_sociale",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="siren",
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
