# Generated by Django 4.1.1 on 2022-10-04 08:32

from django.db import migrations
import django.forms.fields
import public.models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0003_bdese_effectif_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese",
            name="effectif_anciennete",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=["moins de 10 ans", "entre 10 et 20 ans", "plus de 30 ans"],
                null=True,
                verbose_name="Effectif par ancienneté",
            ),
        ),
        migrations.AlterField(
            model_name="bdese",
            name="effectif_age",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "moins de 25 ans",
                    "entre 25 et 35 ans",
                    "entre 35 et 45 ans",
                    "entre 45 et 55 ans",
                    "plus de 55 ans",
                ],
                null=True,
                verbose_name="Effectif par âge",
            ),
        ),
    ]
