# Generated by Django 4.1.1 on 2022-10-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0003_entreprise_accord_entreprise_effectif_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entreprise",
            old_name="accord",
            new_name="bdese_accord",
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="effectif",
            field=models.CharField(
                choices=[
                    ("petit", "moins de 50"),
                    ("moyen", "entre 50 et 300"),
                    ("grand", "entre 301 et 499"),
                    ("sup500", "500 et plus"),
                ],
                default="grand",
                help_text="Saisissez le nombre de salariés",
                max_length=9,
            ),
        ),
    ]
