# Generated by Django 4.1.1 on 2022-10-04 09:46

from django.db import migrations, models
import django.forms.fields
import public.models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0004_bdese_effectif_anciennete_alter_bdese_effectif_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese",
            name="nombre_deces",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de décès",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_demissions",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de démissions",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_departs_volontaires_retraite_preretraite",
            field=models.TextField(
                blank=True,
                help_text="Distinguer les différents systèmes légaux et conventionnels de toute nature",
                null=True,
                verbose_name="Nombre de départs volontaires en retraite et préretraite",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_embauches_cdd",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="dont nombre de contrats de travailleurs saisonniers",
                null=True,
                verbose_name="Nombre d'embauches par contrats de travail à durée déterminée",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_embauches_cdi",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre d'embauches par contrats de travail à durée indéterminée",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_embauches_jeunes",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre d'embauches de salariés de moins de vingt-cinq ans",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_fin_cdd",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de fins de contrats de travail à durée déterminée",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_fin_periode_essai",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="à ne remplir que si ces départs sont comptabilisés dans le total des départs",
                null=True,
                verbose_name="Nombre de départs au cours de la période d’essai",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_licenciements_autres",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de licenciements pour d’autres causes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_licenciements_economiques",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="dont départs en retraite et préretraite",
                null=True,
                verbose_name="Nombre de licenciements pour motif économique",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_mutations",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de mutations d’un établissement à un autre",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="total_departs",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Total des départs",
            ),
        ),
    ]
