# Generated by Django 4.1.1 on 2022-10-04 10:09

from django.db import migrations, models
import django.forms.fields
import public.models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0005_bdese_nombre_deces_bdese_nombre_demissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese",
            name="nombre_heures_chomage_intemperies_indemnisees",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre total d'heures de chômage intempéries indemnisées",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_heures_chomage_intemperies_non_indemnisees",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre total d'heures de chômage intempéries non indemnisées",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_heures_chomage_partiel_indemnisees",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="Y compris les heures indemnisées au titre du chômage total en cas d’arrêt de plus de quatre semaines consécutives",
                null=True,
                verbose_name="Nombre total d'heures de chômage partiel indemnisées",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_heures_chomage_partiel_non_indemnisees",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre total d'heures de chômage partiel non indemnisées",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_promotions",
            field=models.IntegerField(
                blank=True,
                help_text="Utiliser les catégories de la nomenclature détaillée",
                null=True,
                verbose_name="Nombre de salariés promus dans l’année dans une catégorie supérieure",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_chomage_intemperies",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de salariés mis en chômage intempéries",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_chomage_partiel",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de salariés mis en chômage partiel pendant l’année considérée",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_travailleurs_handicapes_accidents_du_travail",
            field=models.IntegerField(
                blank=True,
                help_text="employés sur l'année considérée",
                null=True,
                verbose_name="Nombre de travailleurs handicapés à la suite d'accidents du travail intervenus dans l'entreprise",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_travailleurs_handicapés",
            field=models.IntegerField(
                blank=True,
                help_text="tel qu’il résulte de la déclaration obligatoire prévue à l’article L. 5212-5.",
                null=True,
                verbose_name="Nombre de travailleurs handicapés employés sur l'année considérée",
            ),
        ),
    ]
