# Generated by Django 4.1.1 on 2022-10-04 11:31

from django.db import migrations, models
import django.forms.fields
import public.models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0006_bdese_nombre_heures_chomage_intemperies_indemnisees_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese",
            name="montant_formation_continue",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "formation interne",
                    "formation effectuée en application de conventions",
                    "versement aux organismes de recouvrement",
                    "versement auprès d'organismes agréés",
                    "autres",
                ],
                null=True,
                verbose_name="Montant consacré à la formation continue",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_contrats_apprentissage",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre de contrats d’apprentissage conclus dans l’année",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_heures_stage_non_remunerees",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre d'heures de stage non rémunérées",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_heures_stage_remunerees",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre d'heures de stage rémunérées",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_conge_formation_non_remunere",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre de salariés ayant bénéficié d'un congé formation non rémunéré",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_conge_formation_refuse",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre de salariés auxquels a été refusé un congé formation",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_conge_formation_remunere",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre de salariés ayant bénéficié d'un congé formation rémunéré",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="pourcentage_masse_salariale_formation_continue",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Pourcentage de la masse salariale afférent à la formation continue",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="type_stages",
            field=models.TextField(
                blank=True,
                help_text="à titre d'exemple : adaptation, formation professionnelle, entretien ou perfectionnement des connaissances",
                null=True,
                verbose_name="Décomposition par type de stages",
            ),
        ),
    ]
