# Generated by Django 4.1.1 on 2022-10-04 11:48

from django.db import migrations, models
import django.forms.fields
import public.models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0007_bdese_montant_formation_continue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese",
            name="montant_cotisation_securite_sociale_accidents_travail",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Montant de la cotisation sécurité sociale d'accidents de travail",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_accidents_salaries_temporaires_ou_prestataires",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre d'accidents dont sont victimes les salariés temporaires ou de prestations de services dans l'entreprise",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_accidents_trajet_avec_arret_travail",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre d'accidents de trajet ayant entraîné un arrêt de travail",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_accidents_trajet_mortels",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre d'accidents mortels de trajet",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_accidents_travail_mortels",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre d'accidents mortels de travail",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_incapacites_permanentes_partielles",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=["français", "étrangers"],
                null=True,
                verbose_name="Nombre d'incapacités permanentes partielles notifiées à l'entreprise au cours de l'année considérée",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_incapacites_permanentes_totales",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=["français", "étrangers"],
                null=True,
                verbose_name="Nombre d'incapacités permanentes totales notifiées à l'entreprise au cours de l'année considérée",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="taux_cotisation_securite_sociale_accidents_travail",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Taux de la cotisation sécurité sociale d'accidents de travail",
            ),
        ),
    ]
