# Generated by Django 4.1.2 on 2022-10-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "public",
            "0008_bdese_montant_cotisation_securite_sociale_accidents_travail_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese",
            name="nombre_accidents_autres",
            field=models.IntegerField(blank=True, null=True, verbose_name="Autres cas"),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_accidents_chutes_dénivellation",
            field=models.IntegerField(
                blank=True,
                help_text="Code 02",
                null=True,
                verbose_name="Nombre d'accidents liés à des chutes avec dénivellation",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_accidents_circulation_manutention_stockage",
            field=models.IntegerField(
                blank=True,
                help_text="Codes 01, 03, 04 et 06, 07, 08",
                null=True,
                verbose_name="Nombre d'accidents de circulation-manutention-stockage",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_accidents_existence_risques_graves",
            field=models.IntegerField(
                blank=True,
                help_text="Codes 32 à 40",
                null=True,
                verbose_name="Nombre d'accidents liés à l'existence de risques grave",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_accidents_machines",
            field=models.IntegerField(
                blank=True,
                help_text="À l'exception de ceux liés aux risques ci-dessus, codes 09 à 30",
                null=True,
                verbose_name="Nombre d'accidents occasionnés par des machines",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_accidents_objets_en_mouvement",
            field=models.IntegerField(
                blank=True,
                help_text="Code 05",
                null=True,
                verbose_name="Nombre d'accidents occasionnés par des objets, masses, particules en mouvement accidentel",
            ),
        ),
    ]
