# Generated by Django 4.1.2 on 2022-10-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0009_bdese_nombre_accidents_autres_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese",
            name="caracterisation_affections_pathologiques",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Caractérisation des affections pathologiques à caractère professionnel",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="denomination_maladies_professionnelles",
            field=models.TextField(
                blank=True,
                help_text="Dénomination des maladies professionnelles déclarées à la sécurité sociale au cours de l'année",
                null=True,
                verbose_name="Dénomination des maladies professionnelles",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_declaration_procedes_travail_dangereux",
            field=models.IntegerField(
                blank=True,
                help_text="En application de l'article L. 461-4 du code de la sécurité sociale",
                null=True,
                verbose_name="Nombre de déclarations par l'employeur de procédés de travail susceptibles de provoquer des maladies professionnelles",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_maladies_professionnelles",
            field=models.IntegerField(
                blank=True,
                help_text="Nombre des maladies professionnelles déclarées à la sécurité sociale au cours de l'année",
                null=True,
                verbose_name="Nombre des maladies professionnelles",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_affections_pathologiques",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre de salariés atteints par des affections pathologiques à caractère professionnel",
            ),
        ),
    ]
