# Generated by Django 4.1.1 on 2022-10-07 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("public", "0010_bdese_caracterisation_affections_pathologiques_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
