# Generated by Django 4.1.1 on 2022-10-11 13:45

from django.db import migrations, models
import django.forms.fields
import public.models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0011_entreprise_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese",
            name="age_moyen_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Age moyen des femmes par catégorie professionnelle",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="age_moyen_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Age moyen des hommes par catégorie professionnelle",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="anciennete_moyenne_dans_categorie_profesionnelle_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Ancienneté moyenne des femmes dans chaque catégorie professionnelle",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="anciennete_moyenne_dans_categorie_profesionnelle_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Ancienneté moyenne des hommes dans chaque catégorie professionnelle",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="anciennete_moyenne_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Ancienneté moyenne des femmes par catégorie professionnelle",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="anciennete_moyenne_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Ancienneté moyenne des hommes par catégorie professionnelle",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="conges_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Répartition des congés des femmes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="conges_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Répartition des congés des hommes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="conges_par_type_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "compte épargne-temps",
                    "congé parental",
                    "congé sabbatique",
                ],
                null=True,
                verbose_name="Répartition des congés des femmes selon le type de congés dont la durée est supérieure à six mois",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="conges_par_type_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "compte épargne-temps",
                    "congé parental",
                    "congé sabbatique",
                ],
                null=True,
                verbose_name="Répartition des congés des hommes selon le type de congés dont la durée est supérieure à six mois",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="departs_demission_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de femmes ayant démissionné",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="departs_demission_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre d'hommes ayant démissionné",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="departs_fin_CDD_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de femmes en fin de CDD",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="departs_fin_CDD_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre d'hommes en fin de CDD",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="departs_licenciement_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de femmes licenciées",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="departs_licenciement_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre d'hommes licenciés",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="departs_retraite_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de femmes partis en retraite",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="departs_retraite_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre d'hommes partis en retraite",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="duree_moyenne_entre_deux_promotions_femme",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Durée moyenne entre deux promotions pour les femmes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="duree_moyenne_entre_deux_promotions_homme",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Durée moyenne entre deux promotions pour les hommes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="effectif_par_duree_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "temps complet",
                    "temps partiel entre 20 et 30 heures",
                    "autres temps partiels",
                ],
                null=True,
                verbose_name="Répartition des effectifs femmes selon la durée du travail",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="effectif_par_duree_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "temps complet",
                    "temps partiel entre 20 et 30 heures",
                    "autres temps partiels",
                ],
                null=True,
                verbose_name="Répartition des effectifs hommes selon la durée du travail",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="effectif_par_organisation_du_travail_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "travail posté",
                    "travail de nuit",
                    "horaires variables",
                    "travail atypique dont travail durant le week-end",
                ],
                null=True,
                verbose_name="Répartition des effectifs femmes selon l'organisation du travail",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="effectif_par_organisation_du_travail_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "travail posté",
                    "travail de nuit",
                    "horaires variables",
                    "travail atypique dont travail durant le week-end",
                ],
                null=True,
                verbose_name="Répartition des effectifs hommes selon l'organisation du travail",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="embauches_CDD_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Répartition des embauches femmes en CDD par catégorie professionnelle",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="embauches_CDD_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Répartition des embauches hommes en CDD par catégorie professionnelle",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="embauches_CDI_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Répartition des embauches femmes en CDI par catégorie professionnelle",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="embauches_CDI_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Répartition des embauches hommes en CDI par catégorie professionnelle",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_CDD_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de femmes en CDD",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_CDD_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre d'hommes en CDD",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_CDI_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de femmes en CDI",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_CDI_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre d'hommes en CDI",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_femmes_plus_hautes_remunerations",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre de femmes dans les dix plus hautes rémunérations",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_promotions_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de promotions femme",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_promotions_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de promotions homme",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="remuneration_moyenne_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Rémunération moyenne mensuelle des femmes par catégorie professionnelle",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="remuneration_moyenne_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Rémunération moyenne mensuelle des hommes par catégorie professionnelle",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="remuneration_moyenne_par_age_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "moins de 30 ans",
                    "30 à 39 ans",
                    "40 à 49 ans",
                    "50 ans et plus",
                ],
                null=True,
                verbose_name="Rémunération moyenne mensuelle des femmes par tranche d'âge",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="remuneration_moyenne_par_age_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "moins de 30 ans",
                    "30 à 39 ans",
                    "40 à 49 ans",
                    "50 ans et plus",
                ],
                null=True,
                verbose_name="Rémunération moyenne mensuelle des hommes par tranche d'âge",
            ),
        ),
    ]
