# Generated by Django 4.1.2 on 2022-10-11 17:13

from django.db import migrations
import django.forms.fields
import public.models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0012_bdese_age_moyen_femme_bdese_age_moyen_homme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese",
            name="action_adaptation_au_poste_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Répartition des femmes pour l'adaptation au poste",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="action_adaptation_au_poste_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Répartition des hommes pour l'adaptation au poste",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="action_developpement_competences_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Répartition des femmes pour le développement des compétences",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="action_developpement_competences_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Répartition des hommes pour le développement des compétences",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="action_maintien_emploi_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Répartition des femmes pour le maintien dans l'emploi",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="action_maintien_emploi_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Répartition des hommes pour le maintien dans l'emploi",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_moyen_heures_formation_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre moyen d'heures d'actions de formation par salariée et par an",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_moyen_heures_formation_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre moyen d'heures d'actions de formation par salarié et par an",
            ),
        ),
    ]
