# Generated by Django 4.1.1 on 2022-10-12 09:55

from django.db import migrations
import django.forms.fields
import public.models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0013_bdese_action_adaptation_au_poste_femme_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bdese",
            name="nombre_moyen_heures_formation_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="femmes",
                null=True,
                verbose_name="Nombre moyen d'heures d'actions de formation par salariée et par an",
            ),
        ),
        migrations.AlterField(
            model_name="bdese",
            name="nombre_moyen_heures_formation_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="hommes",
                null=True,
                verbose_name="Nombre moyen d'heures d'actions de formation par salarié et par an",
            ),
        ),
    ]
