# Generated by Django 4.1.2 on 2022-10-13 08:34

from django.db import migrations, models
import django.forms.fields
import public.models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0014_alter_bdese_nombre_moyen_heures_formation_femme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese",
            name="accidents_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "accidents de travail",
                    "accidents de trajet",
                    "maladies professionnelles",
                ],
                null=True,
                verbose_name="Accidents de travail, accidents de trajet et maladies professionnelles chez les femmes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="accidents_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "accidents de travail",
                    "accidents de trajet",
                    "maladies professionnelles",
                ],
                null=True,
                verbose_name="Accidents de travail, accidents de trajet et maladies professionnelles chez les hommes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="complement_salaire_conge",
            field=models.BooleanField(
                default=False,
                help_text="Existence d'un complément de salaire versé par l'employeur pour le congé de paternité, le congé de maternité, le congé d'adoption",
                verbose_name="Complément de salaire versé par l'employeur",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="effectif_forme_securite",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Effectif formé à la sécurité dans l'année",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="evolution_depenses_credit_impot_famille",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Evolution des dépenses éligibles au crédit d'impôt famille",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="existence_organisation_facilitant_vie_familiale_et_professionnelle",
            field=models.BooleanField(
                default=False,
                verbose_name="Existence de formules d'organisation du travail facilitant l'articulation de la vie familiale et de la vie professionnelle",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="exposition_risques_pro_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "manutentions manuelles de charges",
                    "postures pénibles",
                    "vibrations mécaniques",
                    "agents chimiques dangereux",
                    "milieu hyperbare",
                    "températures extrêmes",
                    "bruit",
                    "travail de nuit",
                    "travail en équipes successives alternantes",
                    "travail répétitif",
                ],
                null=True,
                verbose_name="Répartition des postes de travail exposés à des risques professionnels occupés par des femmes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="exposition_risques_pro_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "manutentions manuelles de charges",
                    "postures pénibles",
                    "vibrations mécaniques",
                    "agents chimiques dangereux",
                    "milieu hyperbare",
                    "températures extrêmes",
                    "bruit",
                    "travail de nuit",
                    "travail en équipes successives alternantes",
                    "travail répétitif",
                ],
                null=True,
                verbose_name="Répartition des postes de travail exposés à des risques professionnels occupés par des hommes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="horaire_hebdomadaire_moyen",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="Il est possible de remplacer cet indicateur par la somme des heures travaillées durant l'année.",
                null=True,
                verbose_name="Horaire hebdomadaire moyen affiché des ouvriers et employés ou catégories assimilées",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="maladies_avec_examen_de_reprise_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "nombre d'arrêts de travail",
                    "nombre de journées d'absence",
                ],
                help_text="en application du 3° de l'article R. 4624-31",
                null=True,
                verbose_name="Maladies ayant donné lieu à un examen de reprise du travail chez les femmes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="maladies_avec_examen_de_reprise_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "nombre d'arrêts de travail",
                    "nombre de journées d'absence",
                ],
                help_text="en application du 3° de l'article R. 4624-31",
                null=True,
                verbose_name="Maladies ayant donné lieu à un examen de reprise du travail chez les hommes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="maladies_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "nombre d'arrêts de travail",
                    "nombre de journées d'absence",
                ],
                null=True,
                verbose_name="Maladies chez les femmes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="maladies_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "nombre d'arrêts de travail",
                    "nombre de journées d'absence",
                ],
                null=True,
                verbose_name="Maladies chez les hommes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="mesures_prises_egalite",
            field=models.TextField(
                blank=True,
                help_text="Bilan des actions de l'année écoulée et, le cas échéant, de l'année précédente. Evaluation du niveau de réalisation des objectifs sur la base des indicateurs retenus. Explications sur les actions prévues non réalisées",
                null=True,
                verbose_name="Mesures prises au cours de l'année écoulée en vue d'assurer l'égalité professionnelle",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="montant_depenses_formation_securite",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Montant des dépenses de formation à la sécurité réalisées dans l'entreprise",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_accidents_par_elements_materiels_femme",
            field=models.IntegerField(
                blank=True,
                help_text="Faire référence aux codes de classification des éléments matériels des accidents (arrêté du 10 octobre 1974).",
                null=True,
                verbose_name="Répartition des accidents par éléments matériels chez les hommes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_accidents_par_elements_materiels_homme",
            field=models.IntegerField(
                blank=True,
                help_text="Faire référence aux codes de classification des éléments matériels des accidents (arrêté du 10 octobre 1974).",
                null=True,
                verbose_name="Répartition des accidents par éléments matériels chez les hommes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_accidents_trajet_avec_arret_femme",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre d'accidents de trajet ayant entraîné un arrêt de travail chez les hommes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_accidents_trajet_avec_arret_homme",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre d'accidents de trajet ayant entraîné un arrêt de travail chez les hommes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_accidents_travail_avec_arret_femme",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre d'accidents de travail ayant entraîné un arrêt de travail chez les femmes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_accidents_travail_avec_arret_homme",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre d'accidents de travail ayant entraîné un arrêt de travail chez les hommes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_analyses_produits_toxiques",
            field=models.IntegerField(
                blank=True,
                help_text="Renseignements tirés du rapport du directeur du service de prévention et de santé au travail interentreprises",
                null=True,
                verbose_name="Nombre de prélèvements, d'analyses de produits toxiques et mesures",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_et_denominations_maladies_pro_femme",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Nombre et dénomination des maladies professionnelles déclarées à la Sécurité sociale au cours de l'année concernant les femmes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_et_denominations_maladies_pro_homme",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Nombre et dénomination des maladies professionnelles déclarées à la Sécurité sociale au cours de l'année concernant les hommes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_journees_absence_accident_femme",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre de journée d'absence pour accidents de travail, accidents de trajet ou maladies professionnelles chez les femmes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_journees_absence_accident_homme",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre de journée d'absence pour accidents de travail, accidents de trajet ou maladies professionnelles chez les hommes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_jours_conges_paternite_pris",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="Nombre de jours de congés de paternité pris par le salarié par rapport au nombre de jours de congés théoriques",
                null=True,
                verbose_name="Jours de congés parternité",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_jours_feries_payes",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="Préciser, le cas échéant, les conditions restrictives.",
                null=True,
                verbose_name="Nombre de jours fériés payés",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_moyen_jours_conges_annuels",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="Repos compensateur non compris. Cet indicateur peut être calculé sur la dernière période de référence.",
                null=True,
                verbose_name="Nombre moyen de jours de congés annuels (non compris le repos compensateur)",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_personnes_exposees_bruit",
            field=models.IntegerField(
                blank=True,
                help_text="Les valeurs limites d'exposition et les valeurs d'exposition déclenchant une action de prévention qui sont fixées dans le tableau prévu à l'article R. 4431-2.",
                null=True,
                verbose_name="Nombre de personnes exposées de façon habituelle et régulière à plus de 80 à 85 db à leur poste de travail",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_personnes_horaires_alternant_ou_nuit",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre de personnes occupant des emplois à horaires alternant ou de nuit",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_personnes_horaires_alternant_ou_nuit_50_ans",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre de personnes occupant des emplois à horaires alternant ou de nuit de plus de cinquante ans",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_plans_specifiques_securite",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre de plans spécifiques de sécurité",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_2_jours_repos_hebdomadaire_consecutifs",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de salariés ayant bénéficié tout au long de l'année considérée de deux jours de repos hebdomadaire consécutifs",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_exposes_intemperies",
            field=models.IntegerField(
                blank=True,
                help_text="Au sens de l'article L. 5424-8 : Sont considérées comme intempéries, les conditions atmosphériques et les inondations lorsqu'elles rendent dangereux ou impossible l'accomplissement du travail eu égard soit à la santé ou à la sécurité des salariés, soit à la nature ou à la technique du travail à accomplir.",
                null=True,
                verbose_name="Nombre de salariés travaillant aux intempéries de façon habituelle et régulière",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_exposes_temperatures",
            field=models.IntegerField(
                blank=True,
                help_text="Au sens des articles R. 4223-13 à R. 4223-15",
                null=True,
                verbose_name="Nombre de salariés exposés au froid et à la chaleur",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_exposes_temperatures_extremes",
            field=models.IntegerField(
                blank=True,
                help_text="Au sens de l'article D. 4163-2 : température inférieure ou égale à 5 degrés Celsius ou au moins égale à 30 degrés Celsius pour minimum 900 heures par an.",
                null=True,
                verbose_name="Nombre de salariés exposés aux températures extrêmes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_horaires_individualises",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="Au sens de l'article L. 3121-48.",
                null=True,
                verbose_name="Nombre de salariés bénéficiant d'un système d'horaires individualisés",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_repos_compensateur_code_travail",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="Au sens des dispositions du code du travail et du code rural et de la pêche maritime instituant un repos compensateur en matière d'heures supplémentaires.",
                null=True,
                verbose_name="Nombre de salariés ayant bénéficié d'un repos compensateur au titre du code du travail",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_repos_compensateur_regime_conventionne",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de salariés ayant bénéficié d'un repos compensateur au titre d'un régime conventionne",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_temps_partiel_20_30_heures",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="Au sens de l'article L. 3123-1.",
                null=True,
                verbose_name="Nombre de salariés employés à temps partiel entre 20 et 30 heures (33)",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_temps_partiel_autres",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de salariés employés sous d'autres formes de temps partiel",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_temps_partiel_choisi_ayant_repris_temps_plein_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de salariées femme à temps partiel choisi ayant repris un travail à temps plein",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_temps_partiel_choisi_ayant_repris_temps_plein_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de salariés homme à temps partiel choisi ayant repris un travail à temps plein",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_temps_partiel_choisi_femme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de salariées femme ayant accédé au temps partiel choisi",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_salaries_temps_partiel_choisi_homme",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de salariés homme ayant accédé au temps partiel choisi",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_taches_repetitives",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=["hommes", "femmes"],
                help_text="Au sens de l'article D. 4163-2",
                null=True,
                verbose_name="Nombre de salarié(e)s affectés à des tâches répétitives",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_unites_absence",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="Ne sont pas comptés parmi les absences : les diverses sortes de congés, les conflits et le service national.",
                null=True,
                verbose_name="Nombre de journées d'absence",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_unites_absence_accidents",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de journées d'absence pour accidents du travail et de trajet ou maladies professionnelles",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_unites_absence_autres",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de journées d'absence imputables à d'autres causes",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_unites_absence_conges_autorises",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                help_text="(événements familiaux, congés spéciaux pour les femmes …)",
                null=True,
                verbose_name="Nombre de journées d'absence pour congés autorisés",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_unites_absence_maladie",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de journées d'absence pour maladie",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_unites_absence_maternite",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                null=True,
                verbose_name="Nombre de journées d'absence pour maternité",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="nombre_unites_theoriques_travaillees",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre de journées théoriques travaillées",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="objectifs_progression",
            field=models.TextField(
                blank=True,
                help_text="Définition qualitative et quantitative des mesures permettant de les atteindre conformément à l'article R. 2242-2. Evaluation de leur coût. Echéancier des mesures prévues",
                null=True,
                verbose_name="Objectifs de progression pour l'année à venir et indicateurs associés",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="participation_accueil_petite_enfance",
            field=models.BooleanField(
                default=False,
                verbose_name="Participation de l'entreprise et du comité social et économique aux modes d'accueil de la petite enfance",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="taux_realisation_programme_securite",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Taux de réalisation du programme de sécurité présenté l'année précédente",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="unite_absenteisme",
            field=models.CharField(
                choices=[("J", "Journées"), ("1/2J", "1/2 journées"), ("H", "Heures")],
                default="J",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="bdese",
            name="effectif_age",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=[
                    "moins de 30 ans",
                    "30 à 39 ans",
                    "40 à 49 ans",
                    "50 ans et plus",
                ],
                null=True,
                verbose_name="Effectif par âge",
            ),
        ),
    ]
