# Generated by Django 4.1.2 on 2022-10-13 09:02

from django.db import migrations, models
import django.forms.fields
import public.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "public",
            "0016_bdese_experiences_transformation_organisation_travail_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese",
            name="evolution_amortissement",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Evolution des actifs nets d’amortissement et de dépréciations éventuelles (immobilisations)",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="evolution_productivite",
            field=models.TextField(
                blank=True,
                help_text="lorsque ces éléments sont mesurables dans l’entreprise",
                null=True,
                verbose_name="Evolution de la productivité et le taux d’utilisation des capacités de production",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="montant_depenses_recherche_developpement",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Dépenses de recherche et développement",
            ),
        ),
        migrations.AlterField(
            model_name="bdese",
            name="nombre_visites_medicales",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=["droit commun", "individuel renforcé"],
                help_text="Selon le type de suivi",
                null=True,
                verbose_name="Nombre de visites d'information et de prévention des travailleurs",
            ),
        ),
    ]
