# Generated by Django 4.1.2 on 2022-10-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0017_bdese_evolution_amortissement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese",
            name="capitaux_propres",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Capitaux propres de l'entreprise"
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="emprunts_et_dettes_financieres",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Emprunts et dettes financières dont échéances et charges financières",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="impots_et_taxes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
