# Generated by Django 4.1.2 on 2022-10-13 09:56

from django.db import migrations, models
import django.forms.fields
import public.models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0018_bdese_capitaux_propres_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdese",
            name="evolution_salariale_par_categorie",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField, blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="evolution_salariale_par_sexe",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=["homme", "femme"],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="frais_personnel",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Frais de personnel, y compris cotisations sociales",
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="salaire_base_minimum_par_categorie",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField, blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="salaire_base_minimum_par_sexe",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=["homme", "femme"],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="salaire_median_par_categorie",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField, blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="salaire_median_par_sexe",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=["homme", "femme"],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="salaire_moyen_par_categorie",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField, blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="bdese",
            name="salaire_moyen_par_sexe",
            field=public.models.CategoryField(
                base_field=django.forms.fields.IntegerField,
                blank=True,
                categories=["homme", "femme"],
                null=True,
            ),
        ),
    ]
