# Generated by Django 4.1.7 on 2023-03-07 10:33
from django.db import migrations


def forwards(apps, schema_editor):
    if not schema_editor.connection.vendor.startswith("postgres"):
        print("Database vendor: {}".format(schema_editor.connection.vendor))
        print("Skipping migration without attempting to sync the sequence")
        return

    schema_editor.execute(
        """SELECT setval(pg_get_serial_sequence('"habilitations_habilitation"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "habilitations_habilitation";"""
    )


def backwards(apps, schema_editor):
    if not schema_editor.connection.vendor.startswith("postgres"):
        print("Database vendor: {}".format(schema_editor.connection.vendor))
        print("Skipping migration without attempting to sync the sequence")
        return

    schema_editor.execute(
        """SELECT setval(pg_get_serial_sequence('"entreprises_habilitation"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "entreprises_habilitation";"""
    )


class Migration(migrations.Migration):

    dependencies = [
        ("habilitations", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO habilitations_habilitation (
                id,
                fonctions,
                entreprise_id,
                user_id,
                confirmed_at
            )
            SELECT
                id,
                fonctions,
                entreprise_id,
                user_id,
                confirmed_at
            FROM
                entreprises_habilitation;
        """,
            reverse_sql="""
            INSERT INTO entreprises_habilitation (
                id,
                fonctions,
                entreprise_id,
                user_id,
                confirmed_at
            )
            SELECT
                id,
                fonctions,
                entreprise_id,
                user_id,
                confirmed_at
            FROM
                habilitations_habilitation;
        """,
        ),
        migrations.RunPython(forwards, backwards, atomic=True),
    ]
