# Generated by Django 4.2 on 2023-04-26 08:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("habilitations", "0002_copy_habilitations_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habilitation",
            name="confirmed_at",
            field=models.DateTimeField(null=True, verbose_name="Confirmée le"),
        ),
    ]
