# Generated by Django 4.2 on 2023-06-22 13:48
import django.utils.timezone
from django.db import migrations
from django.db import models


def guess_habilitaion_creation_date(apps, schema_editor):
    Habilitation = apps.get_model("habilitations", "Habilitation")
    for habilitation in Habilitation.objects.all():
        if created_at := habilitation.user.created_at:
            habilitation.created_at = created_at
            habilitation.updated_at = created_at
            habilitation.save()


class Migration(migrations.Migration):

    dependencies = [
        ("habilitations", "0003_alter_habilitation_confirmed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="habilitation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="habilitation",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(
            guess_habilitaion_creation_date,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
