# Generated by Django 5.1.8 on 2025-04-09 09:19
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0048_entreprise_code_naf"),
        ("habilitations", "0005_alter_habilitation_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habilitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("propriétaire", "Propriétaire"),
                    ("éditeur", "Éditeur"),
                    ("lecteur", "Lecteur"),
                ],
                default="propriétaire",
                max_length=20,
                verbose_name="rôle",
            ),
        ),
        migrations.AlterField(
            model_name="habilitation",
            name="confirmed_at",
            field=models.DateTimeField(null=True, verbose_name="confirmée le"),
        ),
        migrations.AlterField(
            model_name="habilitation",
            name="fonctions",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="fonction(s) dans la société",
            ),
        ),
        migrations.AlterField(
            model_name="habilitation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
        migrations.AddConstraint(
            model_name="habilitation",
            constraint=models.UniqueConstraint(
                fields=("entreprise", "user"),
                name="role_entreprise_user",
            ),
        ),
    ]
