# Generated by Django 5.1.8 on 2025-05-02 09:21
import django.core.validators
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprises", "0048_entreprise_code_naf"),
        (
            "habilitations",
            "0006_habilitation_role_alter_habilitation_confirmed_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="habilitation",
            name="role_entreprise_user",
        ),
        migrations.AlterField(
            model_name="habilitation",
            name="fonctions",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(250),
                ],
                verbose_name="fonction(s) dans la société",
            ),
        ),
        migrations.AlterField(
            model_name="habilitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("proprietaire", "Propriétaire"),
                    ("editeur", "Éditeur"),
                    ("lecteur", "Lecteur"),
                ],
                default="proprietaire",
                max_length=20,
                verbose_name="rôle",
            ),
        ),
        migrations.AddConstraint(
            model_name="habilitation",
            constraint=models.UniqueConstraint(
                fields=("entreprise", "user"), name="unique_entreprise_user"
            ),
        ),
    ]
