# Generated by Django 5.1.7 on 2025-05-12 17:09
from django.db import migrations


def remove_accent_in_proprietaire(apps, schema_editor):
    Habilitation = apps.get_model("habilitations", "Habilitation")
    for habilitation in Habilitation.objects.all():
        habilitation.role = "proprietaire"
        habilitation.save()


class Migration(migrations.Migration):
    dependencies = [
        ("habilitations", "0007_remove_habilitation_role_entreprise_user_and_more"),
    ]

    operations = [
        migrations.RunPython(
            remove_accent_in_proprietaire,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
