# Generated by Django 5.1.7 on 2025-06-24 08:16
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("habilitations", "0007_remove_habilitation_role_entreprise_user_and_more"),
        ("invitations", "0004_invitation_date_acceptation"),
    ]

    operations = [
        migrations.AddField(
            model_name="habilitation",
            name="invitation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invitations.invitation",
                verbose_name="invitation",
            ),
        ),
    ]
