# Generated by Django 5.1.11 on 2025-06-25 13:20
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("habilitations", "0008_habilitation_invitation"),
        ("invitations", "0005_alter_invitation_inviteur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habilitation",
            name="invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invitations.invitation",
                verbose_name="invitation",
            ),
        ),
    ]
