# Generated by Django 5.1.15 on 2026-02-05 15:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("habilitations", "0009_alter_habilitation_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="habilitation",
            name="is_conseiller_rse",
            field=models.BooleanField(default=False, verbose_name="conseiller RSE"),
        ),
    ]
