# Generated by Django 5.1.15 on 2026-03-26 17:11
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habilitations", "0010_habilitation_is_conseiller_rse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habilitation",
            name="confirmed_at",
        ),
    ]
