# Generated by Django 5.2.16 on 2026-07-22 14:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("habilitations", "0011_remove_habilitation_confirmed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habilitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("proprietaire", "Administrateur"),
                    ("editeur", "Contributeur"),
                    ("lecteur", "Lecteur"),
                ],
                default="proprietaire",
                max_length=20,
                verbose_name="rôle",
            ),
        ),
    ]
