# Generated by Django 4.2 on 2023-06-22 08:42
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "impact_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("ajoutee_le", models.DateTimeField()),
                ("modifiee_le", models.DateTimeField()),
                ("siren", models.CharField(max_length=9, unique=True)),
                ("denomination", models.CharField(max_length=250)),
                ("effectif", models.CharField(max_length=9, null=True)),
                ("bdese_accord", models.BooleanField(null=True)),
                ("nombre_utilisateurs", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "impact_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("ajoute_le", models.DateTimeField()),
                ("modifie_le", models.DateTimeField()),
                ("reception_actualites", models.BooleanField()),
                ("email_confirme", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Habilitation",
            fields=[
                (
                    "impact_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("fonctions", models.CharField(max_length=250, null=True)),
                ("confirmee_le", models.DateTimeField(null=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metabase.entreprise",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metabase.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entreprise",
            name="utilisateurs",
            field=models.ManyToManyField(
                through="metabase.Habilitation", to="metabase.utilisateur"
            ),
        ),
    ]
