# Generated by Django 4.1.5 on 2023-02-01 10:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="updated_at",
            field=models.DateTimeField(),
        ),
    ]
