# Generated by Django 4.2 on 2023-07-12 14:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0002_habilitation_ajoutee_le_habilitation_modifiee_le"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="date_cloture_exercice",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="systeme_management_energie",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="tranche_bilan",
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="tranche_chiffre_affaires",
            field=models.CharField(max_length=9, null=True),
        ),
    ]
