# Generated by Django 4.2.2 on 2023-08-08 13:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0004_entreprise_appartient_groupe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="effectif_outre_mer",
            field=models.CharField(max_length=9, null=True),
        ),
    ]
