# Generated by Django 4.2.3 on 2023-08-31 13:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("metabase", "0005_entreprise_effectif_outre_mer"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="effectif_groupe",
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="societe_mere_en_france",
            field=models.BooleanField(null=True),
        ),
    ]
