# Generated by Django 4.2 on 2023-06-21 16:37
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0005_alter_entreprise_bdese_accord"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impact_id", models.BigIntegerField(unique=True)),
                ("cree_le", models.DateTimeField()),
                ("modifie_le", models.DateTimeField()),
                ("reception_actualites", models.BooleanField()),
                ("email_valide", models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name="entreprise",
            name="impact_id",
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="nombre_utilisateurs",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="Habilitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fonctions", models.CharField(max_length=250, null=True)),
                ("confirmee_le", models.DateTimeField(null=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metabase.entreprise",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metabase.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entreprise",
            name="utilisateurs",
            field=models.ManyToManyField(
                through="metabase.Habilitation", to="metabase.utilisateur"
            ),
        ),
    ]
