# Generated by Django 4.2 on 2023-06-22 07:57
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0006_utilisateur_entreprise_impact_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entreprise",
            old_name="created_at",
            new_name="ajoutee_le",
        ),
        migrations.RenameField(
            model_name="entreprise",
            old_name="updated_at",
            new_name="modifiee_le",
        ),
        migrations.RenameField(
            model_name="utilisateur",
            old_name="cree_le",
            new_name="ajoute_le",
        ),
        migrations.RenameField(
            model_name="utilisateur",
            old_name="email_valide",
            new_name="email_confirme",
        ),
    ]
