# Generated by Django 4.2.3 on 2023-08-31 13:42
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("metabase", "0006_entreprise_effectif_groupe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="connecte_le",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="nombre_entreprises",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
