# Generated by Django 4.2.6 on 2023-10-26 10:34
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0007_utilisateur_connecte_le_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="date_derniere_qualification",
            field=models.DateField(null=True),
        ),
    ]
