# Generated by Django 4.2.3 on 2023-11-09 14:53
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("metabase", "0008_entreprise_date_derniere_qualification"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="categorie_juridique_sirene",
            field=models.IntegerField(null=True),
        ),
    ]
