# Generated by Django 4.2.7 on 2023-11-23 18:18
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0010_entreprise_effectif_groupe_permanent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BDESE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("est_soumise", models.BooleanField(null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("A ACTUALISER", ""),
                            ("EN COURS", ""),
                            ("A JOUR", ""),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metabase.entreprise",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metabase.utilisateur",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
