# Generated by Django 4.2.7 on 2024-01-03 14:40
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0014_bges"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="effectif_groupe_france",
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="est_societe_mere",
            field=models.BooleanField(null=True),
        ),
    ]
