# Generated by Django 4.2.11 on 2024-05-24 09:11
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0016_entreprise_est_interet_public_entreprise_pays"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="code_NAF",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
