# Generated by Django 5.1.7 on 2025-06-06 12:44
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metabase", "0017_entreprise_code_naf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entreprise",
            name="effectif_permanent",
        ),
    ]
