# Generated by Django 5.1.7 on 2025-06-24 14:46
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0017_entreprise_code_naf"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "impact_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("ajoutee_le", models.DateTimeField()),
                ("modifiee_le", models.DateTimeField()),
                ("role", models.CharField(max_length=20)),
                ("date_acceptation", models.DateTimeField(null=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metabase.entreprise",
                    ),
                ),
                (
                    "inviteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="metabase.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="habilitation",
            name="invitation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="metabase.invitation",
            ),
        ),
    ]
