# Generated by Django 5.1.7 on 2025-06-10 16:07
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("metabase", "0019_remove_entreprise_effectif_groupe_permanent"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="effectif_securite_sociale",
            field=models.CharField(max_length=9, null=True),
        ),
    ]
