# Generated by Django 5.1.7 on 2025-06-10 13:45
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metabase", "0019_remove_entreprise_effectif_permanent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entreprise",
            name="effectif_groupe_permanent",
        ),
    ]
