# Generated by Django 5.1.7 on 2025-06-11 14:29
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0021_entreprise_effectif_securite_sociale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bdese",
            name="utilisateur",
        ),
    ]
