# Generated by Django 5.1.11 on 2025-07-18 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0022_remove_bdese_utilisateur"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSRD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("est_soumise", models.BooleanField(null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("A ACTUALISER", ""),
                            ("EN COURS", ""),
                            ("A JOUR", ""),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("etape_validee", models.TextField(null=True)),
                ("nb_documents_ia", models.IntegerField(default=0)),
                ("nb_iro_selectionnes", models.IntegerField(default=0)),
                ("lien_rapport", models.BooleanField(default=False)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metabase.entreprise",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
