# Generated by Django 5.1.11 on 2025-08-15 11:16
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0023_csrd"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempBGES",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("siren", models.CharField(max_length=9, verbose_name="numéro SIREN")),
                (
                    "dt_publication",
                    models.DateField(verbose_name="date de publication"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["dt_publication"], name="dt_publication_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="TempEgaPro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("siren", models.CharField(max_length=9, verbose_name="numéro SIREN")),
                (
                    "annee",
                    models.CharField(max_length=4, verbose_name="année de publication"),
                ),
                (
                    "reponse_api",
                    models.JSONField(null=True, verbose_name="réponse de l'API"),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("siren", "annee"), name="unique_siren_annee"
                    )
                ],
            },
        ),
    ]
