# Generated by Django 5.1.12 on 2025-10-07 10:37
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0024_tempbges_tempegapro"),
    ]

    operations = [
        migrations.CreateModel(
            name="VSME",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("est_soumise", models.BooleanField(null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("A ACTUALISER", ""),
                            ("EN COURS", ""),
                            ("A JOUR", ""),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("cree_le", models.DateTimeField()),
                ("modifie_le", models.DateTimeField()),
                ("nb_indicateurs_completes", models.IntegerField(default=0)),
                ("progression", models.IntegerField(default=0)),
                ("progression_B1", models.IntegerField(default=0)),
                ("progression_B2", models.IntegerField(default=0)),
                ("progression_B3", models.IntegerField(default=0)),
                ("progression_B4", models.IntegerField(default=0)),
                ("progression_B5", models.IntegerField(default=0)),
                ("progression_B6", models.IntegerField(default=0)),
                ("progression_B7", models.IntegerField(default=0)),
                ("progression_B8", models.IntegerField(default=0)),
                ("progression_B9", models.IntegerField(default=0)),
                ("progression_B10", models.IntegerField(default=0)),
                ("progression_B11", models.IntegerField(default=0)),
                ("progression_C1", models.IntegerField(default=0)),
                ("progression_C2", models.IntegerField(default=0)),
                ("progression_C3", models.IntegerField(default=0)),
                ("progression_C4", models.IntegerField(default=0)),
                ("progression_C5", models.IntegerField(default=0)),
                ("progression_C6", models.IntegerField(default=0)),
                ("progression_C7", models.IntegerField(default=0)),
                ("progression_C8", models.IntegerField(default=0)),
                ("progression_C9", models.IntegerField(default=0)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metabase.entreprise",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
