# Generated by Django 5.1.12 on 2025-10-07 08:03
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0024_tempbges_tempegapro"),
    ]

    operations = [
        migrations.CreateModel(
            name="VSME",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("est_soumise", models.BooleanField(null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("A ACTUALISER", ""),
                            ("EN COURS", ""),
                            ("A JOUR", ""),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("nb_indicateurs_completes", models.IntegerField(default=0)),
                ("progression", models.IntegerField(default=0)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metabase.entreprise",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
