# Generated by Django 5.1.12 on 2025-10-30 16:27
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0025_vsme"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyseIA",
            fields=[
                (
                    "impact_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("ajoutee_le", models.DateTimeField()),
                ("modifiee_le", models.DateTimeField()),
                ("csrd", models.BooleanField(default=False)),
                ("etat", models.CharField(max_length=144, null=True)),
                ("message", models.CharField(max_length=144, null=True)),
                ("nb_phrases", models.IntegerField(null=True)),
                ("nb_phrases_pertinentes", models.IntegerField(null=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metabase.entreprise",
                    ),
                ),
            ],
        ),
    ]
