# Generated by Django 5.1.12 on 2025-11-07 10:04
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0026_analyseia"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyseia",
            name="nom_fichier",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
