# Generated by Django 5.1.15 on 2026-01-29 10:10
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0027_analyseia_nom_fichier"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="conseiller_rse",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
