# Generated by Django 5.1.12 on 2026-03-06 15:28
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0028_utilisateur_conseiller_rse"),
    ]

    operations = [
        migrations.AddField(
            model_name="vsme",
            name="premier_indicateur_cree_le",
            field=models.DateTimeField(null=True),
        ),
    ]
