# Generated by Django 5.1.15 on 2026-03-26 17:12
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0029_vsme_premiere_vsme_cree_le"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habilitation",
            name="confirmee_le",
        ),
    ]
