# Generated by Django 5.1.15 on 2026-04-02 13:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0030_remove_habilitation_confirmee_le"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="code_postal",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
