# Generated by Django 5.1.15 on 2026-04-16 15:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0032_remove_entreprise_systeme_management_energie"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="tranche_consommation_energie_finale",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
