# Generated by Django 5.1.15 on 2026-04-24 07:38
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0033_entreprise_tranche_consommation_energie_finale"),
    ]

    operations = [
        migrations.AddField(
            model_name="vsme",
            name="annee_cloture",
            field=models.PositiveIntegerField(
                default=1970
            ),  # il y a besoin d'une valeur par défaut sur ce champ non nul mais il sera correctement rempli dès la première synchro réalisée après la migration
            preserve_default=False,
        ),
    ]
