# Generated by Django 5.1.15 on 2026-05-21 09:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0034_vsme_annee_cloture"),
    ]

    operations = [
        migrations.AddField(
            model_name="vsme",
            name="choix_module",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
