# Generated by Django 5.2.17 on 2026-09-25 08:52
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0035_vsme_choix_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyseia",
            name="etat_v2",
            field=models.CharField(max_length=144, null=True),
        ),
        migrations.AddField(
            model_name="analyseia",
            name="message_v2",
            field=models.CharField(max_length=144, null=True),
        ),
        migrations.AddField(
            model_name="analyseia",
            name="nb_indicateurs",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="analyseia",
            name="nb_informations",
            field=models.IntegerField(null=True),
        ),
    ]
