# Generated by Django 5.2.17 on 2026-09-25 12:42
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metabase", "0036_analyseia_etat_v2_analyseia_message_v2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analyseia",
            old_name="etat",
            new_name="etat_v1",
        ),
        migrations.RenameField(
            model_name="analyseia",
            old_name="message",
            new_name="message_v1",
        ),
    ]
