@startuml
left to right direction
actor "Visiteur" as visiteur
actor "recherche-entreprise.api.gouv.fr" as apiRE
actor "egapro.travail.gouv.fr" as apiEP
actor "brevo.com" as apiBrevo

rectangle portail-rse.beta.gouv.fr {
  usecase "Consultation des réglementations" as UC1
  usecase "Simulation d'une entreprise" as UC2
  usecase "Evaluation détaillée d'une entreprise" as UC3
  usecase "Remplissage BDESE" as UC4
  usecase "Création de compte" as UC5
  usecase "Connexion" as UC6

  'usecase "Consultation de données" as C1
  'usecase "Modification de données" as C1
}
visiteur --> UC1
visiteur --> UC2
visiteur --> UC3
visiteur --> UC4
visiteur --> UC5
visiteur --> UC6
UC2 --> apiRE
UC2 --> apiEP
UC3 --> apiEP
UC4 --> apiEP
UC5 --> apiBrevo

'actor "Administrateur" as admin
'admin --> C1
@enduml
