@startditaa(--no-shadows)

                 portail-rse.beta.gouv.fr                                    stats.portail-rse.beta.gouv.fr
            +--------------------------------+                             +--------------------------------+
            |                                |     données anonymisées     |                                |
            |      Service Portail RSE       |                             |       Service Metabase         |
            |                                |        +----------+         |                                |
            |                                |        |          |         |                                |
            |                                +------->|PostgreSQL|-------->+                                |
            |                     +----------+        |       {s}|         |                     +----------+
            |                     |          |        +----------+         |                     |          |
            |                     |PostgreSQL|                             |                     |PostgreSQL|
            |                     |       {s}|                             |                     |       {s}|
            +------+-----------+--+----------+                             +---------------------+----------+
                   ^           |
                   |           |
                   |           |
                   |           |
                   |           |    API Brevo
   API Recherche entreprises   +--> API Sentry
   API Index EgaPro                 API Matomo

@endditaa
