@startditaa(--no-shadows, scale=0.8)

                 portail-rse.beta.gouv.fr                              stats.portail-rse.beta.gouv.fr
            +--------------------------------+                       +--------------------------------+
            |                                |                       |                                |
            |        Service Django          |                       |           Metabase             |
            |                                |                       |                                |
            |                                |  données anonymisées  |                                |
            |                                +---------------------->+                                |
            |         PostgreSQL             |                       |          PostgreSQL            |
            |                                |                       |                                |
            |                                |                       |                                |
            +------+-------------+-----------+                       +--------------------------------+
                   ^             |
                   |             |
   API recherche entreprises     +--> API envoi d'e-mail
   API Index EgaPro                   API Sentry
                                      API Matomo
@endditaa
