# Generated by Django 5.1.11 on 2025-06-22 10:00
import uuid

import django.contrib.postgres.indexes
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="identifiant",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de création"
                    ),
                ),
                (
                    "level",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (50, "CRITICAL"),
                            (40, "ERROR"),
                            (30, "WARNING"),
                            (20, "INFO"),
                            (10, "DEBUG"),
                            (0, "NOTSET"),
                        ],
                        editable=False,
                        verbose_name="niveau de log",
                    ),
                ),
                ("msg", models.TextField(blank=True, verbose_name="message")),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="contenu supplémentaire (JSON)",
                    ),
                ),
            ],
            options={
                "verbose_name": "historique des évenements",
                "verbose_name_plural": "historique des évenements",
                "indexes": [
                    django.contrib.postgres.indexes.BrinIndex(
                        autosummarize=True,
                        fields=["created_at"],
                        name="idx_logs_eventlog_created_at",
                    ),
                    models.Index(fields=["level"], name="logs_eventl_level_d95a0b_idx"),
                ],
            },
        ),
    ]
